### ISSUE TITLE
能否添加一个swap图形化的展示

### ISSUE THREAD

**Issue by Salomens** [lollipopkit/flutter_server_box#10]
![image](https://user-images.githubusercontent.com/64776123/219258842-571fbddc-e3b5-40b3-bc5d-3099c5599d4a.png)
辛苦大佬类似与xui这种
![image](https://user-images.githubusercontent.com/64776123/219259111-66258679-92d1-4de4-b2a9-3738adab2b05.png)

**Comment by lollipopkit** [comment]
![MVIMG_20230216_122319](https://user-images.githubusercontent.com/10864310/219268506-a462b613-8e56-49a3-aac3-9ef82a5ee67a.jpeg)
