### ISSUE TITLE
鸿蒙OS安装时提示无证书

### ISSUE THREAD

**Issue by jgc9527** [lollipopkit/flutter_server_box#103]
**描述BUG**

**复现步骤**

**期望结果**

**实际结果**

**截图**

![Screenshot_20230806_204840_com.android.packageinstaller.png](https://github.com/lollipopkit/flutter_server_box/assets/94273329/e9b1081b-6597-4d98-b838-4f8928c6a184)

**设备**

**更多信息**

**Comment by Mayuejin-github** [comment]
目测像签名版本问题

**Comment by lollipopkit** [comment]
https://wen.baidu.com/question/1806191796501393867.html

估计只有：
- 上架华为商店
- 关闭纯净模式

才能解决

**Comment by Mayuejin-github** [comment]
> https://wen.baidu.com/question/1806191796501393867.html
> 
> 估计只有：
> - 上架华为商店
> - 关闭纯净模式
> 
> 才能解决

纯净模式是关闭的，我尝试了使用mt管理器之类的来自签证书，但是安装不了

**Comment by lollipopkit** [comment]
我也没华为设备，不知道做了什么**魔改**

等其他人来解决，暂时搁置

**Comment by jgc9527** [comment]
奇怪，今天又可以安装了

**Comment by jgc9527** [comment]
在连接Linux服务器时会出现这个问题!(Linux版本为Debian11）[Screenshot_20230808_151033_tech.lolli.toolbox.png](https://github.com/lollipopkit/flutter_server_box/assets/94273329/3edbbf86-d2f9-4c5f-b5d1-cebc80eb4409)
![Screenshot_20230808_151232_com.server.auditor.ssh.client.png](https://github.com/lollipopkit/flutter_server_box/assets/94273329/55ae83ff-d3ad-498b-83fc-6b82effaad41)

**Comment by lollipopkit** [comment]
安装没问题就关闭了，上述问题请到 #114 查看
