### ISSUE TITLE
iOS 15使用glances命令会报错，安卓10正常。报错界面如下

### ISSUE THREAD

**Issue by allonmymind** [lollipopkit/flutter_server_box#106]
![image](https://github.com/lollipopkit/flutter_server_box/assets/18719713/c1af14c8-aff6-45b5-91b4-824b17a04e80)

**Comment by lollipopkit** [comment]
这个问题看上去与 app 功能无关，可能是忘记了使用 `virtualenv`

**Comment by allonmymind** [comment]
> 这个问题看上去与 app 功能无关，可能是忘记了使用 `virtualenv`
忘记了使用 virtualenv如何理解，我改如何解决呢，能帮忙提供下解决办法不

**Comment by Iwctwbh** [comment]
source venv/bin/activate

**Comment by lollipopkit** [comment]
上面有回复，注意 venv 脚本的路径
极大概率与 ServerBox 无关，所以关闭

**Comment by allonmymind** [comment]
感谢，事实上我更新最近的版本后这个问题就解决了，没有用到source venv/bin/activate这个解决办法，所以应该不是我linux环境的问题，因为其他终端都能正常运行glances
