### ISSUE TITLE
请问这个会在服务器上安装探针之类的东东吗？

### ISSUE THREAD

**Issue by wxdjs** [lollipopkit/flutter_server_box#11]
请问这个会在服务器上安装探针之类的东东吗？还是只是通过监控命令获取状态？

**Comment by lollipopkit** [comment]
只是单纯通过运行 `.sh` 脚本获取，并且无需root权限。所以不用在意安全问题。

后期可能添加服务器端应用，未使用app时也能收到app的推送（Android上不好实现，可能会使用webhook替代），得知服务器运行状态（包括设定流量阈值，超过就提醒）

**Comment by soxft** [comment]
> 

可以允许用户配置一些比如 serverchan 之类的服务

**Comment by lollipopkit** [comment]
> 可以允许用户配置一些比如 serverchan 之类的服务

[已支持](https://github.com/lollipopkit/server_box_monitor)
