### ISSUE TITLE
tmux显示异常

### ISSUE THREAD

**Issue by lazyahko** [lollipopkit/flutter_server_box#113]
**描述BUG**

有时候第一行或前面几行不显示，有时候下面的绿色任务栏不显示

**复现步骤**

**期望结果**

**实际结果**

**截图**

![Screenshot_2023-08-08-06-57-19-647_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/29919984/cd8bde44-0724-4477-8522-71844d192383)
![Screenshot_2023-08-08-06-57-41-153_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/29919984/0df76884-6565-4d54-8276-55049f57d3e1)

**设备**

**更多信息**

**Comment by calvinweb** [comment]
This may be a bug if xterm.dart/这可能是xterm.dart的bug

**Comment by lollipopkit** [comment]
已告知 xterm.dart 作者，感谢你的反馈

**Comment by lollipopkit** [comment]
麻烦更新至 476 版本，测试是否仍然存在该问题

**Comment by lazyahko** [comment]
已经更新至476，问题依旧

![Screenshot_2023-08-17-19-38-50-448_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/29919984/681c235a-a8c1-4144-9d12-d8c3118a20ba)

![Screenshot_2023-08-17-19-38-57-572_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/29919984/0a98113c-f075-4063-9dda-0b62a5c85ba9)

**Comment by lollipopkit** [comment]
![Screenshot 2023-08-17 at 19 46 46](https://github.com/lollipopkit/flutter_server_box/assets/10864310/8e3b6643-6c88-4297-beed-6a50d4b71d08)


我这里没问题，感觉不是 tmux 的问题，是 shell 的问题

**Comment by lazyahko** [comment]
切换了bash也一样
![Screenshot_2023-08-17-19-49-43-540_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/29919984/a5458c9c-24ba-498e-bcee-965dfc13878d)
