### ISSUE TITLE
安卓小组件没有显示id

### ISSUE THREAD

**Issue by someone120** [lollipopkit/flutter_server_box#115]
配置小组件需要ID，文档说会显示在小组件里，但是没有显示。
![Screenshot_20230809-130835_Pixel 启动器](https://github.com/lollipopkit/flutter_server_box/assets/47704813/9e81f6eb-ea99-4998-ade9-acdb46316de3)

**Comment by zj1123581321** [comment]
Same issue on Redmi K50,Android12 ，How can I find the id?
