### ISSUE TITLE
自动刷新失效

### ISSUE THREAD

**Issue by People-11** [lollipopkit/flutter_server_box#118]
**描述BUG**
从 1.0.409 版本开始，即使在设置里设置了自动刷新间隔，也不会自动刷新，需要手动下拉才会刷新一下

**复现步骤**
1. 在设置里设置非0的自动刷新间隔
2. 升级到 1.0.409 版本
3. 主页以及详细页面都不会自动刷新

**期望结果**
1.0.407 版本的自动刷新正常

**实际结果**
1.0.409 到最新的 1.0.461 版本，自动刷新都不工作

**截图**

**设备**
Pixel 4 Android 11
1.0.409 - 1.0.461

**更多信息**

**Comment by lollipopkit** [comment]
已在 462 中修复，麻烦测试

**Comment by People-11** [comment]
已正常刷新
