### ISSUE TITLE
进入命令行切换后不可操作

### ISSUE THREAD

**Issue by Climit** [lollipopkit/flutter_server_box#124]
ServerBox进入命令行后，切换到其他app或返回桌面，过一段时间再返回ServerBox命令行就处于不可操作状态，除了返回任何操作不可用。

tips
1、偶见复制内容切换至命令行百度输入法粘贴后不可操作（可能是同一个问题）
2、系统环境：Android 13 - vivo X60 - 百度输入法

**Comment by lollipopkit** [comment]
检查系统设置，App 是否拥有 “后台无限制” / “自启动” 权限。

目前 App 在建立连接后，内置了 `keepAliveInterval` = 10s 的保活功能。

**Comment by lollipopkit** [comment]
已在 477 中实现断联提示返回

**Comment by lollipopkit** [comment]
已在 #139 中解决后台断连的问题，请更新至 491 后测试。
