### ISSUE TITLE
openwrt ssh问题

### ISSUE THREAD

**Issue by hange33** [lollipopkit/flutter_server_box#13]
ssh连接后进行任意一个操作（输入字符或粘贴）后就会导致该页面卡死，无法继续输入，也不能左右移动光标（可以正常返回主页面），本人四个服务器只有openwrt出现这个问题![Screenshot_2023-02-25-23-57-56-18_c5f0134a4c551757558202025a96fea6.jpg](https://user-images.githubusercontent.com/45906760/221367230-714754ea-9f96-4737-a57f-055df6ca0097.jpg)

**Comment by lollipopkit** [comment]
大概率是因为不兼容dropbear，已反馈问题至上游依赖

**Comment by lollipopkit** [comment]
https://user-images.githubusercontent.com/10864310/225288571-52ca78bd-d99d-4474-b22d-527e0bfd5679.mp4

麻烦更新至最新版测试，然后反馈，谢谢

**Comment by hange33** [comment]
> https://user-images.githubusercontent.com/10864310/225288571-52ca78bd-d99d-4474-b22d-527e0bfd5679.mp4
> 
> 麻烦更新至最新版测试，然后反馈，谢谢
> 

感谢，已经正常了，有个新的问题，更新不会保留原来的主题状态，我设置的黑暗更新后又变成自动了

**Comment by lollipopkit** [comment]
应该是因为我改了数据库内这项设置的key（nightMode重命名为themeMode），导致之前的设置失效了

可以再次设置为黑暗，再重启，应该就会正常
