### ISSUE TITLE
SSh图形界面显示不正常

### ISSUE THREAD

**Issue by xiyang12345** [lollipopkit/flutter_server_box#138]
使用ssh连接后打开图形界面,出现乱码，显示不正常。希
![Screenshot_20230819-115921](https://github.com/lollipopkit/flutter_server_box/assets/89056379/59245265-3d32-41c1-a7ae-6206a809c14b)
望能改进

**Comment by lollipopkit** [comment]
![Screenshot 2023-09-22 at 02 14 30](https://github.com/lollipopkit/flutter_server_box/assets/10864310/1d57fbb1-3c4b-4a9c-8535-76eae2e7e488)

升级到最新版本仍有这个问题吗？类似界面未发现问题

**Comment by lollipopkit** [comment]
合并至 #181，此处 Issue 将关闭。
