### ISSUE TITLE
软件进入后台后，ssh会断掉

### ISSUE THREAD

**Issue by DanielEcho** [lollipopkit/flutter_server_box#139]
**描述BUG**

软件进入后台后，ssh会断掉
**复现步骤**

上滑返回桌面后，等5秒再切回，点击屏幕呼出键盘后，输入没有反馈
同样服务器的ssh连接使用juicessh不会断开

**期望结果**

期望后台返回后ssh能继续使用

**实际结果**

后台返回后，显示ssh界面，实际输入没有反应

**截图**

**设备**

App版本:1.0.476
系统android13 miui14

**更多信息**

#20 和这个issue的问题差不多

**Comment by lollipopkit** [comment]
麻烦[下载](https://res.lolli.tech/serverbox/e5ec8d3c74dbffa1c1ad24c3eefe5c33ae58294954dfbaf0eb0344e8d935927c.apk)测试

**Comment by lollipopkit** [comment]
![Screenshot 2023-08-10 at 22 36 54](https://github.com/lollipopkit/flutter_server_box/assets/10864310/ade4cad6-10f7-48d7-b283-91b31dac677f)
我这里原生系统正常运行

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/4607e33b-2a0e-4e9e-b111-fbe613465354

**Comment by DanielEcho** [comment]
这个版本没有问题。已解决，谢谢
