### ISSUE TITLE
一个小建议(非bug)

### ISSUE THREAD

**Issue by fireinrain** [lollipopkit/flutter_server_box#142]
**Describe the bug**

**To Reproduce**

**Desired Results**

软件进入的默认页每次都是需要等待服务器连接成功才会显示图表， 是否可以优化成程序关闭前的最后数据
作为下次打开的默认数据，这个时候是不可点击的状态，然后服务器连接成功后自动刷新，能够点击图表
感觉每次打开都是列表在连接 然后一个一个蹦出图表 非常违和。 一个小建议，谢谢开发

**Actual Results**

**Screenshots**

**Device**

**Additional context**

**Comment by lollipopkit** [comment]
这个想法确实挺有创意的，但是不打算这样改，因为我倾向于实时向用户展示当前服务器的状态，而且这个动画是才加上去，至少我觉得很舒服很丝滑。

想法确实挺好的，真心感谢你的建议，不好意思，暂不采纳。
