### ISSUE TITLE
复制粘贴无效

### ISSUE THREAD

**Issue by xgzxmytx** [lollipopkit/flutter_server_box#145]
**描述BUG**

进入ssh界面后，在qq或者微信复制的东西，有一定几率无法粘贴在ssh里，因为无效，本来认为是手机问题，但是用termius每次都可以粘贴进去
**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
这段时间内，未能复现
