### ISSUE TITLE
反馈几个bug

### ISSUE THREAD

**Issue by LucaLin233** [lollipopkit/flutter_server_box#149]
**描述BUG**

1、配置密钥登录后，包管理不可用，之前版本使用密码登录时包管理功能正常

2、sftp中的编辑功能，疑似存在编辑完成保存后内容错位的现象，或者是已删除内容再次出现的现象，请排查一下是否有此问题

以上问题出现在版本1.0.501（当前最新商店版）以及更早的版本中

**复现步骤**

1、配置密钥登录，点击包管理功能
![image](https://github.com/lollipopkit/flutter_server_box/assets/78164141/0bd24eef-65d8-46ab-8605-08b84090fea3)
2、打开sftp，编辑任意内容

**期望结果**

1、正常使用包管理功能更新包

2、sftp功能能够正常编辑并保存内容

**实际结果**

1、无法使用包管理功能

2、sftp编辑功能疑似不正常

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/78164141/6d1fa06f-519c-4960-871b-f9f32fa00d44)

**设备**

系统为ios17.0beta7
app版本为1.0.501

**更多信息**

**Comment by lollipopkit** [comment]
- 包管理器已在 512 中修复
- sftp 可能是因为修改完成，但还未上传完成（sftp界面点击右上角，可以看到任务列表）

**Comment by LucaLin233** [comment]
> - 包管理器已在 512 中修复
> 
> - sftp 可能是因为修改完成，但还未上传完成（sftp界面点击右上角，可以看到任务列表）

包管理在更新后已正常使用
sftp我再继续观察一下
感谢佬的光速修复～

**Comment by lollipopkit** [comment]
如果仍有问题，请开启新的 issue
