### ISSUE TITLE
v1.0.525 Appstore 群晖无法ssh

### ISSUE THREAD

**Issue by YoYulyvW** [lollipopkit/flutter_server_box#153]
错误:Could not chdir to home directory /var/services/homes/lyvw: No such file or directory
mkdir: cannot create directory '/var/services/homes': File exists

群晖的路径都是/volume(x) 能否添加个取消定位sftp的

**Comment by RainSunMe** [comment]
你群晖SFTP服务没开？
文件服务 -> FTP -> SFTP -> 启动SFTP服务
