### ISSUE TITLE
希望编辑服务器时可以选择是否一打开就尝试获取状态

### ISSUE THREAD

**Issue by hausen1012** [lollipopkit/flutter_server_box#155]
因为我有些机器是异地组网，或者是要开vpn才能连接，所以希望配置连接的时候可以选择是否展示状态，不展示的话打开app就不尝试去连接了

**Comment by lollipopkit** [comment]
已实现，请更新至最新版后测试，若仍有问题，请再次开启。

**Comment by hausen1012** [comment]
已经下载测试，完美解决我的需求，感谢！！
