### ISSUE TITLE
Can we have an option to make these generic info fonts bigger?

### ISSUE THREAD

**Issue by ElTopo** [lollipopkit/flutter_server_box#156]
These fonts are tiny and hardly legible, both at the servers screen and the individual server screen, like in this screenshot:

![serverbox](https://github.com/lollipopkit/flutter_server_box/assets/217195/e57d6e99-66d5-4fd4-9a92-898017ac28a2)

TIA

**Comment by ElTopo** [comment]
感謝，但我找不到設置 textFactor 的地方，是否可以具體指明怎樣做，我讀了 WiKi，『长按**首页抽屉内的设置项**，进入 JSON 编辑模式』，不知是否指的是這個截圖裏面的 Settings，我長按它進到一個 Settings Editor，但是看不出 "textFactor": 1.5，應該加在哪裏，我寫在 “themeMode": 1 一行之後，發現無法保存（點對勾按鈕後再進來，我的修改不見了。）

![settings](https://github.com/lollipopkit/flutter_server_box/assets/217195/907e1e61-7d93-45da-bb27-e51661ea63d3)

**Comment by lollipopkit** [comment]
可能因为不符合json格式，所以未能保存设置（对于此问题，将新增格式错误提示）。

例如，修改前文件内容：
```
{
  "themeMode": 0
}
```
修改后：
```
{
  "themeMode": 0,
  "textFactor": 1.2
}
```
需要注意的是：
- 在你添加 `textFactor` 行的上一行的最后，加上 `,`
- `textFactor` 行最后不加 `,`

**Comment by ElTopo** [comment]
Thanks, it works now, I am kind of satisfied with `textFactor: 1.5`
