### ISSUE TITLE
备份功能失效

### ISSUE THREAD

**Issue by a1564471347** [lollipopkit/flutter_server_box#157]
**描述BUG**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/58d66ed7-2f24-4c2e-8cde-8253420e709e

未能发现问题，请详细描述bug

**Comment by a1564471347** [comment]
> trim.3D517E99-A8AC-40A1-A786-B4183B82B7FF.MOV 
> 
> 未能发现问题，请详细描述bug

就是点击备份按钮一点反应没有

**Comment by a1564471347** [comment]
> trim.3D517E99-A8AC-40A1-A786-B4183B82B7FF.MOV 
> 
> 未能发现问题，请详细描述bug

我ios17的iPhone和ios16.6的ipad都是这样点击备份按钮没有反应

**Comment by a1564471347** [comment]
> trim.3D517E99-A8AC-40A1-A786-B4183B82B7FF.MOV 
> 
> 未能发现问题，请详细描述bug

这个手动备份bug不知道什么原因，麻烦加入icloud自动同步备份功能

**Comment by lollipopkit** [comment]
手动点击备份，然后回到主页，点击右上角查看log，贴出截屏

**Comment by a1564471347** [comment]
> 手动点击备份，然后回到主页，点击右上角查看log，贴出截屏
好像根本没有反应，log里面都没有记录

![IMG_3151](https://github.com/lollipopkit/flutter_server_box/assets/65760851/946ff0a6-c028-4099-880d-57322a0cb5cb)

**Comment by a1564471347** [comment]
> 手动点击备份，然后回到主页，点击右上角查看log，贴出截屏

刚刚更新了新版本，ipad和iPhone上都开启了icloud开关，可是配置没有同步

**Comment by lollipopkit** [comment]
...哥们，发log截图
