### ISSUE TITLE
频繁发生prase failed

### ISSUE THREAD

**Issue by mostcute** [lollipopkit/flutter_server_box#159]
连接经常失败，不是每次都会失败，但是失败概率很高，两三次数据刷新就会遇到一次
 [SERVER][INFO]: Connected to block@192.168.50.89:22 in 6 ms.
I/flutter (10013): systype  == linux
E/flutter (10013): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)
E/flutter (10013): Sep

**Describe the bug**

**To Reproduce**

**Desired Results**

**Actual Results**

**Screenshots**

**Device**

**Additional context**

**Comment by mostcute** [comment]
追踪了一下代码，是执行时间date的时候有时候突然返回了月份 

```
I/flutter (10013): segments = 1694155279
I/flutter (10013): segments = 1694155279
I/flutter (10013): segments = 1694155280
I/flutter (20519): [SERVER][INFO]: Connected to block@192.168.50.89:22 in 4 ms.
I/flutter (10013): segments = 1694155282
I/flutter (10013): segments = Sep
I/flutter (10013): 1694155284
E/flutter (10013): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)

```

我在服务器上反复手动执行就没事

**Comment by mostcute** [comment]
有可能是新旧版本同时运行导致脚本被覆盖导致的冲突

**Comment by lollipopkit** [comment]
> 有可能是新旧版本同时运行导致脚本被覆盖导致的冲突

理论上确实存在该问题。。。下个版本优化
