### ISSUE TITLE
inner目录需要删除功能

### ISSUE THREAD

**Issue by mostcute** [lollipopkit/flutter_server_box#160]
**描述BUG**

![db0ee5a79e92e2f5b12a9a42b0e9a7a](https://github.com/lollipopkit/flutter_server_box/assets/23225426/6efc11ec-3b97-40c6-a25d-d5578ac29be6)

**复现步骤**

**期望结果**

期望能删除可以释放空间

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
文件点击即可删除，文件夹长按即可删除
