### ISSUE TITLE
1.0.545(+6)版本无法正常监测路由器

### ISSUE THREAD

**Issue by Ne0joke** [lollipopkit/flutter_server_box#163]
**描述BUG**

路由器是刷了梅林固件的华硕ax56u路由器，之前版本的软件能够正常登录并监视性能温度等参数
今天打开软件发现报错无法监视各种参数
最近没有用软件，不确定是不是这个版本新出现的问题
提示如下错误信息

Segments not match: 12

**期望结果**

**实际结果**

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/23270202/fe695172-be4d-4654-8441-fcacb0a3d4a3)

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
麻烦在终端执行 `uname`，并在此粘贴输出

**Comment by lollipopkit** [comment]
已解决（#184），请更新至 590，如仍有问题，请再次开启
