### ISSUE TITLE
希望作者考虑下iOS添加密码/脸部验证

### ISSUE THREAD

**Issue by fanzhebufan1** [lollipopkit/flutter_server_box#165]
希望作者考虑下iOS添加密码/脸部验证

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/45255a41-cf64-4f86-be79-d8fd5b3deb6a

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/e091f899-7125-4abc-b3d0-663f690d471b

**Comment by lollipopkit** [comment]
。。。我没说清楚，我的本意是告诉你该需求的进度（已经做好大部分，正在优化细节）
