### ISSUE TITLE
1.0.569 中生成新版脚本时使用了Heredoc，导致 fish 用户无法使用

### ISSUE THREAD

**Issue by wcbing** [lollipopkit/flutter_server_box#168]
**描述BUG**
更新 1.0.569 后无法使用，看报错（已贴到下面）应该是使用 Heredoc 生成新版本的脚本，但是fish并不支持这种语法。

**报错信息**
```fish
fish: Expected a string, but found a redirection
cat << 'EOF' > $HOME/.config/server_box/mobile_v16.sh
     ^
```

**设备**
- App版本：1.0.569

**Comment by lollipopkit** [comment]
麻烦更新至最新版测试 :)

**Comment by wcbing** [comment]
还是不行😂，应该是你没在 -c 后加引号

报错如下：
```
fish: Expected a string, but instead found a redirection
sh -c cat << 'EOF' > $HOME/.config/server_box/mobile_v17.sh
           ^
```

**Comment by lollipopkit** [comment]
就是因为单引号有问题才换的 heredoc，双引号的话脚本里一堆得转义，再想想别的方法吧

我自己老老实实装个 fish 试吧，麻烦了

**Comment by wcbing** [comment]
向上面这样直接加单引号不行吗，我测试是没问题的

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/6e4a55c6-9e6f-4d21-be74-79ab3b30f5d0)
zsh 不行

**Comment by wcbing** [comment]
好吧,你再想一想办法。

> 我自己老老实实装个 fish 试吧，麻烦了

是麻烦你了😂
