### ISSUE TITLE
关于命令界面按键显示错误的反馈

### ISSUE THREAD

**Issue by AssassinHjx** [lollipopkit/flutter_server_box#170]
![IMG_0625](https://github.com/lollipopkit/flutter_server_box/assets/91854457/a88d21bb-298d-4585-af10-beacc0fcd9be)
更新最新版后进入命令界面时，快捷按键栏显示为白色横条，删除服务器重新添加仍然这样。
机型为iPhone se3 系统为iOS16.5

**Comment by lollipopkit** [comment]
最新版已修复，如有问题请再次开启
