### ISSUE TITLE
support mosh

### ISSUE THREAD

**Issue by inos-github** [lollipopkit/flutter_server_box#171]
it would be very useful to establish connections via mosh, at least optionally, in order to prevent disruptions especially in regions with poor mobile networks and or when using the integrated terminal

**Comment by lollipopkit** [comment]
I'm very sorry.
Since dart doesn't have a mosh support library at the moment, there's no way to implement it (for me).

**Comment by inos-github** [comment]
Just found:
https://github.com/unixshells/mosh-dart
