### ISSUE TITLE
AppBug

### ISSUE THREAD

**Issue by Aeorq** [lollipopkit/flutter_server_box#173]
在sftp重命名时无法保存，点击重命名无反应1.0.575版本ios上不知道安卓能不能保存

Uploading RPReplay_Final1695577252.mp4…

**Comment by lollipopkit** [comment]
我这边 iOS/macOS 没有这个问题
https://github.com/lollipopkit/flutter_server_box/assets/10864310/6ab9bcc5-242b-4fd4-8796-64749098a160
