### ISSUE TITLE
不知道是不是Bug

### ISSUE THREAD

**Issue by Aeorq** [lollipopkit/flutter_server_box#174]
SFTP不能重命名中文文件夹，英文的可以了😳😳😳是不是我的系统版本太高了不适配呢ios16.6.1

https://github.com/lollipopkit/flutter_server_box/assets/130874582/8180f3f5-6664-477e-a90e-eb33bbdd8187

**Comment by lollipopkit** [comment]
中文我也没问题

https://github.com/lollipopkit/flutter_server_box/assets/10864310/6b2d5606-d95e-4c54-b5c1-505bed76984e

**Comment by lollipopkit** [comment]
可能是其他问题造成的，比如：没有文件权限，可以检查下
