### ISSUE TITLE
sftp编辑功能bug反馈

### ISSUE THREAD

**Issue by LucaLin233** [lollipopkit/flutter_server_box#175]
**描述BUG**

使用serverbox的sftp功能进行文件的编辑操作，编辑json文件时，点击保存上传成功后打开文件发现加上了很多回括号，诸如}、]之类，稳定复现，尚不清楚其他类型文件编辑会不会有此类问题

**复现步骤**

使用sftp的编辑功能
编辑json文件
保存，上传
再次编辑文件，发现加上很多括号，如}、]

**期望结果**

正常保存json文件，不额外加上括号

**实际结果**

json文件末尾加上了很多括号，如}、]

**截图**

![photo_2023-09-26_18-27-18](https://github.com/lollipopkit/flutter_server_box/assets/78164141/17b69e27-4933-4a6d-96c2-f08821bb0ffe)
![photo_2023-09-26_18-27-25](https://github.com/lollipopkit/flutter_server_box/assets/78164141/483de86a-b1d1-4695-8b1c-b13125dd47d0)

**设备**

iOS17.0.2，iphone15pro
APP版本：1.0.578(+4)

**更多信息**

**Comment by liujixu1984** [comment]
我也有这个现象 最后面有一些不是我的代码  删了保存又出现

**Comment by lollipopkit** [comment]
已于之前版本解决，如果仍有问题，请再次开启
