### ISSUE TITLE
支持Windows端

### ISSUE THREAD

**Issue by rong6** [lollipopkit/flutter_server_box#177]
希望能支持一下Windows端，照顾下win用户吧……

**Comment by lollipopkit** [comment]
[试试](https://github.com/lollipopkit/flutter_server_box#%EF%B8%8F-download)

**Comment by x2009again** [comment]
> [试试](https://github.com/lollipopkit/flutter_server_box#%EF%B8%8F-download)

windows的下载链接是无效的

**Comment by rong6** [comment]
> [试试](https://github.com/lollipopkit/flutter_server_box#%EF%B8%8F-download)

Windows下载链接无法打开

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/590.win.zip
不好意思

**Comment by rong6** [comment]
> https://res.lolli.tech/serverbox/590.win.zip
> 不好意思

感谢，已能下载。
还有想问下lolli.tech是干嘛的，打开显示slash，是什么自部署的东西吗？

**Comment by lollipopkit** [comment]
slash 是可以自己部署的一个短链/链接集合服务，GitHub上搜得到

**Comment by rong6** [comment]
> slash 是可以自己部署的一个短链/链接集合服务，GitHub上搜得到

好的，刚刚试了一下，win端无法自定义字体，字体路径并没有中文；此外，win端显示已连接后不显示CPU等信息。

**Comment by x2009again** [comment]
> https://res.lolli.tech/serverbox/590.win.zip 不好意思

谢谢。

**Comment by lollipopkit** [comment]
无法设置字体，开新的 issue 吧
