### ISSUE TITLE
关于armbian-config显示问题

### ISSUE THREAD

**Issue by Climit** [lollipopkit/flutter_server_box#178]
我同时使用了两款app（ServerBox与ConnectBot）连接armbian，并进入armbian-config显示的画面差异如图。
![IMG_20231003_225903](https://github.com/lollipopkit/flutter_server_box/assets/10386431/8dc8f3da-e6e1-4908-9f99-8a47ab0db341)
![IMG_20231003_225845](https://github.com/lollipopkit/flutter_server_box/assets/10386431/611df496-f1f2-4436-952d-e5d7e93d7888)

ps：可能在服务器储存空间满的情况，ServerBox会连接不上并报错（Seperate segments failed, raw:）。

**Comment by lollipopkit** [comment]
合并至 #181，此处 Issue 将关闭。
