### ISSUE TITLE
网速有可能显示为NaN

### ISSUE THREAD

**Issue by hwcwy** [lollipopkit/flutter_server_box#179]
**描述BUG**

主页面网速有可能显示为NaN

**复现步骤**

打开即可

**期望结果**

修复即可

**实际结果**

不显示NaN

**截图**

![Screenshot_20231004-163611.png](https://github.com/lollipopkit/flutter_server_box/assets/74729240/0aeed655-0f9f-4674-aeab-145ddf3aecdb)

**设备**

系统：Android13
App版本：1.0.578

**Comment by lollipopkit** [comment]
过几秒下一次刷新时还是NaN吗？如果下次刷新显示正常，那这是正常现象

**Comment by hwcwy** [comment]
> 过几秒下一次刷新时还是NaN吗？如果下次刷新显示正常，那这是正常现象

明白了
