### ISSUE TITLE
关于iOS客户端Apps

### ISSUE THREAD

**Issue by lzr52o** [lollipopkit/flutter_server_box#183]
怎么一股子安卓味，大佬能用原始Apple UI 开发文档做UI吗，谢谢🙏

**Comment by lollipopkit** [comment]
个人是 `Material Design` 忠实粉丝（乐于 使用并推广），并且再写一套UI也比较累，所以不打算做。

**Comment by allonmymind** [comment]
> 个人是 `Material Design` 忠实粉丝（乐于 使用并推广），并且再写一套UI也比较累，所以不打算做。

appstore咋搜索不到这个app了，佬

**Comment by lollipopkit** [comment]
具体看 https://github.com/lollipopkit/flutter_server_box/discussions/180

**Comment by allonmymind** [comment]
> 具体看 #180
难怪呢，已重新上车。
Segments not match:12 这个问题啥时候修复，好像是有些系统的资源信息获取不到导致的无法展开托盘，终端按钮也就不法点击连接ssh。很影响使用 0.0

**Comment by lollipopkit** [comment]
segments not match？麻烦你再开个相关的 issue 吧

**Comment by allonmymind** [comment]
> segments not match？麻烦你再开个相关的 issue 吧

已提交，麻烦佬处理
