### ISSUE TITLE
部分系统无法ssh连接，提示Segments not match: 12

### ISSUE THREAD

**Issue by allonmymind** [lollipopkit/flutter_server_box#184]
已在安卓和ios测试均报错Segments not match: 12
uname结果如下：
1.Padavan路由器:
[ZTE_E8820S_JM /home/root]# uname -a
Linux ZTE_E8820S_JM 3.4.113 https://github.com/lollipopkit/server_box_monitor/issues/1 SMP Fri Jun 30 01:56:15 CST 2023 mips GNU/Linux

2.PVE7:
root@yb:~# uname -a
Linux yb 5.15.102-1-pve https://github.com/lollipopkit/server_box_monitor/issues/1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 GNU/Linux
大概是上个月更新后出现的，显示连接成功但是报错Segments not match: 12，推测是未能获取主机资源状态无法展开显示托盘导致，参考类似issue [#176](https://github.com/lollipopkit/flutter_server_box/issues/176) 回滚到1.0.407版本，不显示资源状态但是终端按钮可以直接成功连上ssh。

**Comment by allonmymind** [comment]
类似issue#163[](https://github.com/lollipopkit/flutter_server_box/issues/163)

**Comment by lollipopkit** [comment]
执行 `uname` 输出什么？

**Comment by allonmymind** [comment]
> 执行 `uname` 输出什么？

![image](https://github.com/lollipopkit/flutter_server_box/assets/18719713/c7da9f5c-7241-4757-be44-617dd53a107c)
佬是不是看漏了，我有贴上uname结果

**Comment by lollipopkit** [comment]
执行 `sh ~/.config/serverbox/mobile_v19.sh -s`（可能v18之类的），贴上输出

**Comment by allonmymind** [comment]
> 执行 `sh ~/.config/serverbox/mobile_v19.sh -s`（可能v18之类的），贴上输出

![E3214A8A-6F57-41E4-A3FA-07ED0FD01BE1](https://github.com/lollipopkit/flutter_server_box/assets/18719713/d5752ac0-d67b-4025-98e7-ac57f16a4613)
环境是PVE7.4.3

**Comment by lollipopkit** [comment]
注意最后还有个 `-s`，而且最好用 `sh`，既然有v19就执行v19

**Comment by allonmymind** [comment]
> 注意最后还有个 `-s`，而且最好用 `sh`，既然有v19就执行v19

root@gz:~/.config/server_box# sh mobile_v19.sh -s
linux
SrvBoxSep
1697165052
SrvBoxSep
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 1032463    1603    0    0    0     0          0         0  1032463    1603    0    0    0     0       0          0
enp2s0: 72662890687 72755261    0    0    0     0          0     53846 29874278330 59853105    0    0    0     0       0          0
wlp3s0f0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vmbr0: 473897362  492135    0    0    0     0          0     33735 121966194  334566    0    0    0     0       0          0
docker0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
br-378ecbbf59b0:       0       0    0    0    0     0          0         0      746       7    0    0    0     0       0          0
br-ff1d89142e6f: 25354974  107345    0    0    0     0          0         0 135525860  112800    0    0    0     0       0          0
tap101i0: 29727016780 59333620    0    0    0     0          0         0 71525968116 60911045    0 2044    0     0       0          0
tailscale0:   21174     194    0    0    0     0          0         0    29832     154    0    0    0     0       0          0
veth577ba59: 25522937   94188    0    0    0     0          0         0 111490657   98529    0    0    0     0       0          0
veth3c5caf8:       0       0    0    0    0     0          0         0     1926      25    0    0    0     0       0          0
SrvBoxSep
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
SrvBoxSep
cpu  5995786 0 1843332 6146011 154061 0 224231 0 5490781 0
cpu0 1531224 0 446884 1564788 39151 0 6631 0 1401239 0
cpu1 1532712 0 439614 1570351 40916 0 6552 0 1399608 0
cpu2 1417532 0 494004 1453293 35299 0 196728 0 1302821 0
cpu3 1514316 0 462830 1557577 38693 0 14320 0 1387111 0
SrvBoxSep
 10:44:12 up 10:21,  3 users,  load average: 2.75, 2.57, 2.86
SrvBoxSep
Ip: Forwarding DefaultTTL InReceives InHdrErrors InAddrErrors ForwDatagrams InUnknownProtos InDiscards InDelivers OutRequests OutDiscards OutNoRoutes ReasmTimeout ReasmReqds ReasmOKs ReasmFails FragOKs FragFails FragCreates
Ip: 1 64 311129 0 0 215661 0 0 89370 267154 0 70 0 0 0 0 0 0 0
Icmp: InMsgs InErrors InCsumErrors InDestUnreachs InTimeExcds InParmProbs InSrcQuenchs InRedirects InEchos InEchoReps InTimestamps InTimestampReps InAddrMasks InAddrMaskReps OutMsgs OutErrors OutDestUnreachs OutTimeExcds OutParmProbs OutSrcQuenchs OutRedirects OutEchos OutEchoReps OutTimestamps OutTimestampReps OutAddrMasks OutAddrMaskReps
Icmp: 93 0 0 92 0 0 0 0 0 1 0 0 0 0 6878 0 6877 0 0 0 0 1 0 0 0 0 0
IcmpMsg: InType0 InType3 OutType3 OutType8
IcmpMsg: 1 92 6877 1
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts InCsumErrors
Tcp: 1 200 120000 -1 1391 10473 250 42 6 338471 291104 3359 7 557 0
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti MemErrors
Udp: 2649 6899 0 2755 0 0 0 191 0
UdpLite: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti MemErrors
UdpLite: 0 0 0 0 0 0 0 0 0
SrvBoxSep
Filesystem            Size  Used Avail Use% Mounted on
udev                  3.6G     0  3.6G   0% /dev
tmpfs                 735M  1.4M  733M   1% /run
/dev/mapper/pve-root  106G   55G   47G  55% /
tmpfs                 3.6G   40M  3.6G   2% /dev/shm
tmpfs                 5.0M     0  5.0M   0% /run/lock
/dev/sda1             469G  465G     0 100% /mnt/pve/sata
/dev/sdb2             511M  6.3M  505M   2% /boot/efi
/dev/fuse             128M   20K  128M   1% /etc/pve
overlay               106G   55G   47G  55% /var/lib/docker/overlay2/c306efb490f8967d118abc5553092b370e243a33d46fc0f0b0f5afdcad983969/merged
overlay               106G   55G   47G  55% /var/lib/docker/overlay2/a13d5e741c74325c01ff7bf8b95b6f201e3d5669f60da10331ca37c2d8d7bc14/merged
overlay               106G   55G   47G  55% /var/lib/docker/overlay2/941ed8d455e42656b42e5b4896a10cf26b6b832172f26a1885dc0f6db6434a26/merged
overlay               106G   55G   47G  55% /var/lib/docker/overlay2/d18ed7444b833559ccd13c6e4f8ced2d474b5e5fd95a3ea67a404e1ad53c8737/merged
tmpfs                 735M     0  735M   0% /run/user/0
SrvBoxSep
MemTotal:        7519428 kB
MemFree:          383572 kB
MemAvailable:     437836 kB
Buffers:           27028 kB
Cached:           226172 kB
SwapCached:       326668 kB
Active:          2840984 kB
Inactive:        3837220 kB
Active(anon):    2692576 kB
Inactive(anon):  3742336 kB
Active(file):     148408 kB
Inactive(file):    94884 kB
Unevictable:       12132 kB
Mlocked:           12016 kB
SwapTotal:       3670012 kB
SwapFree:        2029160 kB
Dirty:               308 kB
Writeback:             0 kB
AnonPages:       6162408 kB
Mapped:           166116 kB
Shmem:             23452 kB
KReclaimable:      71564 kB
Slab:             242168 kB
SReclaimable:      71564 kB
SUnreclaim:       170604 kB
KernelStack:        7084 kB
PageTables:        33956 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     7429724 kB
Committed_AS:   14596404 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       51640 kB
VmallocChunk:          0 kB
Percpu:             3344 kB
HardwareCorrupted:     0 kB
AnonHugePages:    579584 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      355364 kB
DirectMap2M:     7415808 kB
SrvBoxSep
acpitz
SrvBoxSep
26800
SrvBoxSep
gz
root@gz:~/.config/server_box#

**Comment by lollipopkit** [comment]
[试试](https://res.lolli.tech/serverbox/088abeba98d672b10d636ae14211b1cde370b405abb0fdb72999e6b7e85e383f.apk)，主要加了些log输出，截图看看

**Comment by allonmymind** [comment]
> [试试](https://res.lolli.tech/serverbox/088abeba98d672b10d636ae14211b1cde370b405abb0fdb72999e6b7e85e383f.apk)，主要加了些log输出，截图看看

![Screenshot_20231014-114424.jpg](https://github.com/lollipopkit/flutter_server_box/assets/18719713/d565c26d-eecb-4fdf-99b4-b45e1b3d8350)
还是一样😂

**Comment by allonmymind** [comment]
> [试试](https://res.lolli.tech/serverbox/088abeba98d672b10d636ae14211b1cde370b405abb0fdb72999e6b7e85e383f.apk)，主要加了些log输出，截图看看

![image](https://github.com/lollipopkit/flutter_server_box/assets/18719713/326dad91-5c92-4943-8deb-3f8a2e37fd39)![image](https://github.com/lollipopkit/flutter_server_box/assets/18719713/053a7dcf-345b-4ba9-b0c8-f24f4c3a6aeb)
怎么上传截图不显示

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/00d4b1aea78d6cf863beb18d756ac25f1e785987017362b31e1401ac1383425a.apk，这次应该没问题了

**Comment by allonmymind** [comment]
> [这次](https://res.lolli.tech/serverbox/00d4b1aea78d6cf863beb18d756ac25f1e785987017362b31e1401ac1383425a.apk)应该没问题了

666,pve 和padavan 都能显示了，不过padavan 系统上传下载流量显示有问题，之前朋友也反映过openwrt 也存在这个问题![image](https://github.com/lollipopkit/flutter_server_box/assets/18719713/7cfa6039-a9f3-4726-bb77-5fa936e08ef4)![image](https://github.com/lollipopkit/flutter_server_box/assets/18719713/95648bd4-e92e-4da2-9b54-f87f3dd47fe2)

**Comment by lollipopkit** [comment]
关于流量重新开 issue 吧（还是规范写好，虽然我也懒）

:)

**Comment by allonmymind** [comment]
> 关于流量重新开 issue 吧（还是规范写好，虽然我也懒）
> 
> :)

好的，能否把ios版也同步更新下，ios端还是有问题

**Comment by lollipopkit** [comment]
iOS 正在改桌面小部件，会尽早

**Comment by allonmymind** [comment]
> iOS 正在改桌面小部件，会尽早

这个问题已经出现一个月了，ios主力机完全无法远程使用了，能否先更新一版恢复使用

**Comment by lollipopkit** [comment]
不好意思，这几天去找工作了。

刚已提交App Store审核申请，明天应该就好。
