### ISSUE TITLE
debian 11 链接后看不到状态

### ISSUE THREAD

**Issue by josangmi** [lollipopkit/flutter_server_box#186]
**描述BUG**

Debian 11 系统出现
SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = ， port = 52994
的错误

使用的是ufw 防火墙。

443                        ALLOW IN    Anywhere
52785                      ALLOW IN    Anywhere
443 (v6)                   ALLOW IN    Anywhere (v6)
52785 (v6)                 ALLOW IN    Anywhere (v6)

需要怎么做设置？
**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by josangmi** [comment]
ufw 卸载之后 用iptables 设置了一下出现下面这个错。
Segments not match: expect null, got 1

**Comment by lollipopkit** [comment]
app 版本？在服务器上执行 `sh ~/.config/server_box/mobile_v21.sh -s` 输出什么？

**Comment by josangmi** [comment]
App Version:Version 1.0.588 (590)
服务器没有这个目录，是不是还需要安装啥东西。 centos 7 好像也没装就可以看到。 是Debian 11 需要吗？

**Comment by josangmi** [comment]
嗯，感谢，建用户的是否没弄好没有给home目录，重新配置就好了。
