### ISSUE TITLE
备份同步bug

### ISSUE THREAD

**Issue by luckyreny** [lollipopkit/flutter_server_box#187]
开启同步点备份无反应。开启icloud同步后也不能在不同设备间同步。

**Describe the bug**

**To Reproduce**

**Desired Results**

**Actual Results**

**Screenshots**

**Device**

**Additional context**

**Comment by lollipopkit** [comment]
开启iCloud同步后重启app了吗？

功能大概率是没问题，但是可以优化（例如开启选项后立即同步），会在后期更新
