### ISSUE TITLE
Windows版备份问题

### ISSUE THREAD

**Issue by id7368** [lollipopkit/flutter_server_box#188]
点击备份后调用Windows 11系统分享功能，默认只有Outlook客户端，如果使用Outlook客户端分享json的话，实际上分享的只有这个文件名，并不会作为附件添加到邮件中。
![Snipaste_2023-10-20_01-07-39](https://github.com/lollipopkit/flutter_server_box/assets/28560843/34ab29aa-c5a3-4d56-b68c-abaf8a15cf1d)
![Snipaste_2023-10-20_01-08-05](https://github.com/lollipopkit/flutter_server_box/assets/28560843/eadc6a8d-7e25-431b-b6e3-27d8d04924bc)

**Comment by NekoYyang** [comment]
自行编译的windows版本吗（）

**Comment by id7368** [comment]
> 自行编译的windows版本吗（）

首页下载的压缩包。

**Comment by NekoYyang** [comment]
我这边下是403（）

**Comment by lollipopkit** [comment]
> 我这边下是403（）

再试试？

**Comment by lollipopkit** [comment]
麻烦更新至608版本尝试是否能够备份

**Comment by id7368** [comment]
> 麻烦更新至608版本尝试是否能够备份

似乎情况更糟糕了，共享按钮都没了，请看GIF录像：

![screenshots](https://github.com/lollipopkit/flutter_server_box/assets/28560843/c3cd0f84-f265-4dd9-b456-e6f34fd79652)

**Comment by afrojewelz** [comment]
目前备份功能在windows版客户端上试过是暂时无效的. 但是软件本身太好用了 如果支持导出备份到一个文件(json或者yaml),那这大玩具简直无敌

**Comment by PaperCube** [comment]
[5888cb7](https://github.com/lollipopkit/flutter_server_box/commit/5888cb717240b1e6c8a9c22c81ce42d38b52636b)

**Comment by PaperCube** [comment]
[5888cb7](https://github.com/lollipopkit/flutter_server_box/commit/5888cb717240b1e6c8a9c22c81ce42d38b52636b)
