### ISSUE TITLE
请问安卓手机用sftp功能下载的文件在哪个文件夹里面呀？我找不到

### ISSUE THREAD

**Issue by JelmdtcSings** [lollipopkit/flutter_server_box#19]

**Comment by lollipopkit** [comment]
![Screenshot_2023-03-23-18-23-01-531_tech.lolli.toolbox.jpg](https://user-images.githubusercontent.com/10864310/227174396-e8ecf6d7-4aab-426a-a4d9-df00d28bb1a8.jpg)

如图底部，`/data/user/0/tech.lolli.toolbox/app_flutter/sftp`

**Comment by lollipopkit** [comment]
后继可能更改下载目录到常见目录，如`/storage/emulated/0/Downloads`

**Comment by lollipopkit** [comment]
Android已更改默认文件夹
