### ISSUE TITLE
有考虑过加入跳板机访问支持吗？

### ISSUE THREAD

**Issue by michaelsara** [lollipopkit/flutter_server_box#190]
通过一个跳板机，访问内网中的其他机器，避免开放多个端口带来的安全性问题

>感谢各位开发者的辛苦劳动，让我们用上了这么好的软件👍👍👍

**Comment by lollipopkit** [comment]
如果有 Android 机，麻烦[测试](https://res.lolli.tech/serverbox/ac1f6aabbf5391ec07a584aebf34a7043e861ebf27f248085f99457583f0177c.apk)

**Comment by ForeUP** [comment]
> 如果有 Android 机，麻烦[测试](https://res.lolli.tech/serverbox/ac1f6aabbf5391ec07a584aebf34a7043e861ebf27f248085f99457583f0177c.apk)

@lollipopkit 我测试了，感觉跳板机没用啊，连接的错误日志和没开跳板的一样

**Comment by lollipopkit** [comment]
这次应该没问题了，[Android](https://res.lolli.tech/serverbox/20eb1211ce1faadca31a2a22ecf9f5ccc6ada007ec48056506c92328f36fef9e.apk)

**Comment by michaelsara** [comment]
Thanks.  All yours
