### ISSUE TITLE
安卓客户端后台一会儿会断开连接

### ISSUE THREAD

**Issue by Saseboshigure** [lollipopkit/flutter_server_box#193]
![Screenshot_2023-10-22-19-43-36-31_c5f0134a4c551757558202025a96fea6](https://github.com/lollipopkit/flutter_server_box/assets/46619395/d96ed0a3-74f5-4246-be6c-b87daefea515)

**Comment by DanielEcho** [comment]
我也是这个问题，版本1.0.606
