### ISSUE TITLE
[需求] 能以进程树的形式查看进程

### ISSUE THREAD

**Issue by wc7086** [lollipopkit/flutter_server_box#194]
能切换以进程树的形式查看进程，例如
![image](https://github.com/lollipopkit/flutter_server_box/assets/74053663/8ecd6ca3-5455-43d7-b491-5e3db0ab0806)

**Comment by lollipopkit** [comment]
首先抱歉，暂时（大概率以后也）不打算做，因为这进term就能轻松获取。

进程页在我心目中的目标只是提供一个简单的UI，要达到类似htop的完成度，靠我一个人很难。
