### ISSUE TITLE
fish shell无法使用，报错Segments not match: expect 12, got 1

### ISSUE THREAD

**Issue by seawave0564** [lollipopkit/flutter_server_box#195]
bash正常，切换默认shell后会导致此问题

**Comment by lollipopkit** [comment]
我这里测试没有问题

![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/3818ccbc-02a6-4da4-8eeb-acad596b8916)

**Comment by linb666666** [comment]
我也是这个报错，但是不是切换默认shell后会导致此问题

**Comment by lollipopkit** [comment]
麻烦点击主界面右上角按钮，截图log

**Comment by lollipopkit** [comment]
如果是android，麻烦测试
https://res.lolli.tech/serverbox/ee6cf7cc404ee3e209c622dfdbd6b0b48c3e37701b467d90607056cf71d53fce

**Comment by linb666666** [comment]
> 如果是android，麻烦测试
> https://res.lolli.tech/serverbox/ee6cf7cc404ee3e209c622dfdbd6b0b48c3e37701b467d90607056cf71d53fce

是电脑的，现在他自己好了

**Comment by lollipopkit** [comment]
那先关闭了，如果更新至616或以上仍有问题，请再次开启

**Comment by horror-proton** [comment]
This message also occurs in `v1.0.707(+1)`,
log says something like
```text
[App][Warning]
Write script to xxxx by shell: Exception:
fish: Expected a string, but found a redirection
cat << 'EOF' > $HOME/.config/server_box/mobile_v34.sh
     ^
```
I ran execsnoop in that server, and saw output like
```
fish             578     576       0 /usr/bin/fish -c mkdir -p $HOME/.config/server_box\ncat << 'EOF' > $HOME/.config/server_box/mobile_v34.sh\n#!/bin/sh\n# Script for ServerBox app v1.
```
while fish does not support syntax like `<<` I guess.

It seems that this command is not executed with `sh` as expected?
https://github.com/lollipopkit/flutter_server_box/blob/b08265221f9053b847505d0efe31d39bb61ca440/lib/data/model/app/shell_func.dart#L34-L35
