### ISSUE TITLE
安卓版v1.0.606(+1)貌似无法备份

### ISSUE THREAD

**Issue by bibo138** [lollipopkit/flutter_server_box#196]
如题，安卓13，点击备份按钮没任何反应。更早之前的版本可以备份为json文件。

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/a0e4272c-4c9d-4e9b-94d1-4e9f7f980b35

有视频吗？我这边Android/iOS都没问题

**Comment by lollipopkit** [comment]
有视频吗？我这边Android/iOS都没问题

**Comment by bibo138** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/80937079/93e817cd-3a69-4986-857b-9be1419202ed

**Comment by bibo138** [comment]
好吧，重装了一下app后症状莫名消失......

**Comment by lollipopkit** [comment]
可惜了，应该在还有问题的时候看看log（主界面右上角按钮）

如果又遇到了该问题，请新开issue
