### ISSUE TITLE
安卓v1.0.606(+1) 恢复备份后，主界面和设置界面会变成空白。

### ISSUE THREAD

**Issue by yuhuike** [lollipopkit/flutter_server_box#197]
安卓13 MIUI，恢复备份后，服务器先显示连接中，之后就变成空白。设置界面打开一样。
![Screenshot_2023-10-25-10-22-24-741_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/1ceef9c9-d2a0-4740-bfdb-4e210218e979)
![Screenshot_2023-10-25-10-22-16-203_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/0f2ddb31-935a-4acf-8a5d-854f2dd7c823)

**Comment by lollipopkit** [comment]
麻烦点击右上角的按钮，并截图

**Comment by yuhuike** [comment]
![Uploading Screenshot_2023-10-26-12-52-09-901_tech.lolli.toolbox.jpg…]()

**Comment by yuhuike** [comment]
上传失败了吗
![Screenshot_2023-10-26-12-52-09-901_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/3c294647-4eec-470e-a655-8bff63672238)

**Comment by Skycnhe** [comment]
越更新Bug越多

**Comment by BlakGriffin** [comment]
我也遇到了，PC端加载失败后导入配置到安卓，现在安卓啥都看不到了

**Comment by akatsukiro** [comment]
我也碰到了类似的问题，但是我的似乎更甚一筹，啥也没有。
MIUI 14。
![Screenshot_2023-10-27-19-06-20-112_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/69096852/2c1d5537-4dd0-48b2-91a4-1995770084d7)

**Comment by yuhuike** [comment]
logs
![Screenshot_2023-10-27-22-32-14-585_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/8fe87089-8562-4c5b-9698-eca0df86879f)
![Screenshot_2023-10-27-22-32-10-800_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/2ee5fea4-2ab6-4d7f-9d4a-6dcab4012f6f)
![Screenshot_2023-10-27-22-32-05-706_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/d810fee7-6348-4222-9128-d4888a013a98)
![Screenshot_2023-10-27-22-32-01-832_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/ab039a92-86fc-4c4a-b488-53fada2500b6)
![Screenshot_2023-10-27-22-31-56-258_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/30818970/a497ea70-78da-487c-b419-03ad122f01a7)

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/814585121392894bdf0a60d825af6fce16fedc639692068d96a01437f6f5b03d.apk

如果仍未解决问题 且 愿意加群沟通：762870488
