### ISSUE TITLE
mac版打开空白，没有任何可用功能

### ISSUE THREAD

**Issue by ikmil** [lollipopkit/flutter_server_box#199]
<img width="866" alt="image" src="https://github.com/lollipopkit/flutter_server_box/assets/13192711/b0666e78-2cba-476d-8d76-4a61731f1b40">
macos 11.7

**Comment by lollipopkit** [comment]
Intel？

**Comment by Talkchan** [comment]
我是arm m1 也是空白界面

**Comment by Think-Me** [comment]
<img width="400" alt="image" src="https://github.com/lollipopkit/flutter_server_box/assets/28859254/a00fd6d1-4ec7-4613-a4b0-8390405930a3">

<img width="586" alt="image" src="https://github.com/lollipopkit/flutter_server_box/assets/28859254/83c83836-087c-4935-adc7-63c048d29743">

**Comment by ikmil** [comment]
> Intel？

yes , mac os big sur 11.7

**Comment by lollipopkit** [comment]
已在 1.0.717 中解决,如果仍存在问题请再次开启
