### ISSUE TITLE
FormatException: Invalid character (at character 10) Proc-Type: 4 ENCRYPTEDDEK-Info:

### ISSUE THREAD

**Issue by fecture** [LollipopKit/flutter_server_box#2]
创建私钥保存的时候提示这个，私钥是没有问题的，在别的ssh工具上能用。请问是什么问题导致的？

**Comment by LollipopKit** [comment]
保存密钥时会[解析密钥并解密](https://github.com/LollipopKit/flutter_server_box/blob/0fdc1b784b8d53bb705e7772026a1b789bf254d0/lib/view/page/private_key/edit.dart#L109)，看上去是dartssh2解析密钥的问题。

已经向dartssh2负责人反映了这个问题
<img width="260" alt="image" src="https://user-images.githubusercontent.com/10864310/169730896-5fc38904-6ec4-42a3-83b2-21a59b69a639.png">

想确认下，您使用的是rsa加密的密钥吗？（可以查看密钥的第一行是否为`-----BEGIN RSA PRIVATE KEY-----`）

**Comment by fecture** [comment]
第一行确实是-----BEGIN RSA PRIVATE KEY-----

**Comment by LollipopKit** [comment]
好的，会尽快支持rsa加密的密钥

**Comment by fecture** [comment]
谢谢

**Comment by LollipopKit** [comment]
> 谢谢

是android吗？麻烦[下载](https://cdn3.cust.app/uploads/ServerBox_143b_Arm64.apk)测试下，没有问题再发布更新

**Comment by fecture** [comment]
安卓亲测可以，等ios的

**Comment by LollipopKit** [comment]
ios得等明天了

**Comment by LollipopKit** [comment]
**f60b09a**
