### ISSUE TITLE
安卓，已经更新到最新版了，每次重新打开还是会提示更新版

### ISSUE THREAD

**Issue by u-Sir** [lollipopkit/flutter_server_box#202]
安卓，已经更新到最新版了，每次重新打开还是会提示更新版

**Comment by lollipopkit** [comment]
现在仍然提示吗？

**Comment by u-Sir** [comment]
> 现在仍然提示吗？

现在试了下，好像没了，不过进设置手动点击检查更新时，会提示旧版的出来 当前：1.0.603 点击后提示新版本：1.0.590🤦‍♀️

**Comment by lollipopkit** [comment]
设计如此...

但是有几个人反馈这个问题，那还是改了吧

原本的设计，当不存在新版本：
- 自动检查，非强制更新，会提示没有更新的版本
- 手动检查，被认为是强制更新，会提示最新的版本
