### ISSUE TITLE
Ability to use jump host(server)

### ISSUE THREAD

**Issue by NEK-RA** [lollipopkit/flutter_server_box#204]
Hi
Recently found out ServerBox and it looks nice, but I wondering if there's ability to specify jump host somewhere?
I mean the `-J` option of OpenSSH, like `ssh -J jump-user@jump-host target-user@target-server`

At least according to https://github.com/TerminalStudio/dartssh2/issues/74 this option is available in `dartssh2` which you are using in ServerBox

If there is already support for this feature in ServerBox - how can I use it? I just haven't found anything like that.
If there's not yet developed option to use jump hosts, can you consider this issue as a feature request?

Thanks

**Comment by lollipopkit** [comment]
Implemented
