### ISSUE TITLE
nat lxc架构面板无法弹出

### ISSUE THREAD

**Issue by dialen2** [lollipopkit/flutter_server_box#206]
ios系统16.1.2，软件版本v1. 0.622（+2），lxc架构的nat面板无法呼出只显示已连接，kvm的机器是正常的，软件版本在v1. 0.606是正常的，从v1. 0.616版本开始nat鸡的面板无法呼出

**Comment by lollipopkit** [comment]
麻烦首页右上角按钮进入，截图log

**Comment by BlakGriffin** [comment]
windows和安卓最新版一样的问题，LXC架构的nat无法加载

**Comment by lollipopkit** [comment]
已知道问题所在，合并至 #207
