### ISSUE TITLE
终端窗口能不能一直保持住啊

### ISSUE THREAD

**Issue by laiquziru** [lollipopkit/flutter_server_box#211]
每次开个新窗口，刚才的直接找不到了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by lollipopkit** [comment]
![截屏2023-11-12 15 52 26](https://github.com/lollipopkit/flutter_server_box/assets/10864310/0fa2311f-7c96-457b-ab58-b34a3245c450)

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/e5dd692e-634e-4d23-8654-d2df34286fe1)
