### ISSUE TITLE
无法连接Windows的ssh

### ISSUE THREAD

**Issue by hedan2** [lollipopkit/flutter_server_box#212]
添加完Windows服务器之后无法连接，错误信息如下:
SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = /此处是我的域名，需要隐藏/, port = /端口需要隐藏/
希望我的反馈可以得到解决，谢谢

**Comment by lollipopkit** [comment]
看报错应该是网络问题
如果排除了网络问题，服务器上安装了openssh吗？安装了的话理论上是支持的
如果排除网络问题且安装了openssh仍无法连接，可能目前的 ssh lib 只支持 Unix-like system，Windows需要更新支持
