### ISSUE TITLE
希望能改进输入命令的方式

### ISSUE THREAD

**Issue by hausen1012** [lollipopkit/flutter_server_box#213]
不是bug，但是每次输入命令时，不能实时的输入到控制台，需要在输入法点击刚刚电机的字符才能输入到控制台

**Comment by lollipopkit** [comment]
。。。看样子大概率是输入法的问题？

我这边可以提供设置项来调整行为

**Comment by lollipopkit** [comment]
尝试在设置中将”键盘类型“改为”visiblePassword“

**Comment by hausen1012** [comment]
感谢，确实解决了我的问题。但是我发现另一个问题，进入软件时能正常展示状态，但是点击shell，会一直显示 connecting starting shell。我不知道这是否和我设置默认shell为zsh有关

**Comment by hausen1012** [comment]
同时，我发现设置为 visiblePassword 时，显示为小米安全键盘，此时删除按键无效，但我设置为number时，能满足我的需求，并可以删除字符
