### ISSUE TITLE
添加容器更新按钮

### ISSUE THREAD

**Issue by xingleiwu** [lollipopkit/flutter_server_box#218]
**Describe the bug**

**To Reproduce**

**Desired Results**

**Actual Results**

**Screenshots**

**Device**

**Additional context**

请求添加docker容器更新按钮
![mmexport1700286265226](https://github.com/lollipopkit/flutter_server_box/assets/13015600/e321296d-f838-4437-b7f9-62a0a4049604)

**Comment by lollipopkit** [comment]
这个做不到。

可以做到更新镜像、删除容器，但不知道怎么启动新的容器（因为不知道docker run后面的参数。如果是compose，不知道compose配置文件的路径）
