### ISSUE TITLE
Android桌面部件无法显示推送

### ISSUE THREAD

**Issue by likeaturtle** [lollipopkit/flutter_server_box#224]
docker部署，Android桌面部件智能显示json文件中定义的本机名称和当前时间，无法显示其他推送。
![3fb3e928b1921edfb108e6ae3af4418](https://github.com/lollipopkit/server_box_monitor/assets/56377910/0b5174e2-587f-4236-a90c-dea8f256581d)

**Comment by lollipopkit** [comment]
尝试浏览器直接访问url，看看有没有数据
