### ISSUE TITLE
不能选择复制log的范围。

### ISSUE THREAD

**Issue by taozhiyuai** [lollipopkit/flutter_server_box#228]
在终端显示的logo界面里面长按文本直接弹出复制按钮，但是并不能选择复制范围。希望能够改进这个功能![Screenshot_2023-12-03-18-41-47-848_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/146583103/bc9f9bb0-d787-46e3-ae6e-bb8c10703625)

**Comment by lollipopkit** [comment]
长按，不松开，移动手指，即可移动选中区域
