### ISSUE TITLE
serverbox for windows 设置全屏后灰屏，如何关闭全屏？

### ISSUE THREAD

**Issue by ZuesTao** [lollipopkit/flutter_server_box#229]
如题：
serverbox for windows 设置里点全屏后，再次打开软件灰屏，无法进入设置关闭全屏？

**复现步骤**

期望再次进入设置关闭全屏

**实际结果**

窗口灰屏，无法进入设置关闭全屏。

**截图**

**设备**
Windows10 64位
软件版本：latest.win

**Comment by lollipopkit** [comment]
在文件夹内寻找setting.hive文件，删除然后重启app

**Comment by ZuesTao** [comment]
谢谢，已经解决
