### ISSUE TITLE
serverbox for Mac 打开后界面空白无法使用 

### ISSUE THREAD

**Issue by ZuesTao** [lollipopkit/flutter_server_box#230]
serverbox for Mac 打开后界面空白无法使用 

**描述BUG**

打开软件后，界面空白，无法使用 

**复现步骤**

希望修复空白界面

**实际结果**

界面空白，无法做任何操作

**截图**

![iShot_2023-12-06_12 10 52](https://github.com/lollipopkit/flutter_server_box/assets/73762224/f8b248b4-6ae8-4204-b610-b99d89d3a992)

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
与 #199 相同
