### ISSUE TITLE
备份和恢复-webdav不录入任何内容确定后提示异常需要优化

### ISSUE THREAD

**Issue by upbeat-backbone-bose** [lollipopkit/flutter_server_box#231]
**描述BUG**

备份恢复webdav提示异常

**复现步骤**

1.备份和恢复
2.webdav展开-设置
3.不录入任何内容，点击好确认
4.提示内容不友好

**期望结果**

一个友好的提醒内容或者不提示

**实际结果**

抛出了代码级别的null错误

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/438092/79b099b9-4e4b-4422-8450-e0e12e27874b)
![image](https://github.com/lollipopkit/flutter_server_box/assets/438092/c995abc8-fe39-4720-b006-ad4527b6a778)
![image](https://github.com/lollipopkit/flutter_server_box/assets/438092/0bf4ed8e-e4ac-4765-9aa2-ffc5b8bab315)
**设备**

系统版本:iOS17.1.2
App版本:v1.0.665（+1）

**更多信息**

**Comment by lollipopkit** [comment]
这个地方的报错确实可能有很多种，如果统一给一个友好的提示（“请检查参数”之类的），反而可能无法找到出错的具体原因，且大家都是玩服务器的人了，多多少少愿意折腾、学习
