### ISSUE TITLE
能不能加podman的管理？

### ISSUE THREAD

**Issue by Potterli20** [lollipopkit/flutter_server_box#233]
可以把docker改为容器，然后二级页面改为有docker和podman选择。

**Comment by lollipopkit** [comment]
Implemented in 50bcabbc5470d3944a2617f21ae0c30604c75cad
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/4352a1d6-db1d-421c-8f9a-26291e4faac9)
