### ISSUE TITLE
网络设备显示不完整

### ISSUE THREAD

**Issue by AniberMokie** [lollipopkit/flutter_server_box#234]
**描述BUG**

我在Unbutu服务器界面的网络栏只能看到“lo”网络设备，而服务器是通过网线联网的，网络设备名称是“enp3s0”，APP中没有显示这个网络设备，因此看不到实际的网络上传或下载速度。
我将我的树莓派也添加到APP中，发现网络栏也是显示不完整的，我树莓派是通过WiFi连网的，但网络栏中只显示了“lo”和“eth0”设备，实际有网速的应该是“wlan0”设备，网络栏却没有显示。

**复现步骤**

记得很久以前的版本是可以看到所有网络设备的，后面更新后就出现网络设备显示不完整了，卸载重新安装问题也依旧存在。

**期望结果**

希望可以自己选择显示哪些网络设备速度

**截图**

网络栏的显示截图
![Screenshot_2023-12-12-18-55-08-429_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/57789558/92f3852d-483a-46d1-984e-b4c67e79769f)
![Screenshot_2023-12-12-19-00-48-000_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/57789558/8917d90e-bfdb-4f46-b634-e2be1a00fe90)

**设备**

系统：Android12
App版本：1.0.665

**更多信息**

无

**Comment by AniberMokie** [comment]
> 你这个Ubuntu的版本是多少

服务器是Ubuntu 18.04.6 LTS
树莓派4B是Raspberry Pi OS 64位

**Comment by lollipopkit** [comment]
已修复，v1.0.677
