### ISSUE TITLE
大佬  能不能支持下ios15

### ISSUE THREAD

**Issue by lalasou** [lollipopkit/flutter_server_box#237]
希望添加ios 15 等旧版支持
谢谢😬

**Comment by lollipopkit** [comment]
在iOS15成功运行，不太明白你的意思，请详细描述

**Comment by lalasou** [comment]
> 在iOS15成功运行，不太明白你的意思，请详细描述

我是ios 14.3  不能用啊 
不让下载

**Comment by lollipopkit** [comment]
但是app要求的最低版本是12.0

**Comment by lalasou** [comment]
> 但是app要求的最低版本是12.0

大佬我错了  跳转到国区不能下 我以为系统版本不支持呢
换地区可以了


大佬能不能以后新版本  加一个ipa下载 🙏

**Comment by lollipopkit** [comment]
暂时不考虑
