### ISSUE TITLE
ipad版本备份与恢复下的icloud云端打不开

### ISSUE THREAD

**Issue by luckyreny** [lollipopkit/flutter_server_box#239]
**描述BUG**

ipad版本备份与恢复下的icloud云端打不开

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**ipad mini5

**更多信息**

**Comment by lollipopkit** [comment]
是开关打不开？请截图

**Comment by lalasou** [comment]
> 是开关打不开？请截图
我这边也是打不开  下面是日志
ps：这app真棒👍🏻 感谢大佬

![image](https://github.com/lollipopkit/flutter_server_box/assets/7440313/7dc25c4d-e59f-4df9-aa25-4c312e8ae0c8)

**Comment by lollipopkit** [comment]
如果问题仍然存在请再次开启
