### ISSUE TITLE
使用小米14Pro使用问题

### ISSUE THREAD

**Issue by lovechang1986** [lollipopkit/flutter_server_box#242]
大佬好，我使用小米14Pro手机，连接ssh之后存在两个问题，
1 输入法为小米安全输入法，即手机识别输入那块为密码输入区，不知道怎么解决呢？
2 输入一些命令之后无法使用向前删除键对命令进行删除，即按了删除不起左右。

求大佬帮看看

**Comment by strongDong** [comment]
11pro有同样的问题，应该是MIUI的适配问题

**Comment by huashu2021** [comment]
我也是  删除键不起作用

**Comment by strongDong** [comment]
> 我也是 删除键不起作用

我在设置里把 键盘类型 改为 number 后可以正常使用了，不然一直弹出安全键盘。

**Comment by kslpix** [comment]
在设置中关闭安全键盘会有帮助！

**Comment by lovechang1986** [comment]
@strongDong 感谢，测试可用，但是每次都需多一遍操作输入法的过程:joy:

**Comment by lovechang1986** [comment]
@kslpix 谢谢

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/6fcaa0dad1f39afa373498b1359993b65d4b5cf2eb9fc9fd2e6c23ce05b8fdaf.apk
试试能删除了吗

**Comment by lovechang1986** [comment]
@lollipopkit 新版本已可以删除。
