### ISSUE TITLE
windows版本添加服务器时已经填写密码，但是打开terminal还是需要单独输入密码

### ISSUE THREAD

**Issue by tcscat** [lollipopkit/flutter_server_box#246]
**描述BUG**

![image](https://github.com/lollipopkit/flutter_server_box/assets/61655339/7383c475-df55-4fc5-9975-1cdeb2e837cf)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
因为serverbox内置的ssh term存在问题，所以优先调用系统ssh（ssh命令为了安全，未提供直接明文传入密码的方式，需要手动输入）

**Comment by qian9008** [comment]
> 因为serverbox内置的ssh term存在问题，所以优先调用系统ssh（ssh命令为了安全，未提供直接明文传入密码的方式，需要手动输入）

所以如何解决，替换为putty还是不行。
