### ISSUE TITLE
Windows10 点击设置-直接灰屏

### ISSUE THREAD

**Issue by ohyoxo** [lollipopkit/flutter_server_box#247]
**描述BUG**
Windows10 点击设置-直接灰屏

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://github.com/lollipopkit/flutter_server_box/assets/126952400/827c7655-8d79-4276-8a92-2b4969f91e77)
![image](https://github.com/lollipopkit/flutter_server_box/assets/126952400/bebd2fcb-a230-42d1-b4f0-45f6a550ba06)

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
已在 703+ 版本中解决，请更新后尝试，如果仍未解决请再次开启
