### ISSUE TITLE
反馈已经建议

### ISSUE THREAD

**Issue by Aeorq** [lollipopkit/flutter_server_box#25]
在使用sftp管理文件时发现删除文件夹无效
，也希望能够加入sftp可编辑文件功能以及代码片段能够在ssh连接上是的页面选择使用，现在的代码片段也是有bug，执行后返回信息为空白

**Comment by lollipopkit** [comment]
感谢反馈，已知晓，最近忙着毕业，可能会比较慢

**Comment by Aeorq** [comment]
好的希望能实现这些东西

**Comment by Aeorq** [comment]
最新版本我貌似删除不了文件了😂

**Comment by lollipopkit** [comment]
> 最新版本我貌似删除不了文件了😂

https://stackoverflow.com/questions/40503675/how-could-i-use-rmdir-in-sftp-to-remove-remote-folders-not-empty

SFTP协议如此

**Comment by Twshuai** [comment]
能编辑文件和从手机直接上传文件就好了👍就可以抛弃网页了
