### ISSUE TITLE
openwrt系统登录以后网络流量显示

### ISSUE THREAD

**Issue by mzyyl** [lollipopkit/flutter_server_box#251]
**描述BUG**

openwrt系统登录以后在主界面显示的流量是wan➕lan口总流量，能不能设置成可以选lan口或者wan口流量显示呢

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
设计就是主界面显示所有，详情得去二级目录
