### ISSUE TITLE
希望可以改进硬盘剩余空间的展示方案

### ISSUE THREAD

**Issue by 58fly** [lollipopkit/flutter_server_box#252]
![cb9dd40a907569025253ff4fca5af3a](https://github.com/lollipopkit/flutter_server_box/assets/46588220/69e7f778-08b3-466c-a1fb-35456ad53651)
如图，13T的硬盘，到最后剩余低于1T的时候，应该自动换算为GB单位，更加精准显示剩余空间，谢谢您的软件

**Comment by lollipopkit** [comment]
已在 717 中实现
