### ISSUE TITLE
无法下载和编辑文件

### ISSUE THREAD

**Issue by lalasou** [lollipopkit/flutter_server_box#255]
会卡主   如图
![image](https://github.com/lollipopkit/flutter_server_box/assets/7440313/20f7fb59-f6cc-4fab-b335-72eebceb00f8)
![image](https://github.com/lollipopkit/flutter_server_box/assets/7440313/f5c728db-13a5-4228-9caf-1ee200530db8)

**Comment by lollipopkit** [comment]
感谢，已修复，请等待更新（1.0.723+）
