### ISSUE TITLE
设置备选链接后 都可用的情况下会连接两次

### ISSUE THREAD

**Issue by lalasou** [lollipopkit/flutter_server_box#258]
![image](https://github.com/lollipopkit/flutter_server_box/assets/7440313/4a2beefa-fb31-4c80-9006-69ed6717d6b0)
如图  
并且打开后会明显卡一下

主连接是ipv6 ddns
备连接是 内网ipv4

**Comment by lollipopkit** [comment]
这大概率是恢复云端备份，重载导致重新连接

**Comment by lalasou** [comment]
> 这大概率是恢复云端备份，重载导致重新连接

试了下确实是这个原因 
把iCloud备份关了 秒开 不卡了

如图
![image](https://github.com/lollipopkit/flutter_server_box/assets/7440313/b506c55e-a2bb-4df6-a226-81eacf9dc8e6)
这个 备份是不是靠后点 先显示数据 最后再备份

**Comment by lollipopkit** [comment]
[更好的解决方式](https://github.com/lollipopkit/flutter_server_box/commit/799a1ac5f0ecc997e3dff0be20680775e6731ab1#diff-d8b6df46dedfb95258dda6598a28d9e3c20aca02a91b88d2d90079d7b3dca77fR49)，如果服务器信息（host等）未改变，则不重连
