### ISSUE TITLE
ios最新版1.0.729（+4）bug反馈

### ISSUE THREAD

**Issue by mervinniu** [lollipopkit/flutter_server_box#261]
设备14pm.系统ios16.6.1。
1、在更新最新版的1.0.729（+4）
以后，ssh无法连接，具体表现为打开ssh连接显示灰色屏幕，无法进入。
2、1.0.729之前的版本ssh也存在一个bug，具体表现为进入ssh后，输入reboot命令，弹窗提示连接断开后，app会变成黑屏状态，必须退出后台重新打开才能使用。

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
抱歉，已在 1.0.731 中修复，请等待更新

**Comment by lollipopkit** [comment]
如果仍有问题请再次开启
