### ISSUE TITLE
安卓1.0.731(+2) 进入ssh灰屏

### ISSUE THREAD

**Issue by bxoooooo** [lollipopkit/flutter_server_box#262]
安卓1.0.731(+2) 进入ssh灰屏

**Comment by lollipopkit** [comment]
这问题应该是在730中解决了的，并且我这边没有无法复现

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/6a9b6af6536e598acc75699f768d36b83fcd816e7dd82753f9b988878efbd0b6.apk

试试这个有没有问题

**Comment by bxoooooo** [comment]
这个完美支持

**Comment by lollipopkit** [comment]
感谢反馈，已添加至参与者列表 30932304002e3e1bec808a432f9bfb07f1901d85
