### ISSUE TITLE
关于本地备份失效

### ISSUE THREAD

**Issue by bxoooooo** [lollipopkit/flutter_server_box#263]
点击备份无法调用文件    无法备份文件   三星系统

**Comment by lollipopkit** [comment]
- 可以下个版本增加一个从剪切板恢复
- 这个问题我无法解决，不是Android原生开发者，抱歉

**Comment by bxoooooo** [comment]
他这个备份估计是调取权限问题   能恢复    但是点击备份没有调取权限

**Comment by lollipopkit** [comment]
只能以剪切板为替代解决方案了（v1.0.740中已实现），想要解决根本问题，得去第三方库反馈。
我等会儿去反馈反馈。
