### ISSUE TITLE
SSH界面白屏

### ISSUE THREAD

**Issue by KatharsisKing** [lollipopkit/flutter_server_box#264]
点击SSH图标或代码执行图标
会：
![Screenshot_20240130_005145.png](https://github.com/lollipopkit/flutter_server_box/assets/58802933/c45d8f6d-a14b-466c-b14a-95698b7a2041)

- 系统 Android13
- App版本：1.0.731

**Comment by lollipopkit** [comment]
白屏后返回主界面，点击右上角，看看log

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/6a9b6af6536e598acc75699f768d36b83fcd816e7dd82753f9b988878efbd0b6.apk

试试这个有没有问题

**Comment by lollipopkit** [comment]
请升级至732以解决
感谢反馈，已添加至参与者列表 30932304002e3e1bec808a432f9bfb07f1901d85
