### ISSUE TITLE
ssh切换后台一会就会断开连接  弹窗点击ok就会卡黑屏

### ISSUE THREAD

**Issue by yuan6975** [lollipopkit/flutter_server_box#265]
**描述BUG**

**复现步骤**

登录ssh 
软件切换后台1分钟以上
返回软件ssh连接断开
弹窗显示断开
点击ok 屏幕黑屏

**期望结果**
能像电脑软件一样登录ssh后发送空包保持连接不中断

**实际结果**

**截图**

**设备**

- 系统：  Android13
- App版本： e.g. 1.0.717+3

**更多信息**

**Comment by lollipopkit** [comment]
请更新至最新，该问题已在731中解决

**Comment by lollipopkit** [comment]
已在 740 中解决，如果仍存在问题，请再次开启
