### ISSUE TITLE
iCloud同步依旧无法开启

### ISSUE THREAD

**Issue by GHA193** [lollipopkit/flutter_server_box#267]
**描述BUG**

尝试在APP内开启iCloud同步，点不开。日志显示文件不存在。
关联的已关闭的issue：#239

**复现步骤**

我尝试过退出app，去iCloud中重新打开对ServerBox的云同步，然后打开ServerBox，在备份设置中开启iCloud备份，依旧报错。

**期望结果**

iCloud备份应该正常开启

**实际结果**

iCloud备份无法开启

**截图**

![A9324D7F-A770-4BBA-A6D5-0D9A388A83C9_4_5005_c](https://github.com/lollipopkit/flutter_server_box/assets/24401268/cbe57c78-d997-4965-9391-adcb126ac468)

**设备**

iOS 17.3

**更多信息**

**Comment by lollipopkit** [comment]
请更新至740后再次测试

**Comment by GHA193** [comment]
问题已解决，多谢

**Comment by letsgo245** [comment]
How the fuck do you do this I been trying for 3 months
