### ISSUE TITLE
详情页磁盘使用情况标准文字不正确

### ISSUE THREAD

**Issue by upbeat-backbone-bose** [lollipopkit/flutter_server_box#268]
**描述BUG**

磁盘应该是“可用”而不是“已用”，数字与文本不对应

**复现步骤**

**期望结果**

文字显示描述与所取得的数字逻辑概念保持一致，显示为“可用”

**实际结果**

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/438092/70012204-c102-4f32-86ab-4ad01fa8f6ec)

**设备**

iPhone 13 pro max

**更多信息**

**Comment by lollipopkit** [comment]
已在740中修复
