### ISSUE TITLE
Docker 容器監控錯誤

### ISSUE THREAD

**Issue by Nebulosa-Cat** [lollipopkit/flutter_server_box#270]
**描述BUG**

我目前是透過 docker compose 啟動 docker 容器
裡面包含有 4 個 images
然而 APP 中只顯示了 3 個
然而透過 SSH 指令與其他 APP 顯示則都是正常的 4 個
指令:
```
docker ps
```
結果呈現 4 組 container id

**复现步骤**
打開 Docker 監控頁面
直接顯示錯誤統計 (只顯示了 3 個正在運作的容器)

打開

**期望结果**

呈現所有容器 (4 個)

**实际结果**

只呈現 3 個

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/30948446/04be39fa-6848-4ff7-b5b0-de0e7e5603e9)
![image](https://github.com/lollipopkit/flutter_server_box/assets/30948446/1713d36d-7294-4c75-9287-d30dbff89751)

**设备**

iphone 12 mini
ios 17.3
監控的機器是樹梅派 4b 4g arm64

**更多信息**

**Comment by lollipopkit** [comment]
已在740中修复，请更新后再次测试

**Comment by Nebulosa-Cat** [comment]
> 已在740中修复，请更新后再次测试

感謝，已經正常
