### ISSUE TITLE
最新版ios 打开直接灰屏

### ISSUE THREAD

**Issue by HappyQuQu** [lollipopkit/flutter_server_box#271]
**描述BUG**

打开app直接灰屏

**复现步骤**

**期望结果**

**实际结果**

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/4098823/5f79562a-5844-4b38-91f4-9f974171ce99)

![image](https://github.com/lollipopkit/flutter_server_box/assets/4098823/76873962-a682-4848-a50a-07232f3fab7a)
**设备**

ios17.3
1.0.783（+2）

**更多信息**

**Comment by lollipopkit** [comment]
更新740后还存在该问题吗？

**Comment by Nebulosa-Cat** [comment]
> 更新740后还存在该问题吗？

iPad 17.3 安裝最新版本 ServerBox
發現只要勾上「全屏模式」就會灰屏
如圖：
![image](https://github.com/lollipopkit/flutter_server_box/assets/30948446/48992a51-b6a7-48d5-9880-4e5fb4861859)

**Comment by lollipopkit** [comment]
> > 更新740后还存在该问题吗？
> 
> iPad 17.3 安裝最新版本 ServerBox
> 發現只要勾上「全屏模式」就會灰屏
> 如圖：
> ![image](https://github.com/lollipopkit/flutter_server_box/assets/30948446/48992a51-b6a7-48d5-9880-4e5fb4861859)

感谢，提供了关键信息。春节之后再解决

**Comment by HappyQuQu** [comment]
最新版本还是复现

**Comment by HappyQuQu** [comment]
以前配置添加过跳转服务器,后来功能取消了,但是配置还在,不知道是不是引起白屏的原因,
删除所有节点,重新添加就好了
