### ISSUE TITLE
增加执行监控脚本前的延迟

### ISSUE THREAD

**Issue by swift-lee** [lollipopkit/flutter_server_box#275]
**描述BUG**

因为 ssh 有自定义的登录消息（sssd），导致监控脚本的写入和执行被判断为失败，但实际上是成功的

**复现步骤**

按步骤正确添加服务器

**期望结果**

正常使用所有功能

**实际结果**

大多数时间无法使用首页（服务器）中的所有功能，报错 Exception: sftp worker event: SftpStatusError: No such file(code 2)。少数时间或者多次手动刷新后可以刷出来。ssh 页可以正常连接进入 ssh 终端。

**截图**

![Screenshot_20240208-041255.jpg](https://github.com/lollipopkit/flutter_server_box/assets/57428138/5e4092cb-1472-467c-bc5d-4dfb873714cd)

![Screenshot_20240208-041803.jpg](https://github.com/lollipopkit/flutter_server_box/assets/57428138/92c4429c-8cdb-471e-8619-73312a55b950)

![Screenshot_20240208-041809.jpg](https://github.com/lollipopkit/flutter_server_box/assets/57428138/e11409ef-1065-403d-994f-60c94cd604f8)

**设备**

Android 11/氢OS 11，App 1.0.740 (740)

**更多信息**

我猜是 ssh 的消息还没完成输出就执行了监控命令导致的，如果能做到输出完毕后才执行监控脚本，比如 ssh 连接后延迟 1s 进行脚本的写入和执行，问题可能得到解决

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/ServerBox-763.apk

请尝试此版本

**Comment by swift-lee** [comment]
> https://res.lolli.tech/serverbox/ServerBox-763.apk
> 
> 请尝试此版本

问题解决，感谢修复
