### ISSUE TITLE
docker 版本不显示

### ISSUE THREAD

**Issue by L-Super** [lollipopkit/flutter_server_box#276]
**描述BUG**

新版本布局更改后，docker面板不显示docker版本信息

**期望结果**

显示docker版本

**实际结果**

docker版本未知

**截图**

**设备**

- 系统：Android14
- App版本： v1.0.740

**更多信息**

**Comment by lollipopkit** [comment]
已在版本764+中解决，如更新后仍存在问题，请再次开启issue
