### ISSUE TITLE
请指定bash安装监控脚本

### ISSUE THREAD

**Issue by Tridays** [lollipopkit/flutter_server_box#278]
**描述BUG**

请指定bash安装监控脚本
比如/bin/bash

**
1.当服务器的默认shell是fish，zsh或者是其他的时候，监控脚本是安装失败的：因为语法有区别。
2.另外建议日志Logs可以选择复制。
3.建议参考termux项目，他们的命令窗口做非常不错，全屏，简洁，这样更适合远程代码。对比图如下

**期望结果**
期待此越来越好！！！

**实际结果**
满意

**截图**
![Screenshot_2024-02-10-04-12-06-699_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/127336245/36470d2d-70be-4cfb-8075-08e86d1e5112)
![Screenshot_2024-02-10-04-26-17-971_com termux](https://github.com/lollipopkit/flutter_server_box/assets/127336245/80ca2a57-fbd4-4d4d-a49f-f2415dee5300)

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
已在版本764+中解决，如更新后仍存在问题，请再次开启issue
