### ISSUE TITLE
能否在设置中加入监控视图关闭的按钮

### ISSUE THREAD

**Issue by CDWEN0526** [lollipopkit/flutter_server_box#283]
大佬能不能在设置中加入关闭监控视图功能，不去获取服务器的监控数据，因为云服务器都会有异地ip登录的报警功能，监控视图一获取监控数据，阿里云就会将所有服务器的异地ip登录的报警信息发送过来。
软件非常非常好用，nice！！

**Comment by lollipopkit** [comment]
编辑服务器信息，最下面，有个自动连接，或许可以满足你的需求
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/9084164b-d8a0-4ae5-8e84-de8e83ca5f4e)
