### ISSUE TITLE
CPU显示不对

### ISSUE THREAD

**Issue by Peter-90** [lollipopkit/flutter_server_box#290]
![IMG_1148](https://github.com/lollipopkit/flutter_server_box/assets/22003137/e7c52571-41bc-4f1b-b75e-9f8291f94bda)
pve和下面的两个虚拟机的CPU显示总是一样，其实在PVE的后台看是不一样的

APP版本：v1.0.773(+3)
IOS版本：17.0.3

**Comment by lollipopkit** [comment]
大概是计算方式、频率不同

- 方式：pve _可能_ 是基于kvm统计的，serverbox是基于Linux系统内核统计的
- 频率：计算使用率与时间有关，pve _可能_ 频率为5s，serverbox可能3s，CPU在5s和3s内的平均使用率当然不同

**Comment by Peter-90** [comment]
> 大概是计算方式、频率不同
> 
> * 方式：pve _可能_ 是基于kvm统计的，serverbox是基于Linux系统内核统计的
> * 频率：计算使用率与时间有关，pve _可能_ 频率为5s，serverbox可能3s，CPU在5s和3s内的平均使用率当然不同

我记得之前的某个版本是对的，更新以后就不对了，这个导致其实看到的cpu都是pve的数据，看不到各虚拟机的数据

**Comment by lollipopkit** [comment]
可是CPU显示的实现一直没有修改过。

有没有可能是给每个虚拟机的CPU核数改变了？或者改变了CPU类型？

**Comment by Peter-90** [comment]
> 可是CPU显示的实现一直没有修改过。
> 
> 有没有可能是给每个虚拟机的CPU核数改变了？或者改变了CPU类型？

这我们有调整过，我几个有个版本显示是对的，问题不大，就是看起来有点尴尬

**Comment by lollipopkit** [comment]
那不好意思，暂不处理
