### ISSUE TITLE
群晖连接失败

### ISSUE THREAD

**Issue by LevenYi** [lollipopkit/flutter_server_box#292]
**描述BUG**

rt
软件版本：1.0.780
群晖版本：7.11-42962
报错如下：
      Segments not match: expect 16, got 1, raw:

Could not chdir to home directory /var/services/homes/Leven_Yi: No such file or directory
sh: /var/services/homes/Leven_Yi/.config/server_box/mobile_v40.sh: No such file or directory

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by RainSunMe** [comment]
https://kb.synology.cn/zh-cn/DSM/tutorial/ssh_could_not_chdir_to_home_directory @LevenYi

**Comment by LevenYi** [comment]
> https://kb.synology.cn/zh-cn/DSM/tutorial/ssh_could_not_chdir_to_home_directory @LevenYi

已解决，启用群晖家目录即可
