### ISSUE TITLE
1.0.773 更新1.78 更新点击无效

### ISSUE THREAD

**Issue by bxoooooo** [lollipopkit/flutter_server_box#293]
点击更新按钮无效

分否增加github更新 不需要在应用内更新

**Comment by lollipopkit** [comment]
检查是否授予了安装权限。需等待下载完成，大概三十秒。

大部分用户都是国人，GitHub release仅打算大版本更新发布

**Comment by lollipopkit** [comment]
是不是无法开启通知权限？如果是，是那个版本有问题，那个问题在最新版本已解决

**Comment by bxoooooo** [comment]
能不能给个下载地址   很难受   这个也不能备份,服务器太多又不敢删除重新安装

**Comment by bxoooooo** [comment]
点击更新  我发现数据在走  下载的数据  但是就是不加载进度条  也不弹出安装的app

**Comment by bxoooooo** [comment]
找到办法了  我用另外手机更新最新版本  再提取app

**Comment by lollipopkit** [comment]
https://res.lolli.tech/serverbox/ServerBox-787.apk
