### ISSUE TITLE
app打开生物认证无限验证

### ISSUE THREAD

**Issue by sakalakagg** [lollipopkit/flutter_server_box#294]
**描述BUG**
ios设置内打开生物认证，重新进入app的话会无限弹出识别

**复现步骤**

**Comment by sakalakagg** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/37735553/0265c659-06aa-42c6-a524-f77fdf6c72b7)

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/d13b7099-4de8-49b0-8bc4-4ee02cbf2c8c

无法复现，只能尽力

**Comment by qhq** [comment]
同样的问题，以前版本好的，开的生物认证，好像从上一个更新开始，就无限刷脸，只能关掉了。

**Comment by qhq** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/3319385/71cad9f0-e14d-4877-87bb-c09556b3db29

**Comment by lollipopkit** [comment]
尝试修复，麻烦更新822试试

**Comment by qhq** [comment]
更新了，问题依旧

**Comment by lollipopkit** [comment]
已在1.0.831中解决，如果仍存在问题，请再次开启
