### ISSUE TITLE
Connect button not visible for long server names

### ISSUE THREAD

**Issue by dani7959** [lollipopkit/flutter_server_box#298]
Connect button is not visible (cannot connect) when server name is long.
![Screenshot 2024-03-06 at 20 25 54](https://github.com/lollipopkit/flutter_server_box/assets/35736735/caa4544e-d741-4c7f-8215-75786ccdd617)

iPhone 15 Pro
Display Zoom > Larger Text
Text Size > 2/7

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/08c5da4d-7826-4e1c-b992-2db43660f102)

Fixed
