### ISSUE TITLE
error after connection

### ISSUE THREAD

**Issue by dani7959** [lollipopkit/flutter_server_box#299]
Ubuntu Server 18.04.6.
When connecting server:
- Connecting...
- Connected
- Loading...
- Error (see error)

Notes:
Terminal SSH connection works OK
Server reports system load / mem usage / swap usage via shell OK

![Screenshot 2024-03-06 at 20 46 24](https://github.com/lollipopkit/flutter_server_box/assets/35736735/0365f922-b795-4dfc-b62b-9503bf24e977)

Ios 17.4

**Comment by lollipopkit** [comment]
Can you exec `sh ~/.config/server_box/mobile_v40.sh` in terminal? 
Does it exists? 
Executable?

**Comment by dani7959** [comment]
Sorry for the late response. There was no access to the .config folder.
Solved by giving write access with chmod.

Maybe show a message "Check write permissions for ~/.config/ folder"

Thanks!

**Comment by lollipopkit** [comment]
Now, the install script will check `.config` perm first, thanks for your feedback.
