### ISSUE TITLE
今天更新过后用不了密钥登录

### ISSUE THREAD

**Issue by fecture** [LollipopKit/flutter_server_box#3]
编辑中打开公钥认证开关保存再编辑仍然是关闭状态，导致页面一直是Loading。ios版

**Comment by fecture** [comment]
抱歉，是端口转发出了问题，外网访问ok

**Comment by LollipopKit** [comment]
> 编辑中打开公钥认证开关保存再编辑仍然是关闭状态，导致页面一直是Loading。ios版

“仍是关闭状态”是更新出的bug

服务器信息编辑界面，是否使用公钥的开关显示出了问题，[这里](https://github.com/LollipopKit/flutter_server_box/blob/4148aac31b9e139b382918e1ecdd01713061624f/lib/view/page/server/edit.dart#L258)判断有问题，会在随后修复
