### ISSUE TITLE
服务器页面数据不显示

### ISSUE THREAD

**Issue by Mr-ZhangL** [lollipopkit/flutter_server_box#30]
ssh通过密码连接，ssh能进去，但是主页面的服务器状态不显示，CentOS6系统![image](https://user-images.githubusercontent.com/120122134/236661759-6575fadb-196c-444b-9241-dbdf7a9840e8.png)![image](https://user-images.githubusercontent.com/120122134/236661776-c629fd9b-9115-4f7c-966a-559c73411d3f.png)

**Comment by jaychoubaby** [comment]
同，刚添加的时候服务器可以连上，后面就连不上了，三台服务器只有一台正常连接![image](https://user-images.githubusercontent.com/26641387/236661965-285386b4-2217-4535-be79-f27caa9f35db.png)

**Comment by lollipopkit** [comment]
麻烦点击“点击查看”，截图看看

**Comment by Mr-ZhangL** [comment]
> 麻烦点击“点击查看”，截图看看

![image](https://user-images.githubusercontent.com/120122134/236685428-adf0474a-9039-4614-8765-232813228419.png)![image](https://user-images.githubusercontent.com/120122134/236685440-0e17006f-9303-4f80-bbbb-7e9b2c8dab1d.png)

**Comment by lollipopkit** [comment]
“点击查看”按钮，如下图的位置
![IMG_20230507_230734.jpg](https://user-images.githubusercontent.com/10864310/236685762-a0f58a43-3d11-44d3-9c64-9146ce9e3977.jpg)

**Comment by lollipopkit** [comment]
“点击查看”按钮，如下图的位置
![IMG_20230507_230734.jpg](https://user-images.githubusercontent.com/10864310/236685762-a0f58a43-3d11-44d3-9c64-9146ce9e3977.jpg)

**Comment by Mr-ZhangL** [comment]
> “点击查看”按钮，如下图的位置
> ![IMG_20230507_230734.jpg](https://user-images.githubusercontent.com/10864310/236685762-a0f58a43-3d11-44d3-9c64-9146ce9e3977.jpg)
> 
> 

刚才发的截图就是“点击查看”的界面。还有一张是log，应该是日志。

**Comment by lollipopkit** [comment]
。。。应该是没有点到“点击查看”按钮，点到了会弹出类似对话框
![Screenshot_2023-05-07-23-18-50-455_tech lolli toolbox](https://user-images.githubusercontent.com/10864310/236686514-1671e396-9539-498c-8f2d-798143cb7b26.jpg)

**Comment by Mr-ZhangL** [comment]
> 。。。应该是没有点到“点击查看”按钮，点到了会弹出类似对话框
> 
> ![Screenshot_2023-05-07-23-18-50-455_tech lolli toolbox](https://user-images.githubusercontent.com/10864310/236686514-1671e396-9539-498c-8f2d-798143cb7b26.jpg)
> 
> 

![image](https://user-images.githubusercontent.com/120122134/236686694-64296334-6574-4136-b60d-3cef377f3c2d.png)

**Comment by Mr-ZhangL** [comment]
报错提示和日志上的报错是一样的啊

**Comment by lollipopkit** [comment]
可能不一样，所以需要确认下，感谢

**Comment by Mr-ZhangL** [comment]
> 可能不一样，所以需要确认下，感谢

那这是啥情况？是我这边操作不对？还是Bug？

**Comment by lollipopkit** [comment]
bug、不兼容（CentOS6）都有可能，需要后继帮忙测试，请问有安卓机吗？

**Comment by Mr-ZhangL** [comment]
> bug、不兼容（CentOS6）都有可能，需要后继帮忙测试，请问有安卓机吗？

可以帮忙测试的。不过我这边是iPhone，没有安卓机。

**Comment by Mr-ZhangL** [comment]
TF版的测试链接有吗

**Comment by lollipopkit** [comment]
iOS每个版本都需要苹果商店审核（一次至少1天），所以不方便测试，我自己找台CentOS6试试吧

**Comment by Mr-ZhangL** [comment]
> iOS每个版本都需要苹果商店审核（一次至少1天），所以不方便测试，我自己找台CentOS6试试吧

![image](https://user-images.githubusercontent.com/120122134/236687934-6e719570-64ed-423b-8bf7-36493cff1216.png)
这是详细的系统版本及内核

**Comment by Mr-ZhangL** [comment]
还有一个bug反馈下，iOS端的终端主题切换失效（所有主题都不能用）
![image](https://user-images.githubusercontent.com/120122134/236689454-cd9e98bb-c344-4ef8-9fcd-28adc90435b1.jpeg)

**Comment by lollipopkit** [comment]
麻烦检查服务器：
1. 是否存在 `$HOME/.config/server_box/mobile_app.sh`
2. 能否执行上述文件（`sh $HOME/.config/server_box/mobile_app.sh`）
3. 如果能执行，麻烦贴出输出

**Comment by Mr-ZhangL** [comment]
> 麻烦检查服务器：
> 
> 1. 是否存在 `$HOME/.config/server_box/mobile_app.sh`
> 
> 2. 能否执行上述文件（`sh $HOME/.config/server_box/mobile_app.sh`）
> 
> 3. 如果能执行，麻烦贴出输出


根目录下没有对应的文件夹和文件
![image](https://user-images.githubusercontent.com/120122134/236771231-28ed862b-a010-462b-997b-dd3ea9928976.png)
![image](https://user-images.githubusercontent.com/120122134/236771281-952d148a-0f1c-4a6f-a455-1510d5ca6de3.png)
![image](https://user-images.githubusercontent.com/120122134/236771320-b8f75265-971f-4443-8358-63856c2a7be3.png)

**Comment by Mr-ZhangL** [comment]
还是报错
![image](https://user-images.githubusercontent.com/120122134/236996235-cd2525d3-e015-4ff6-bdc5-29340d1cf684.png)

**Comment by Mr-ZhangL** [comment]
再反馈一个bug。SFTP的定位路径页面无法取消
![image](https://user-images.githubusercontent.com/120122134/236997276-15e804e6-730b-45d3-b393-43d947172ca6.png)

**Comment by Mr-ZhangL** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/120122134/8cb5d630-6a9f-466e-a742-e669edb01bec)
![image](https://github.com/lollipopkit/flutter_server_box/assets/120122134/e5dd3e87-eaaa-4927-80fd-2d37ed02f20c)

最新版（293）还是报错🥲

**Comment by lollipopkit** [comment]
293只是修复了sftp取消按钮，麻烦截图下右上角logs

**Comment by Mr-ZhangL** [comment]
> 293只是修复了sftp取消按钮，麻烦截图下右上角logs

![image](https://github.com/lollipopkit/flutter_server_box/assets/120122134/fe84c587-8517-4158-b1ba-dbf612f31ab7)

**Comment by Mr-ZhangL** [comment]
1、连接问题解决了，sftp取消问题也解决了。
2、但是终端主题问题还没解决（换完主题无效）。
3、提个建议：希望sftp增加上传功能

**Comment by lollipopkit** [comment]
上传功能请在 #33 中讨论
