### ISSUE TITLE
总是提示这个报错 SSHAuthAbortError(Connection closed before authentication)

### ISSUE THREAD

**Issue by Peter-90** [lollipopkit/flutter_server_box#302]
总是提示这个报错，删除重新添加也不行，SSHAuthAbortError(Connection closed before authentication)，之前一直好好的，突然就出现了这个问题

**Comment by lollipopkit** [comment]
网络问题，检查
- 代理配置
- 防火墙
- fail2ban
- ...

**Comment by Peter-90** [comment]
> 网络问题，检查
> 
> * 代理配置
> * 防火墙
> * fail2ban
> * ...

好的
