### ISSUE TITLE
查看日志bug 安卓14

### ISSUE THREAD

**Issue by bxoooooo** [lollipopkit/flutter_server_box#309]
查看某些日志
一行过长会出现不显示的问题
比如这样直接被截断  不会换行显示
Mar 14 23:03:35 .16890323 systemd[1]: docker.service: Main process exit>
Mar 14 23:03:35ud.168323 systemd[1]: docker.service: Failed with resul>

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/f848f2e2-a67b-4baa-8fcc-0e877529d627)

。。。这不是本app的问题
