### ISSUE TITLE
IOS16 下 搜狗收入法 输入命令会丢失前两个字符

### ISSUE THREAD

**Issue by EmonLieu** [lollipopkit/flutter_server_box#31]
IOS16 下 搜狗收入法 输入命令会丢失前两个字符 ，同时建议一下服务器状态增加一下CPU温度显示

**Comment by lollipopkit** [comment]
- 目前是支持显示CPU温度的，不过为了兼容性，可能部分系统上不支持，后继可能会优化
- 输入法部分处理目前对于我来说确实有些困难，暂时搁置，不好意思

**Comment by EmonLieu** [comment]
> come method will lose the first two characters of the input

目前支持显示温度的系统有哪些呢？

**Comment by EmonLieu** [comment]
这边看了一下代码似乎是 在转换温度格式的时候 CmdType 里面没有 树莓派的  /sys/class/thermal/thermal_zone0/type 的类型枚举cpu-thermal 所以树莓派的系统不显示温度？ 这个是有什么考量吗？

**Comment by lollipopkit** [comment]
为了尽可能兼容，选择Linux通用的获取温度方式

执行 `cat /sys/class/thermal/thermal_zone*/type` 就可以看到是否支持、支持哪些

**Comment by lollipopkit** [comment]
我这边测试了 `1.0.407` 没有问题，如果仍然有问题，请再次开启
