### ISSUE TITLE
参数错误的server是否无法修改

### ISSUE THREAD

**Issue by downerxl** [lollipopkit/flutter_server_box#310]
**描述BUG**
添加参数错误的server无法进行修改。
如IP地址错误、密码错误时找不到能够修改server参数的地方，点击server卡片后报错“SSHErr<SSHErrType.connect>: alterUrl no @”。

**复现步骤**
无

**期望结果**
无

**实际结果**
无

**截图**
无

**设备**
macos 14.4

**更多信息**
无

**Comment by lollipopkit** [comment]
长按服务器可以编辑

可以改成出错的话，单击进入编辑
