### ISSUE TITLE
希望能自定义获取温度的命令

### ISSUE THREAD

**Issue by Seifon** [lollipopkit/flutter_server_box#313]
因为系统有差异，取温度的命令不一样

比如我的设备是：

grep Tsensor /proc/msp/pm_cpu | awk '{print $4}'

**Comment by lollipopkit** [comment]
已添加至TODO

**Comment by Seifon** [comment]
![Uploading IMG_6698.jpeg…]()

感谢作者采纳建议，现在自定义还有点小问题，就是经常会显示一串很长的错误，一会正常，一会异常。通过ssh执行很多次都没问题额，换了free -h也会经常显示错误，说明跟命令无关额

**Comment by lollipopkit** [comment]
忘记回复了，应该是没有这个问题了吗？
