### ISSUE TITLE
复制文本方式建议优化

### ISSUE THREAD

**Issue by kali-urs** [lollipopkit/flutter_server_box#315]
文本复制不好操作，能优化成这种方式吗？就是带精确选择的。
![Uploading Screenshot_2024-03-20-12-17-25-788_org.mozilla.firefox_beta.jpg…]()

**Comment by kali-urs** [comment]
![Uploading Screenshot_2024-03-20-12-17-25-788_org.mozilla.firefox_beta.jpg…]()

**Comment by lollipopkit** [comment]
重复 https://github.com/lollipopkit/flutter_server_box/issues/256
