### ISSUE TITLE
有些要二次输密码能做到吗，就是弹出输密码要取消要弹出来

### ISSUE THREAD

**Issue by gdopera** [lollipopkit/flutter_server_box#316]
**描述BUG**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
不好意思，没明白什么意思

**Comment by gdopera** [comment]
还是不行，现在会弹出来了，但没有取消再弹发自我的iPhone 12在 2024年5月7日，15:54，lollipopkit ***@***.***> 写道：﻿
Closed #316 as not planned.
