### ISSUE TITLE
pve证书问题

### ISSUE THREAD

**Issue by doyoman** [lollipopkit/flutter_server_box#317]
**描述BUG**

使用最新版pve管理功能，因为pve默认要https访问，而大部分人都不会将其部署到公网并且部署证书，所以访问时会有https证书的问题，web可以点击高级避开这个问题，但是serverbox管理pve时会报错。

![image](https://github.com/lollipopkit/flutter_server_box/assets/63859866/0685696c-2df3-42ec-b6d1-725e8c7a0ab3)

**复现步骤**
添加pve管理，例如https://192.168.2.20:8006

打开即报错

**期望结果**
希望serverbox能跳过这个证书不信任

**Comment by lollipopkit** [comment]
如果是Android，麻烦测试

https://res.lolli.tech/serverbox/ServerBox-824.apk

**Comment by doyoman** [comment]
> 如果是Android，麻烦测试
> 
> https://res.lolli.tech/serverbox/ServerBox-824.apk

不好意思，我是ios系统

**Comment by lollipopkit** [comment]
麻烦更新831，新增PVE跳过证书验证设置

**Comment by s7lx** [comment]
目前就在831，还是有同样的问题

**Comment by lollipopkit** [comment]
设置了“跳过证书”吗？

**Comment by s7lx** [comment]
当然设置了。那个开关反复开关各种，都测试了

**Comment by alterem** [comment]
同样的问题

**Comment by s7lx** [comment]
iOS 1.0.852  Tested and passed

**Comment by lollipopkit** [comment]
> iOS 1.0.852 Tested and passed

Thanks
