### ISSUE TITLE
服务器列表报错

### ISSUE THREAD

**Issue by tetumeme** [lollipopkit/flutter_server_box#318]
**描述BUG**

在1.0.807版本无此错误，升级1.0.817后出现的，
服务器列表下的快捷无法显示，服务器名称后面显示查看错误，点击后显示
Seperate segments failed, raw:

**复现步骤**

**期望结果**

**实际结果**

**截图**

![Screenshot_2024-03-24-22-28-20-35_c5f0134a4c551757558202025a96fea6](https://github.com/lollipopkit/flutter_server_box/assets/45534868/72953713-b2da-43a9-9457-d7462a0ec593)

**设备**

**更多信息**

**Comment by tetumeme** [comment]
![Screenshot_2024-03-24-22-45-24-86_c5f0134a4c551757558202025a96fea6](https://github.com/lollipopkit/flutter_server_box/assets/45534868/f6ba9d9a-cb9f-4994-81d3-930809b8139d)
这段日志不知道能不能定位问题

**Comment by lollipopkit** [comment]
先确定当前无法连接，然后备份，再降级 [807](https://cdn.lolli.tech/serverbox/ServerBox-807.apk) 后，能正常连接吗

**Comment by tetumeme** [comment]
807的包没有了，能给个包我试试吗？

> 先确定当前无法连接，然后备份，再降级[807](https://cdn.lolli.tech/serverbox/ServerBox-807.apk)后，能正常连接吗？

**Comment by lollipopkit** [comment]
刚刚的回复里，看到颜色不一样的“807”了吗，点一下

**Comment by tetumeme** [comment]
> 刚刚的回复里，看到颜色不一样的“807”了吗，点一下

看到了，刚试了下，现在用807还是这个问题。重新输入服务器资料也是这样显示。

**Comment by lollipopkit** [comment]
那就不是更新app导致的，检查网络，例如是不是被ban了

**Comment by tetumeme** [comment]
> 那就不是更新app导致的，检查网络，例如是不是被ban了

确实是我这的问题，更改密码就可以用了。
