### ISSUE TITLE
生物验证反复出现

### ISSUE THREAD

**Issue by MoMingRose** [lollipopkit/flutter_server_box#320]
**描述BUG**
下拉通知栏再返回，生物验证就会弹出来

还有一次一直弹（不记得具体操作了什么，只知道那个时候我在调主题相关的设置）

**复现步骤**
1. 软件不用后台，前台就行
2. 下拉通知栏
3. 上拉关掉通知栏，返回软件
4. 生物验证出现

以上步骤100%复现

**设备**
系统:  Android14
App版本: 1.0.827

**Comment by lollipopkit** [comment]
更新829试试

**Comment by lollipopkit** [comment]
如果仍有问题请再次开启
