### ISSUE TITLE
Android 小组件不显示 ID，MIUI13、Android 12

### ISSUE THREAD

**Issue by zj1123581321** [lollipopkit/flutter_server_box#323]
**描述BUG**
https://github.com/lollipopkit/flutter_server_box/issues/115
看到有人也反馈过这个问题，但是没有看到后续进展，issue 就被关闭了。

**复现步骤**
添加小组件后不展示 id，自然也无法配置

**截图**
![59fa89535752faca24f5b2628585faa](https://github.com/lollipopkit/flutter_server_box/assets/33171229/8567a34c-ff5e-4a67-a19b-0303a9207a0f)

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
之前未能复现所以关闭了，最近忙抱歉，会尽快修复

**Comment by zj1123581321** [comment]
> 我连找到这个小部件都没，同miui，在桌面上点击添加小部件 推荐中的全部应用 里面，没有找到serverbox相关的应用，不清楚是什么情况

按这个流程走

添加小部件-点击搜索-底部的【安卓小部件】
![8434429c7b4936921e529bc65af4e79](https://github.com/lollipopkit/flutter_server_box/assets/33171229/fa2f2906-6d52-4978-a969-0165301b9ef3)

**Comment by hurriedlu** [comment]
> > 我连找到这个小部件都没，同miui，在桌面上点击添加小部件 推荐中的全部应用 里面，没有找到serverbox相关的应用，不清楚是什么情况
> 
> 按这个流程走
> 
> 添加小部件-点击搜索-底部的【安卓小部件】 ![8434429c7b4936921e529bc65af4e79](https://private-user-images.githubusercontent.com/33171229/321228390-fa2f2906-6d52-4978-a969-0165301b9ef3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTA1MjcsIm5iZiI6MTcxMjc1MDIyNywicGF0aCI6Ii8zMzE3MTIyOS8zMjEyMjgzOTAtZmEyZjI5MDYtNmQ1Mi00OTc4LWE5NjktMDE2NTMwMWI5ZWYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDExNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzdiMTdhMzRmZDA1MzY5NGU5YTUwNWQxZTQzOTRlY2JmNThjNTM5OTU1NmE2N2RiYTUzNjczMTAxNjViMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oX5AQNSCTVhTS0vXaRiWO-e05ozMCy3I1J0R5dpIYhw)

找到了 谢谢
