### ISSUE TITLE
windows11闪退，没人有这样的情况吗？有些天了，我等更新，结果一直没更新

### ISSUE THREAD

**Issue by abcmiao** [lollipopkit/flutter_server_box#325]
下载windows最新版，解压到全是英文目录，双击打开闪退。
放到D盘，C盘都不行，之前的版本可以，但是忘记是哪个版本了。

环境：

64 位操作系统, 基于 x64 的处理器

版本	Windows 11 专业版
版本	23H2
操作系统版本	22631.3374
体验	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by lollipopkit** [comment]
不好意思，最近忙而且手头没win机器。

已发布[844](https://cdn.lolli.tech/serverbox/ServerBox-844.win.zip)，如果仍然闪退，可能需要删除数据库文件

**Comment by abcmiao** [comment]
> 不好意思，最近忙而且手头没win机器。
> 
> 已发布[844](https://cdn.lolli.tech/serverbox/ServerBox-844.win.zip)，如果仍然闪退，可能需要删除数据库文件

好的，我去测试下。不过大佬你可以装个windows虚拟机，这样还能顺带测试下arm版的windows，一举两得

**Comment by abcmiao** [comment]
> 不好意思，最近忙而且手头没win机器。
> 
> 已发布[844](https://cdn.lolli.tech/serverbox/ServerBox-844.win.zip)，如果仍然闪退，可能需要删除数据库文件

不过还有个问题，这个下载链接提示拒绝，没有权限
<img width="841" alt="9069" src="https://github.com/lollipopkit/flutter_server_box/assets/13944985/82a04345-2b63-4f52-bbe1-4d212a7efcef">

**Comment by lollipopkit** [comment]
我的问题，现在再试呢

**Comment by abcmiao** [comment]
> 我的问题，现在再试呢

大佬你确定一下，是不是文件给错了，一眼望不到头的svg文件，都找不到serverbox.exe的启动文件

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/releases
