### ISSUE TITLE
vps使用更新后死机，启动跑代码卡死。

### ISSUE THREAD

**Issue by yzg790787394** [lollipopkit/flutter_server_box#326]
**描述BUG**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
"更新"就是调用系统的更新，大概率不会引起卡死

如果无法通过快照恢复，可以尝试在vps控制台，挂载iso然后通过vnc重装系统可能可以保留数据恢复系统

将在后继版本中警告用户注意备份
