### ISSUE TITLE
希望让iOS版本能够横屏显示

### ISSUE THREAD

**Issue by pgs666** [lollipopkit/flutter_server_box#327]
有一台闲置的iOS设备，希望能放在一边横屏显示我的服务器信息，但是我发现iOS版本的serverbox不支持横屏，而安卓版本是支持的，如果能在iOS版本上也做一下对应的支持就好了，感谢作者大大（

**Comment by lollipopkit** [comment]
已在852中实现，麻烦升级测试（需在设置中开启全屏模式）

**Comment by pgs666** [comment]
> 已在852中实现，麻烦升级测试（需在设置中开启全屏模式）

感谢🥰
