### ISSUE TITLE
最新的serverbox升级选项有问题

### ISSUE THREAD

**Issue by pctoolsx** [lollipopkit/flutter_server_box#330]
最新的iOS v1.0.843(+4)版，点击server update的时候一直显示3秒（秒数不倒数，一直显示3秒，也点击不了）
![IMG_9225](https://github.com/lollipopkit/flutter_server_box/assets/44749267/a7837828-ce12-4f2c-bd76-ff1b7d8706ba)

**Comment by lollipopkit** [comment]
已在852中解决，如果升级后仍存在问题，请再次开启
