### ISSUE TITLE
直到当前最新版本下，设备主机信息依然识别失败，提示为mobile_v44.sh存在错误

### ISSUE THREAD

**Issue by XHLiang0** [lollipopkit/flutter_server_box#336]
设备主机信息识别错误，提示为mobile_v44.sh存在错误

**期望结果**
![S40416-09053372_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/90927576/b32133ec-fb9a-453f-ba37-cc1061bb788f)

**截图**
![S40416-09025155_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/90927576/5115401c-ecba-4074-94ff-e7e0286be32d)

**设备详细信息**
- 系统： Flyme 10.24.4.7Daily / Android 14
- App版本： 1.0.859
- 主机系统为ArchLinux
- 
![S40416-09085105_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/90927576/2bf715ba-2805-4dba-a77d-a6a68e7859f1)

**Comment by lollipopkit** [comment]
麻烦粘贴下 `hostname` 和 `cat /etc/hostname` 的输出，如果包含隐私请使用*替代

**Comment by lollipopkit** [comment]
> > 麻烦粘贴下 `hostname` 和 `cat /etc/hostname` 的输出，如果包含隐私请使用*替代
> 
> ```
> cat: can't open '/etc/hostname': No such file or directory
> ```
> 
> @lollipopkit 再借楼反馈一下问题，
> 
> 1. openwrt不能sftp查看文件
> 2. ios不能长亮屏幕，过一会就息屏了
> 3. 首页状态卡片，能不能同时显示上下行速度和上下行流量，读写速度和读写量，手动切来切去很难受

- wrt可能没有安装sftp，所以没法用
- TODO
- 流量视图可以在设置切换

**Comment by lollipopkit** [comment]
之前就是因为屏幕放不下，所以才点击切换。

archlinux可以`hostname`获取主机名吗？
