### ISSUE TITLE
SFTP功能改进建议

### ISSUE THREAD

**Issue by LucaLin233** [lollipopkit/flutter_server_box#338]
目前最新版本的SFTP点击编辑，完成上传的模式非常的舒服，但是在编辑过程中还是有一些不顺手的地方，例如有超过屏幕的内容时，无法拖动屏幕快速定位到需要编辑的内容，只能靠移动光标来到达指定位置
改进建议：
1、使得sftp的文件编辑界面可拖动，编辑更加方便，有助于快速定位到需要编辑的部分
2、加入换行机制，当超过屏幕使换行
个人认为2会更好一点，开发者可酌情考虑

**Comment by lollipopkit** [comment]
已在868中新增换行，如有问题，请再次开启
