### ISSUE TITLE
页面灰屏

### ISSUE THREAD

**Issue by FHU-yezi** [lollipopkit/flutter_server_box#348]
**描述BUG**

SSH、服务器概览、设置等页面灰屏

**复现步骤**

1. 设置 - 主题色种子 - 打开「跟随系统」
2. 重启 App
3. 连接任意服务器 / 打开 「关于 & 反馈」页面，灰屏

**期望结果**

页面正常显示。

**实际结果**

页面灰屏，点击无响应。

**截图**

![](https://github.com/lollipopkit/flutter_server_box/assets/50828953/034a3250-a65b-4d9a-9976-ad5358362724)

![](https://github.com/lollipopkit/flutter_server_box/assets/50828953/e5684ba5-bcef-44df-9c30-d1e57d8460df)

**设备**

Android，荣耀 50，Android 12

Serverbox v1.0.873 Build at 2024-04-23 with Flutter 3.19.5

**Comment by FHU-yezi** [comment]
Problem disappered after reinstalling App. Closing.

**Comment by lollipopkit** [comment]
已在1.0.877中解决，如果仍存在问题，请再次开启issue
