### ISSUE TITLE
feature: 支持 google authenticator

### ISSUE THREAD

**Issue by IllTamer** [lollipopkit/flutter_server_box#349]
RT google authenticator 是一个 google 发行的 2FA 身份验证器，相较于正常ssh链接流程，它在客户端与服务器建立ssh链接时不仅需要输入账号密码，还需要输入验证码才可通过ssh验证流程（先后顺序由sshd_config中的配置决定，如下图）

![224009f11pi7p1pvnonpky.jpg](https://github.com/lollipopkit/flutter_server_box/assets/78360471/5619171b-d633-4f8a-9292-137b8c9107ea)

我对该功能的预期是：在检测到ssh验证过程中需要额外的用户输入时，弹出提示框并要求用户输入。

不知道您对这个提议是否有兴趣

**Comment by IllTamer** [comment]
> https://cdn.lolli.tech/serverbox/ServerBox-878.apk
> 
> 我配置了sshd后，但是连ssh cli都无法连接，所以如果有Android，麻烦测试

我很高兴您听取了大家的建议,增设了跳板服务器, 密匙认证等连接选项. 但本提案所期望的功能其实仅仅是简单的将预先配置登录密码/密匙 改为 进行连接时主动弹出输入框要求用户键入密码, 以达到兼容 google authenticator 的效果 -- 这也是大部分其他 android 终端所采取的方案.

再次感谢您的付出 💐

**Comment by lollipopkit** [comment]
ssh 2fa只是UI上看起来与输入ssh密码类似，但其实认证是通过的keyboard-interactive

经过群友测试，已经完成
![943b11a3cc295cc148beb164140178f7](https://github.com/lollipopkit/flutter_server_box/assets/10864310/9e0e38fb-e05e-4182-9813-9bf6defba257)
