### ISSUE TITLE
传感器列表中部分数字的单位错误

### ISSUE THREAD

**Issue by ZRY233** [lollipopkit/flutter_server_box#350]
**描述BUG**

风扇转速，电压单位全部显示成摄氏度。

**复现步骤**

**期望结果**

显示正确单位

**实际结果**

显示错误单位

**截图**

![Screenshot_2024-04-30-16-43-40-562_tech lolli toolbox-edit](https://github.com/lollipopkit/flutter_server_box/assets/76866747/70df7776-3e0f-4e82-a5b8-0eb45f98c3e9)

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
可否提供 `sensors -j` 的输出?

**Comment by ZRY233** [comment]
ZRYraspi  name1  ~  sensors -j
{
   "pwmfan-isa-0000":{
      "Adapter": "ISA adapter",
      "fan1":{
         "fan1_input": 3240.000
      }
   },
   "cpu_thermal-virtual-0":{
      "Adapter": "Virtual device",
      "temp1":{
         "temp1_input": 54.550
      }
   },
   "w1_slave_temp-virtual-0":{
      "Adapter": "Virtual device",
      "temp1":{
         "temp1_input": 26.187
      }
   },
   "w1_slave_temp-virtual-0":{
      "Adapter": "Virtual device",
      "temp1":{
         "temp1_input": 40.062
      }
   },
   "rpi_volt-isa-0000":{
      "Adapter": "ISA adapter",
      "in0":{
         "in0_lcrit_alarm": 0.000
      }
   },
   "rp1_adc-isa-0000":{
      "Adapter": "ISA adapter",
      "in1":{
         "in1_input": 1.479
      },
      "in2":{
         "in2_input": 2.544
      },
      "in3":{
         "in3_input": 1.395
      },
      "in4":{
         "in4_input": 1.404
      },
      "temp1":{
         "temp1_input": 51.985
      }
   }
}
  ZRYraspi  name1  ~ 

lollipopkit ***@***.***> 于 2024年5月7日周二 上午9:47写道：

**Comment by lollipopkit** [comment]
![1e42b9233551894e5105e0751fbc6158](https://github.com/lollipopkit/flutter_server_box/assets/10864310/50326357-5e2d-404d-baaf-3212222bb071)

已修改，使用 `sensors` 命令的原输出

https://cdn.lolli.tech/serverbox/ServerBox-893.apk

麻烦测试，感谢

**Comment by ZRY233** [comment]
正常了！

Issues-translate-bot ***@***.***> 于 2024年5月10日周五 下午8:19写道：
