### ISSUE TITLE
三星 DEX 模式下指纹认证绕过BUG

### ISSUE THREAD

**Issue by o2asdv** [lollipopkit/flutter_server_box#351]
**描述BUG**
在三星DEX模式下使用软件，即使设置了指纹认证，且三星手机上已经弹出指纹认证验证的界面了，但DEX下的APP，可以不经过认证就可以登录已经配置的服务器并进行操作。同时，在这种状态下，我也可以通过DEX下的界面关闭指纹认证。
我只有三星手机，怀疑其他有类似DEX功能的手机应该都有类似的BUG。

**设备**
- 系统： 三星 S23 Android 14 
- App版本： 1.0.877

**Comment by PaperCube** [comment]
我们已经留意到此问题，将在一段时间后开始着手修复。在此之前，请暂时先使用其他方式（例如手机自带的应用锁功能）替代锁定

**Comment by lollipopkit** [comment]
使用测试版 https://cdn.lolli.tech/serverbox/pkg/ServerBox_1026_amd64.apk，或者等待发布新版
