### ISSUE TITLE
服务器页右下角添加按钮偏出屏幕

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#359]
**描述BUG**

服务器页右下角添加按钮偏出屏幕且无法点击

**复现步骤**

**截图**

![Screenshot_20240521_144014_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/159670257/7be92329-3de3-4919-9f80-2de57858df5f)

**设备**

**更多信息**

唯独服务器页右下角按钮偏出屏幕并且无法点击到，其他三个并列的页面均正常

**Comment by lollipopkit** [comment]
已在之前的版本修复，但未发布新版。不好意思。将尽快发布新版。

**Comment by Jasonzhu1207** [comment]
> 已在之前的版本修复，但未发布新版。不好意思。将尽快发布新版。

ok，辛苦了🥰
