### ISSUE TITLE
Windows版ssh页面右上角缺少最小化、缩放、关闭按钮

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#361]
**描述BUG**
Windows版ssh页面右上角缺少最小化、缩放、关闭按钮

**复现步骤**
1.打开Windows客户端
2.点到ssh选项卡
3.右上角缺少最小化、缩放、关闭按钮
**截图**
![image](https://github.com/lollipopkit/flutter_server_box/assets/159670257/f3486352-95d3-4d3b-a94d-f304bad7af67)

**设备**
系统：Windows11专业版 23H2 22631.3593
App版本：1.0.871

**更多信息**
Windows版 ssh页面右上角缺少最小化、缩放、关闭按钮，其他三个页面正常

**Comment by PaperCube** [comment]
Fix will shipped with next release
