### ISSUE TITLE
代码片段选择栏片段过多会超出屏幕

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#363]
**描述BUG**
执行代码片段选择栏片段过多会超出屏幕

**复现步骤**
1.打开APP
2.服务器页面直接点击代码片段执行按钮
3.或ssh页连接后点击代码片段按钮

**期望结果**
希望在图中框出的区域做一个滚动列表上下滑动，另外希望可以加一个设置项，选择在点击好以后立即执行还是预览二次确认再执行
![Screenshot_20240523_080501.jpg](https://github.com/lollipopkit/flutter_server_box/assets/159670257/38ca3d6e-5301-460b-97ec-a5776ccbad56)

**截图**
![Screenshot_20240523_080433_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/159670257/4544ef18-fd9d-4bb0-b204-b56ff414b374)

![mmexport1716422813378.png](https://github.com/lollipopkit/flutter_server_box/assets/159670257/8811ff4b-e1b8-47a9-8c2f-7880c9eced32)

**设备**
系统： win11 & Android 12
App版本： 1.0.871 & 1.0.892

**更多信息**
这个问题同时存在于Windows和安卓端，同时Windows端还存在列表排列过于紧密没有空隙的问题
另外希望可以加一个设置项，选择在点击好以后立即执行还是预览二次确认再执行
辛苦啦🥰🥰🥰

**Comment by lollipopkit** [comment]
已在 930 版本中修复
