### ISSUE TITLE
Windows版本备份无法备份到本地

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#364]
**描述BUG**
Windows版本备份不能备份到本地只能分享

**复现步骤**
打开应用
点开侧栏
点击以文件形式备份

**期望结果**
弹出来一个文件选择框选择保存位置而不是Windows自带分享

**截图**
![image](https://github.com/lollipopkit/flutter_server_box/assets/159670257/538d8469-96d3-494e-9c03-fe474d4aae43)

**设备**
系统：win11
App版本： 1.0.871

**更多信息**
搞成正常的保存到本地多好，win原生分享真不见的几个人用过，难用不方便

**Comment by PaperCube** [comment]
[5888cb7](https://github.com/lollipopkit/flutter_server_box/commit/5888cb717240b1e6c8a9c22c81ce42d38b52636b) 
点击备份将会自动在资源管理器中定位备份文件
