### ISSUE TITLE
Windows版ssh光标问题

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#365]
**描述BUG**
win版本ssh页光标永远只能放在第一个ssh窗口里，永远不能在新增ssh窗口中输入

**复现步骤**
1.打开应用
2.点击ssh选项卡
3.连接第一台小鸡
4.新增一个连接连上第二台小鸡

**期望结果**
鼠标点击切换到某个输入框时光标就该直接跟过来

**设备**
系统：win11
App版本： 1.0.871

**更多信息**
接复现步骤4：此时第二个输入框无论如何都无法输入任何东西，键盘操作全操作到第一个输入框中，想连另一台机子大概率要关掉所有输入框，开一个新的才能正常使用；小概率要直接关掉应用重开才能恢复

**Comment by lollipopkit** [comment]
9304a0377b8827cd7eb21cb2b0875995f62eaec3
