### ISSUE TITLE
安卓版ssh文本拉伸问题

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#368]
**描述BUG**
代码向上滚动的同时收起键盘几乎100%触发文本拉伸

**复现步骤**
如何复现：
1. 打开 APP
2. 点击ssh
3. 连接任意服务器
4. 执行任意命令（最好是持续输出大量文本的命令方便复现）
5.文本向上持续滚动时收起键盘

**截图**
![Screenshot_20240526_094543_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/159670257/11714667-ce3d-4eda-a1be-8b25483f1069)

**设备**
系统： Android12
App版本： 1.0.911

**Comment by lollipopkit** [comment]
正常现象
