### ISSUE TITLE
mac上排序无法拖动

### ISSUE THREAD

**Issue by 77160860** [lollipopkit/flutter_server_box#372]
进入ssh终端后无法返回  只能关闭！

**Comment by 77160860** [comment]
<img width="426" alt="iShot_2024-06-03_19 38 09" src="https://github.com/lollipopkit/flutter_server_box/assets/9974648/3b5d6fc3-dc54-457d-8758-db312e92549c">

**Comment by PaperCube** [comment]
排序已修复 (ee88923)。

> ssh终端后无法返回 只能关闭

这个可否详细描述一下？

**Comment by 77160860** [comment]
Mac进入ssh后没有返回按键  只能关闭

**Comment by lollipopkit** [comment]
为了最大化窗口，所以没有返回按钮，你可以：
- 输入 `exit` 并回车
- 鼠标在程序窗口左侧边缘开始向右拖动，类似 iOS 侧滑返回
