### ISSUE TITLE
docker 容器显示 已停止

### ISSUE THREAD

**Issue by jaydong2016** [lollipopkit/flutter_server_box#374]
昨晚更新最新版本后就出现截图中情况
![Screenshot_2024-06-05-18-39-31-134_tech.lolli.toolbox-edit.jpg](https://github.com/lollipopkit/flutter_server_box/assets/23270314/c7436384-a8a4-46be-aaa1-52884cee9349)

**Comment by lollipopkit** [comment]
https://cdn.lolli.tech/serverbox/ServerBox_934_arm64.apk

**Comment by lollipopkit** [comment]
已在 949 修复
