### ISSUE TITLE
仅显示为一行功能 bug

### ISSUE THREAD

**Issue by viyv** [lollipopkit/flutter_server_box#377]
**描述BUG**

编辑虚拟按键里打开仅显示为一行(可滚动)按钮，在 ssh 界面，虚拟按键不会自适应，导致显示不全

**复现步骤**

打开虚拟按键界面里，仅显示为一行功能

**期望结果**

显示全，而不是字体一半
**实际结果**

实际只显示字的上半身，下半身不见
**截图**

![1439AB5C-A2C8-4D10-8359-FFE443D493BD](https://github.com/lollipopkit/flutter_server_box/assets/84920939/3c6cedaf-c2b6-4a61-b475-a8c288769ccc)

**设备**

iOS  15.0.1
iPhone X

**更多信息**

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/f44a73ed-54ca-49a9-a6b2-2fb4cb417846)
无法复现，大概率是 Flutter 框架的问题。

设置-辅助功能-(最底部)分应用设置，为 ServerBox 关闭字体加粗
