### ISSUE TITLE
依赖gms?

### ISSUE THREAD

**Issue by Hua159** [lollipopkit/flutter_server_box#379]
我在下载安装其项目的安卓apk安装包时打开出现崩溃，并有以下错误日志![Screenshot_2024-06-09-20-42-34-802_com.fankes.apperrorstracking.jpg](https://github.com/lollipopkit/flutter_server_box/assets/103234291/094e45c3-816a-4169-b926-7787c248c2d6)

通过日志内容分析似乎是需要其gms运行才能打开，我在打开后成功运行
我使用的设备ram为8g，运行gms会占据额外ram，我不希望在使用一个软件时特意去打开
那么请问是否可以移除此依赖

**Comment by lollipopkit** [comment]
v967 已发布，移除了 GMS

如果仍存在问题，请开启 issue
