### ISSUE TITLE
使用跳板机连接时无法连接服务器

### ISSUE THREAD

**Issue by Wuming-HUST** [lollipopkit/flutter_server_box#392]
**描述BUG**

跳板机可以连接上，但是无法连接上内网的服务器
显示 
```
认证失败，请检查密码/密钥/主机/用户等是否错误

SSHAuthAbortError(Connection closed before authentication)
```

但电脑上直接执行
```
ssh user@192.168.1.23 -J 跳板机
```
可以连接上服务器

```
ssh 跳板机
```
也能直接连接到跳板机

无论是密码连接还是密钥都是一样的错误。

**期望结果**

希望能通过跳板机连接内网的服务器。

**实际结果**

实际无法连接，显示查看错误

**截图**

![Screenshot_20240613_135948](https://github.com/lollipopkit/flutter_server_box/assets/37974000/26aa4de5-f94b-464f-a1f2-290554c640fd)

**设备**

系统：Android14
App 版本 1.0.930

**更多信息**

**Comment by Winspain** [comment]
same question

**Comment by Winspain** [comment]
同样的问题，但补充一个可能导致问题的现象：
清除跳板机，使用全局梯子进行链接，错误提示为：sshAuthFailError(all authentication methods failed)
或许问题是出现在sftp上面？

**Comment by hausen1012** [comment]
一样的错误

**Comment by dlzhongp** [comment]
这个问题解决了吗，我也遇到了这个问题

**Comment by Winspain** [comment]
> 这个问题解决了吗，我也遇到了这个问题

解决了，本质原因出在Ubuntu 24.04的系统，/etc/ssh/sshd_config.d目录下多了几个文件，删掉就好。你试试。

**Comment by hausen1012** [comment]
> /etc/ssh/sshd_config.d

 我这边是时好时坏，不是说完全连不上

**Comment by hausen1012** [comment]
> > 这个问题解决了吗，我也遇到了这个问题
> 
> 解决了，本质原因出在Ubuntu 24.04的系统，/etc/ssh/sshd_config.d目录下多了几个文件，删掉就好。你试试。

我刚看了，我是22.04，这目录下没文件

**Comment by dlzhongp** [comment]
我的服务器是CentOS7，我想知道你删掉的是什么文件，我好看看我这里有没有这样的问题

**Comment by dlzhongp** [comment]
经过我测试发现，主是问题来自于路由转发，我在局域网中跳板服务器是好用的，从外网经过路由转发使用跳板机就会报错。但是其他软件类似的功能确没有问题，这让我不知该怎么处理了。还是很喜欢ServerBox在手机上使用的方便体验，希望能解决这个问题或是给我指个解决的方向。

**Comment by universeXiong** [comment]
我也遇到这个情况了，使用阿里云有公网IP的服务器跳转内部服务器会失败，服务器是centos7

**Comment by Canary233** [comment]
同样的问题，手机，跳板机，目标服务器都在同个局域网内依然复现

**Comment by Wuming-HUST** [comment]
更新 v1.0.1070后正常了

**Comment by sccuijian** [comment]
不好使依旧，版本1.0.1206。。。。。

**Comment by Pandaaaa906** [comment]
v1104正常 最新的1206有问题

**Comment by UlyssesZh** [comment]
Same error on v1256. Why was the issue closed?

**Comment by UlyssesZh** [comment]
I wanted to do a git bisect to find the first broken commit since v1104, but I failed to set up the development environment for the old versions. I do not have time to investigate further. Let's hope the developer will look at this.
