### ISSUE TITLE
批量删除服务器页无法滑动

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#393]
**描述BUG**
批量删除服务器页无法滑动列表

**复现步骤**
1.打开设置
2.点击批量删除服务器

**设备**
系统： Android12 $ win11
App版本：1.0.971

**更多信息**
win 安卓都存在同样问题

**Comment by lollipopkit** [comment]
请等待更新，如果新版仍存在问题，请开启新的 issue
