### ISSUE TITLE
Windows 11 下显示异常

### ISSUE THREAD

**Issue by QJAG1024** [lollipopkit/flutter_server_box#396]
**描述BUG**
如题
将窗口调整至横向像素数大于纵向像素数时窗体出现错误位移，使得顶栏与标题栏按钮当场暴毙

**复现步骤**
1. 打开任意界面
2. 拖拽窗口使得其成为一个横置的矩形
3. 注意到错误发生

**期望结果**
在横屏窗口下能合理看见应用顶栏与标题栏按钮并与之交互

**实际结果**
两者消失

**截图**
![image](https://github.com/lollipopkit/flutter_server_box/assets/123146382/f26e6cfb-51a9-4984-95da-0dc94045223d)
上图为纵向窗口时表现
![image](https://github.com/lollipopkit/flutter_server_box/assets/123146382/1a32b17c-3250-4a19-abdc-ff3d176e0950)
上图为横向窗口时表现

**设备**
联想拯救者y7000p2020（i7-10750H/GTX1650ti），16GB RAM
Windows 11 专业版 24H2，Insider Preview  26120.670

**更多信息**
N/A

**Comment by QJAG1024** [comment]
P.S.
图中底栏反馈出另一个问题
CJK字体覆盖不完全

**Comment by QJAG1024** [comment]
> P.S. 图中底栏反馈出另一个问题 CJK字体覆盖不完全

已提交新issues #397

**Comment by PaperCube** [comment]
收到，最近比较忙，过段时间修复
