### ISSUE TITLE
Windows 11 下中文字体显示问题

### ISSUE THREAD

**Issue by QJAG1024** [lollipopkit/flutter_server_box#397]
**描述BUG**
如题
windows11下中文字体部分错乱

**复现步骤**

如何复现：
        1. 打开任意界面
        2. 查看底栏
        3. 点击”服务器“项或”代码片段“项
        4. 看到错误
打开设置-SSH-主题亦能观察到明显问题

**期望结果**
以同一字体渲染所有中文字形

**实际结果**
系统字体与应用字体相冲突导致字体不统一

**截图**

![image](https://github.com/lollipopkit/flutter_server_box/assets/123146382/0b96b3d4-e9b0-4c33-a968-fd1dc46714c5)
![image](https://github.com/lollipopkit/flutter_server_box/assets/123146382/47160028-e3eb-4822-b522-d5d108c91d98)
![image](https://github.com/lollipopkit/flutter_server_box/assets/123146382/1b14dc67-1ddb-4f36-94a1-e8a9e44a7f89)
如图，中文字体不统一

**设备**
联想拯救者y7000p2020（i7-10750H/GTX1650ti），16GB RAM
Windows 11 专业版 24H2，Insider Preview 26120.670

**更多信息**
N/A

**Comment by lollipopkit** [comment]
已修复, 请等待下次更新
