### ISSUE TITLE
窗口无法固定 每次启动都是最小窗口

### ISSUE THREAD

**Issue by 77160860** [lollipopkit/flutter_server_box#398]
对于有多台vps显示不方便   希望能设置固定窗口大小 谢谢！
![iShot_2024-06-17_09 51 56](https://github.com/lollipopkit/flutter_server_box/assets/9974648/dd8946a5-8239-408b-aa90-7ba6bf98e1a2)

**Comment by lollipopkit** [comment]
请等待下次更新，若仍存在问题，请开启新的 issue
