### ISSUE TITLE
请求设备支持

### ISSUE THREAD

**Issue by Tao173** [LollipopKit/flutter_server_box#4]
很棒的开源项目，有两个需求，提一下：支持无密码登陆，我的局域网设备都是没有密码的，这个软件不支持无密码登陆选项。请求设备支持openwrt，软路由现在跑个docker跑一些小服务也还可以，希望增加支持。

**Comment by LollipopKit** [comment]
好的，会尽快支持

**Comment by LollipopKit** [comment]
我这里没有无密码登录的设备，麻烦[下载](cdn3.cust.app/uploads/ServerBox_151_Arm64.apk)测试反馈下

**Comment by Tao173** [comment]
![Screenshot_2022-05-29-19-02-46-628_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170864793-2e2b60ca-dc0a-4908-aaa2-b810e35bc4f5.png)
![Screenshot_2022-05-29-19-03-02-225_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170864796-aa005c71-d4ac-4928-beb0-c60481def5a4.png)
登录可以，下面那个是乌班图没问题，上面那个是op，乌班图有密码，op没有密码，op的日志发了一部分，截图不全，，，需要吗？需要想办法全发给你。

**Comment by LollipopKit** [comment]
看样子登录是没有问题，但是解析CPU温度出错了
<img width="701" alt="image" src="https://user-images.githubusercontent.com/10864310/170864946-6c0a1622-a8ca-497c-9a0c-4d4e2490536a.png">
我去检查下

**Comment by Tao173** [comment]
OK，我把op的系统日志也给你。

![image](https://user-images.githubusercontent.com/64321391/170865008-da3c03d0-5041-4169-a57f-2fb31d049c7f.png)
![Screenshot_2022-05-29-19-12-37-859_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170865116-64abfc11-b908-4579-8a4f-b7535359053f.png)
需要测试的话随时call

**Comment by LollipopKit** [comment]
还是刚才的链接，试试，然后麻烦发下app log

**Comment by Tao173** [comment]
主界面已经可以访问到设备信息了，但是测试docker和sftp无法访问。日志如下：
![Screenshot_2022-05-29-19-54-23-111_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170867744-5e402899-b952-47fc-9a61-0492f238273c.png)
![Screenshot_2022-05-29-20-08-36-839_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170867760-8aa97d2f-c873-4a56-8eee-0b7d8b4fbcc9.png)

**Comment by LollipopKit** [comment]
openwrt的sftp无法使用，大概率是因为其使用的dropbear，不支持sftp，可以尝试安装openssh以开启sftp。

docker界面显示的什么错误？还是说什么都没显示？

**Comment by Tao173** [comment]
> openwrt的sftp无法使用，大概率是因为其使用的dropbear，不支持sftp，可以尝试安装openssh以开启sftp。
> 
> docker界面显示的什么错误？还是说什么都没显示？

docker界面什么都没有显示

**Comment by Tao173** [comment]
我试了一下，我的op里面包含
CONFIG_PACKAGE_openssh-sftp-client=y
CONFIG_PACKAGE_openssh-sftp-server=y
然后使用Xshell登录之后点击xftp软件是可以连接到openwrt的。
docker界面和stp一样没有内容空屏白色。
![20220530102026](https://user-images.githubusercontent.com/64321391/170905829-5a45723d-ed6a-443b-91af-3ac828ae84ed.gif)

**Comment by LollipopKit** [comment]
重启app，等待首页状态加载完成后，进入docker界面，然后截图app log（要全部的）看看，麻烦了

**Comment by Tao173** [comment]
试了一下stp和docker都是转圈，进不去。
没有红色日志，还是截图给你。
![Screenshot_2022-05-30-10-54-20-721_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170909261-c0ee9814-bb2d-409a-8a65-19448e0167af.png)
![Screenshot_2022-05-30-10-56-14-092_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170909274-584642df-ddc0-4177-9cc7-319ce3b55c03.png)
![Screenshot_2022-05-30-10-56-20-089_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170909284-c495c0b1-3455-4fd6-8ecd-9934b12f934e.png)

**Comment by LollipopKit** [comment]
能用命令`sftp -P {port} {user}@{host}`使用sftp吗？

**Comment by Tao173** [comment]
命令行用sftp没用过，我试了一下可以链接上（上半部分不是：
![image](https://user-images.githubusercontent.com/64321391/170938015-62b9bd54-7074-4eb3-ab88-936f690fd843.png)

**Comment by LollipopKit** [comment]
sftp这个问题有点困难。

docker页面增加了更多调试输出，麻烦再次下载刚刚的链接，等待首页状态加载完成后进入docker界面
- 观察docker界面有无变化
- 截图app log

**Comment by Tao173** [comment]
你好，我重新试了，没有红色日志
![Screenshot_2022-05-30-18-04-52-505_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170969891-8c65fd2b-71a7-4180-9cdf-8e03e7080c5f.png)
![Screenshot_2022-05-30-18-05-03-585_tech lolli toolbox](https://user-images.githubusercontent.com/64321391/170969915-3fb24f59-b826-43ef-ae10-77967a16fa77.png)

**Comment by LollipopKit** [comment]
可以发下运行`docker version`的结果吗？

**Comment by LollipopKit** [comment]
苹果需要经过App Store的审核，通常会晚一天才能上架。然后手机又会延迟一两天才能收到App Store的更新推送。。。。

SFTP的问题有点困难，找不到原因，能力有限，抱歉了

04db5a82b9424ab7801f0c17d62336afc542289d
