### ISSUE TITLE
建议docker添加功能

### ISSUE THREAD

**Issue by ymxkiss** [lollipopkit/flutter_server_box#40]
建议docker管理中，添加容器运行状态显示，并添加重启功能。

**Comment by lollipopkit** [comment]
![Screenshot_2023-05-16-14-02-13-918_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/10864310/2ed86f0a-f112-4690-a5d3-424884195446)

运行状态一直有，重启将会添加
