### ISSUE TITLE
Watch OS相关：config键值在软件的IOS设置里无法保存

### ISSUE THREAD

**Issue by sakuraanzu** [lollipopkit/flutter_server_box#401]
Watch OS相关：config键值在软件的IOS设置里，写入后无法保存https://github.com/lollipopkit/server_box_monitor/assets/81692273/067b791a-910c-45ae-a77b-8fc4ded7aa80

**Comment by lollipopkit** [comment]
点了右上角保存吗

**Comment by sakuraanzu** [comment]
是的肯定点了
