### ISSUE TITLE
是否可以将ping和base64加到二级菜单

### ISSUE THREAD

**Issue by onenora** [lollipopkit/flutter_server_box#41]
- [ ] 如题，这两个功能使用频率其实很低，是否可以在设置界面选择折叠这2个菜单
- [ ] 主界面保留一个服务器界面即可
- [ ] 设置界面可以选择这两个是否在底部显示

**Comment by jaychoubaby** [comment]
同，这俩功能几乎没什么用，还占据主要位置

**Comment by lollipopkit** [comment]
会在discussion开启投票，以投票决定。

个人认为，没有影响到日常使用。
