### ISSUE TITLE
无法连接局域网内的服务器

### ISSUE THREAD

**Issue by Shicw** [lollipopkit/flutter_server_box#427]
**描述BUG**
在局域网内ssh连接,报如下错误:
SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 192.168.31.59, port = 2024

**截图**
![b9110061ab9da238cb7f584e9426e69](https://github.com/lollipopkit/flutter_server_box/assets/25601867/6b3b4da4-69cd-47bc-8ce1-dd4254b29cc6)

**设备**
- 系统： iOS15
- App版本： 1.0.992

**Comment by lollipopkit** [comment]
给了本地网络权限吗？

**Comment by Shicw** [comment]
> 给了本地网络权限吗？

确实没有给权限......
