### ISSUE TITLE
路由器SSH无法查看视图

### ISSUE THREAD

**Issue by setcurl** [lollipopkit/flutter_server_box#434]
**描述BUG**

Xiaomi AX3000T路由器开启SSH后,ServerBox获取不到服务器(路由器)信息，还报错
![Screenshot_2024-07-01-15-16-13-188_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/78637344/21f77181-a56a-4d5c-8ccf-3462011b2de4)
但是SSH能连上
![Screenshot_2024-07-01-15-25-19-061_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/78637344/0917717f-466d-4294-9bb1-a462c7f63a99)
这是啥原因？🙃

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
测试 [v1008](https://cdn.lolli.tech/serverbox/pkg/)

**Comment by setcurl** [comment]
> 测试 [v1008](https://cdn.lolli.tech/serverbox/pkg/)
可以了，但是SFTP一直在加载中....
![Screenshot_2024-07-03-22-07-13-071_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/78637344/832164d7-7772-4e1d-b53b-267cab293397)

**Comment by lollipopkit** [comment]
90%可能因为路由器没有安装sftp

**Comment by lollipopkit** [comment]
其原理可能是 scp，并非 sftp

**Comment by setcurl** [comment]
> 其原理可能是 scp，并非 sftp

那能支持一下嘛🌝

**Comment by lollipopkit** [comment]
在 #452 跟踪进度
