### ISSUE TITLE
ssh，按住左方向键的时候，建议可以一直往回走

### ISSUE THREAD

**Issue by Whichbfj28** [lollipopkit/flutter_server_box#45]
ssh，按住左方向键的时候，建议可以一直往回走。

如果输入一长串命令，发现一开始字符输错了，要点很多下。

**Comment by lollipopkit** [comment]
`HOME` 可以直接到开头，`Alt + 左/右` 可以以单词为单位移动

**Comment by lollipopkit** [comment]
已实现 0022294ea4410588d6ee1019aea7a6e402a7bc50
