### ISSUE TITLE
离谱，离谱，离大谱

### ISSUE THREAD

**Issue by ArcCal** [lollipopkit/flutter_server_box#451]
因为使用serverbox，我的多台vps失去控制，从来没想是serverbox的锅。

直到昨天才知道原因：

serverbox会在系统上生出一个目录，我不知道他在干啥，就把这目录删除了。

然后ssh密钥就失效了。使用正确的用户名和密钥，也无法登陆机器了。

这就是为啥机器无法ssh登陆但其他已经部署的服务还在运行的原因。

**Comment by lollipopkit** [comment]
不多说：代码开源 + 构建可重现
