### ISSUE TITLE
 FormatException: Unexpected extension byte (at offset 5)

### ISSUE THREAD

**Issue by Antiviolance** [lollipopkit/flutter_server_box#453]
![2024-07-07_17-55-05](https://github.com/lollipopkit/flutter_server_box/assets/174950476/da9c3a2c-578c-44d2-93ca-6658a9ff0b66)
 That's the problem that arises. What could it be? Encoding?

**Comment by eraser333** [comment]
I meet this problem too

**Comment by Antiviolance** [comment]
It's a pity no one can help here(

**Comment by Antiviolance** [comment]
I have a connection to a machine with Windiows 10 and I don't understand what the reason is.

**Comment by lollipopkit** [comment]
Is this a Windows ssh server?

No plans for Windows ssh server support.

**Comment by Antiviolance** [comment]
> Is this a Windows ssh server?
> 
> No plans for Windows ssh server support.

Oh, I could really use this (

**Comment by lollipopkit** [comment]
I'm sorry, I have no knowledge about related content for implementing this on Windows.

**Comment by lollipopkit** [comment]
You can track it #483
