### ISSUE TITLE
ServerBox on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [lollipopkit/flutter_server_box#456]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have ServerBox listed in the repo. Please review the listing at https://www.openapk.net/serverbox/tech.lolli.toolbox/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by lollipopkit** [comment]
Thank you for your work. I will add the download banner link.

**Comment by mobilenetworkltd** [comment]
I noticed that you have another app - GPTBox. Do you want me to add it to OpenAPK also?

**Comment by lollipopkit** [comment]
Yes, please.

**Comment by mobilenetworkltd** [comment]
Here it is https://www.openapk.net/gptbox/flutter.gpt.box/. Maybe you can send me an icon file. I could not find one.

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_gpt_box/blob/main/assets/app_icon.png

**Comment by mobilenetworkltd** [comment]
Thank you very much. Wish you good day.

**Comment by lollipopkit** [comment]
Have a great day too!
