### ISSUE TITLE
更新推送无法下载

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#457]
**描述BUG**
收到1011的更新推送无法下载，推送提示框只显示了个版本号无内容，点击更新跳转到 https://[cdn.lolli.tech](https://cdn.lolli.tech/serverbox/pkgServerBox_1011_windows_amd64.zip)/serverbox/pkgServerBox_1011_windows_amd64.zip
404无法访问

**截图**
![image](https://github.com/lollipopkit/flutter_server_box/assets/159670257/ac29c702-c9f3-4cfa-b9ff-c664d973636d)
![image](https://github.com/lollipopkit/flutter_server_box/assets/159670257/2b6b53a5-89c4-4429-afc9-f90cdd282fc6)

**设备**
系统：win11 & 安卓12
App版本： 1.0.992

**Comment by lollipopkit** [comment]
感谢，已修复
