### ISSUE TITLE
查看错误bug

### ISSUE THREAD

**Issue by luoxiashen** [lollipopkit/flutter_server_box#469]
我连接termux的ssh查看错误但能正常连接，但是之前的版本（我不知道是那个，最近的）查看是正常的，更新后就不行
![IMG_20240719_112538.jpg](https://github.com/user-attachments/assets/22cf14a2-52fe-4431-8709-41ba22e2f8a3)

![IMG_20240719_112622.jpg](https://github.com/user-attachments/assets/027b8dec-2f21-41d8-90c3-ff6b65287998)

**Comment by luoxiashen** [comment]
992就正常，刚试了

**Comment by lollipopkit** [comment]
麻烦测试 v1020
