### ISSUE TITLE
底下三个按钮建议

### ISSUE THREAD

**Issue by Whichbfj28** [lollipopkit/flutter_server_box#47]
1、把转换和ping 和成一个 【工具 】按钮，以后新增工具也可以集合到这个工具按钮里面
2、主页面底部新增一个docker按钮，新增一个ssh,sftp按钮。

**Comment by jaychoubaby** [comment]
可以参考一下这个UI
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/0a331cd1-8306-4b76-92e8-446f84c88791)![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/f00dc78a-7604-4156-9e98-4a5516c4dcb9)![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/5b90cb06-a924-4994-8f07-cba400a1368d)

- 第一页显示服务器的状态，点击服务器可以进入服务器的详情查看具体细节
- 第二页管理服务器的docker容器
- 第三页可以做ftp
- 第四页可以做设置页面

很喜欢ServerBox 希望越来越好 加油

**Comment by jaychoubaby** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/64a003c2-cb3a-4d07-b811-8fde17286279)
