### ISSUE TITLE
RangeError (length): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by itsandrewpao** [lollipopkit/flutter_server_box#470]
**描述BUG**

Logs(1017)

[17:08] [Root] [WARNING]

RangeError (length): Invalid value: Only valid value is 0: 1

#0  UpgradePkginfo._parseYum (package:server_box/data/model/pkg/upgrade_info.dart)
#1 new UpgradePkginfo (package:server_box/data/model/pkg/upgrade_info.dart:17)
#2 _onPkg.<anonymous closure> (package:server_box/view/widget/server_func_btns.dart:273)
#3 MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4 ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5 new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#6 new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#7 new List.of (dart:core-patch/array_patch.dart:39)
#8 ListIterable.toList (dart:_internal/iterable.dart:224)
#9 _onPkg (package:server_box/view/widget/server_func_btns.dart:273)

<asynchronous suspension>

**复现步骤**

**期望结果**

能否在 wiki 中 详细描述一下 pkg 功能

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
该功能的作用仅为一键更新系统

因为该功能需要兼容众多系统, 难以维护, 且手动更新并不难, 因此决定暂时移除
