### ISSUE TITLE
Biometric Auth will be skipped if you press cancel

### ISSUE THREAD

**Issue by hlarc** [lollipopkit/flutter_server_box#486]
**Describe the bug**
If you enable Biometric Authentication and press cancel during Authentication the App will just open wich defeats the purpose of Authentication 

**To Reproduce**
Activate Biometric Authentication in the Settings and then reopen the app and press cancel.

**Desired Results**
It should re prompt me or show a button to reprompt me the Auth.

**Actual Results**
It just opens the App.

**Logs** 
There was nothing in the Logs

**Device**
OnePlus Nord 3
Android 14

**Additional context**
Nothing to add

**Comment by lollipopkit** [comment]
[v1029](https://cdn.lolli.tech/serverbox/pkg/) fixed, please test.

**Comment by lollipopkit** [comment]
Fixed in v1034
