### ISSUE TITLE
1.0.1018版本连接termux显示错误

### ISSUE THREAD

**Issue by 88484396** [lollipopkit/flutter_server_box#493]
**描述BUG**

连接termux的时候界面报错，显示：

未知

```sh
Segments: expect 16, got 1, raw:

sh: 0: cannot open /dev/shm/srvboxm_v51.sh: No such file

测试ssh正常。普通的linux服务器正常。

我看issue提到以前的是可以正常显示的，所以提交了这个问题。

![Screenshot_20240726-133542_ServerBox](https://github.com/user-attachments/assets/e0782364-24b9-4b0f-acdd-4ec6e2f151d5)

**Comment by 88484396** [comment]
![Screenshot_20240726-133542_ServerBox](https://github.com/user-attachments/assets/9ec03771-6870-4642-b032-3449ea377002)

**Comment by lollipopkit** [comment]
麻烦测试 [1029](https://cdn.lolli.tech/serverbox/pkg/)

包含了数据库迁移, 请提前备份

**Comment by 88484396** [comment]
![Screenshot_20240726-141713_ServerBox](https://github.com/user-attachments/assets/604589cf-e36f-475a-a2c9-b31280c66933)
变成灰色这样了

**Comment by 88484396** [comment]
![Screenshot_20240726-202532_ServerBox](https://github.com/user-attachments/assets/2822fa6d-2ca4-4746-a24d-b77d4c9be993)
那个228就是termux

**Comment by lollipopkit** [comment]
看报错应该是网络问题, 无法访问设备, 但是灰色确实是个问题

**Comment by 88484396** [comment]
> 看报错应该是网络问题, 无法访问设备, 但是灰色确实是个问题

ssh没问题，能正常连上，只有那个面板有问题
![Screenshot_20240726-214906_ServerBox](https://github.com/user-attachments/assets/f74b9c4f-e23a-4d9b-b650-3f7c36ae8907)

**Comment by lollipopkit** [comment]
麻烦测试 1032

**Comment by 88484396** [comment]
> 麻烦测试 1032

ok了，能显示了，辛苦
