### ISSUE TITLE
小部件添加后失效

### ISSUE THREAD

**Issue by happytbs** [lollipopkit/flutter_server_box#498]
**描述BUG**

添加小部件后没反应

**复现步骤**
如何复现：
1. 打开 设置
2. 点击 'Android设置'
3. 选择 ‘卓面部件链接设置’
4. 点击添加，输入对应信息（包括创建的小部件id）
5. 保存

**期望结果**
小部件显示绑定的服务器信息

**实际结果**
仍然保留在显示id的状态

**截图**
![20cce1fec8f2c8dbcfc8f924d917f4b](https://github.com/user-attachments/assets/0e3faa6c-038d-43c1-b60d-be3719a04483)
![3ceca835021f851aec6a7eef1bdae7d](https://github.com/user-attachments/assets/f1fb5a1c-17da-4ace-af90-24dc52a68f24)

**设备**

- 系统： Android14 XiaomiHyperOS1.0
- App版本：1.0.1034

**更多信息**

无

**Comment by lollipopkit** [comment]
请等待发布更新，或者尝试[测试版](https://cdn.lolli.tech/serverbox/pkg/?sort=time&order=desc)

**Comment by GKK2024** [comment]
# 版本1.0.1104,系统Android13  MIUI14.02 ; Andriod9  lineageos16
### 问题依旧存在：局域网条件下，测试安卓版serverbox桌面小部件读取monitor数据，表现为小部件只显示ID值，不显示服务器monitor的数据。同一局域网、服务器，苹果端小部件正常显示数值。测试时间：2024年12月9日。
### 期待后期得到修复。
### Android13  MIUI14.02 
![QQ图片20241209202317](https://github.com/user-attachments/assets/9bd3f9cd-b0c7-4dae-a5e1-edbb708911c2)
###  Andriod9  lineageos16
![QQ图片20241209202229](https://github.com/user-attachments/assets/79ca2d7f-b060-4f94-980c-ab2cedadd30f)
### iPhone13  ios 18
![QQ图片20241209202220](https://github.com/user-attachments/assets/c362029e-1ecd-4304-bf34-c03b8d8ec29a)
