### ISSUE TITLE
添加SSH私钥报错

### ISSUE THREAD

**Issue by FourLeafTec** [lollipopkit/flutter_server_box#5]
添加私钥报错 PEM header must end with -----

私钥格式如下，是ed25519算法生成的

```
-----BEGIN OPENSSH PRIVATE KEY-----
b3...M=
-----END OPENSSH PRIVATE KEY-----
```

**Comment by LollipopKit** [comment]
末尾有换行符吗？去掉试试。
下个版本会自动trim()。
感谢。

**Comment by FourLeafTec** [comment]
感觉不是这个问题，PEM header行末是支持换行的，也尝试了去掉header，body，footer末尾的换行，都还是报错

我另一台服务器是RSA密钥倒是没事，header、body、footer都有行末换行，所以比较像是ed25519支持有点问题，可能跟长度有关，ed25519算法生成的密钥都比较短

**Comment by LollipopKit** [comment]
试了试ed25519，没有复现。

可以看看[源码](https://github.com/TerminalStudio/dartssh2/blob/02a166ff04da6f34858c251bb3ad61c2145edc95/lib/src/ssh_pem.dart#L30)，检查下是否存在空白字符。

**Comment by LIPiston** [comment]
我遇到了类似的问题

私钥保存成功了
并不能保存我输入的私钥密码

**Comment by mostcute** [comment]
感觉是回车的问题，我从terniaml复制出来报添加私钥报错 PEM header must end with -----

但是复制出来找个聊天软件发送一遍，从聊天窗口复制出来就可以用了

**Comment by mostcute** [comment]
@FourLeafTec

**Comment by hisune** [comment]
同密钥无法保存，直接卸载了

**Comment by syk6666** [comment]
添加SSH私匙  提是错误 服务器是dmit的

**Comment by Butwhy1** [comment]
> 添加SSH私匙 提是错误 服务器是dmit的

 不要标头和标尾，只复制秘钥部分复制到另一个秘钥中替换，然后复制进去就可以了

**Comment by eterice** [comment]
刚发现这个软件，结果初次使用就不能用ssh证书，一看问题已经是10月份的了，还没有解决

**Comment by wishday** [comment]
同样遇到问题  用文本编辑器复制进去 再加一行回车 然后神奇的可以了

**Comment by urosch** [comment]
This does not work unfortunately.

**Comment by kai19982** [comment]
我尝试在xshell导入私钥，然后在xshell重新导出就可以成功添加不会报错

**Comment by lollipopkit** [comment]
已修复https://github.com/lollipopkit/flutter_server_box/pull/281，如果仍有问题，请再次开启
