### ISSUE TITLE
1034版本 ssh的键盘变成安全键盘了

### ISSUE THREAD

**Issue by Carlos920** [lollipopkit/flutter_server_box#500]
**描述BUG**

今天更新到1034版本后，ssh的键盘变成了小米安全键盘，没更新前是搜狗输入法

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**
- 系统：小米12 pro  Android14
- App版本： 1.0.1034

**更多信息**

**Comment by lollipopkit** [comment]
建议：
0. 设置内关闭 `输入法字符缓存` (`letter cache`)
1. (可选) 关掉没有用的安全键盘
2. (可选) 使用 Gboard、Rime 等输入法
