### ISSUE TITLE
没法添加ssh





### ISSUE THREAD

**Issue by 2006tangzhi** [lollipopkit/flutter_server_box#52]
**描述BUG**
一个关于BUG的清晰描述。
没法添加ssh 
其他软件可以
**复现步骤**
如何复现：
1. 打开 '...'
2. 点击 '....'
3. 滚动到 '....'
4. 看到错误

**期望结果**
一个关于你期望的结果的清晰描述。

**实际结果**
一个关于实际结果的清晰描述。

**截图**
如果可以，请添加截图（包括错误界面和日志界面）来帮助解释你的问题。![Screenshot_2023-05-28-15-09-23-942_com.sonelli.juicessh.jpg](https://github.com/lollipopkit/flutter_server_box/assets/95123678/e096d8d8-0d80-4d8c-94a1-5906bfc82f54)

![Screenshot_2023-05-28-15-08-02-810_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/95123678/640b4407-0d80-4a49-a155-4d8d4ab9ba18)

**设备**
 - 系统： e.g. iOS16 or Android13
 - App版本： e.g. 1.0.302

**更多信息**
在这里添加关于这个问题的更多信息。

**Comment by lollipopkit** [comment]
大概率是系统、网络的问题，可以尝试关闭流量后连接
