### ISSUE TITLE
多个ssh窗口时，在一个窗口粘贴，会粘贴到其他ssh窗口里

### ISSUE THREAD

**Issue by likecreep** [lollipopkit/flutter_server_box#522]
**描述BUG**
多个ssh窗口时，在一个窗口粘贴，会粘贴到其他ssh窗口里

**复现步骤**
多个ssh窗口时，在一个窗口粘贴，会粘贴到其他ssh窗口里

**期望结果**
在当前窗口粘贴

**实际结果**
会粘贴到其他ssh窗口里

**设备**

- 系统： macOS  14.6.1
- App版本： 1.0.1051

**Comment by lollipopkit** [comment]
https://github.com/user-attachments/assets/c50a98aa-2889-4fd6-a5b5-5e94a3669804

已修复，请等待发布更新
