### ISSUE TITLE
希望给sftp页面增加一个返回上级的按钮

### ISSUE THREAD

**Issue by geol** [lollipopkit/flutter_server_box#531]
当前版本，下文工具栏的返回按钮在退出重进sftp以后，进入记忆的路径，再次点击返回一律返回到了根目录。希望能添加如家目录或返回上级目录的按钮。

**Comment by lollipopkit** [comment]
请等待更新，或者在 https://cdn.lpkt.cn/serverbox/pkg/?sort=time&order=desc 下载测试版
