### ISSUE TITLE
功能添加 上下流量带宽显示

### ISSUE THREAD

**Issue by duncai233** [lollipopkit/flutter_server_box#534]
上下流量带宽可以指定某一张网卡，比如eth1    不然在路由器上  (eth0的下载和上传，刚好跟eth1相反) 会直接把流量反转加一倍

**Comment by duncai233** [comment]
之前显示没问题，不知道为什么现在上下一样了

**Comment by lollipopkit** [comment]
请等待更新发布，或者使用[测试版](https://cdn.lpkt.cn/serverbox/pkg/?sort=time&order=desc)

**Comment by duncai233** [comment]
我的意思就是可以给每一台服务器增加一个选项 这个选项可以决定在主页显示的网络数据是哪张网卡的数据或者全部网卡的数据

**Comment by lollipopkit** [comment]
![image](https://github.com/user-attachments/assets/4af13bf4-976c-45ef-92dd-5aad5b7b8d07)

我的，没说在哪：
首页-服务器编辑-更多-指定设备-网络
