### ISSUE TITLE
备用ssh目标无法使用

### ISSUE THREAD

**Issue by Jasonzhu1207** [lollipopkit/flutter_server_box#550]
**描述BUG**
备用ssh目标无法使用，主用寄了备用可用的情况下根本连不上，备用地址填到主用去就行了

**设备**
系统：win11&Android12
App版本： 1070

**Comment by lollipopkit** [comment]
我测试是没问题的，看看你填的备用链接？

<div display="display: flex">
<img width="100px" src="https://github.com/user-attachments/assets/8f428287-e845-4212-bb44-baabb10af9fe"></img>
<img width="100px" src="https://github.com/user-attachments/assets/0ba90123-6456-4a92-84c9-371f1fe62931"></img>
</div>

**Comment by lollipopkit** [comment]
https://cdn.lpkt.cn/serverbox/pkg/?sort=time&order=desc

试试 1076
