### ISSUE TITLE
windows客户端备份问题

### ISSUE THREAD

**Issue by alias38** [lollipopkit/flutter_server_box#562]
**win客户端点击备份，直接跳到打开此电脑，无法以文件形式备份**

**Comment by 150154906** [comment]
V1104还是有这个问题，我让GPT写了一个备份脚本，手动备份。
`
@echo off
echo ==================================
echo 确实是否需要【备份】（按任意键继续）
echo ==================================
pause

setlocal

:: 定义路径
set "path_A=%USERPROFILE%\AppData\Roaming\ServerBox"
set "path_B=.\backup"

:: 创建目标目录（如果不存在）
if not exist "%path_B%" (
    mkdir "%path_B%"
)

:: 文件列表
set "file_list=docker_enc.hive history_enc.hive key_enc.hive no_backup_enc.hive server_enc.hive setting_enc.hive snippet_enc.hive srvbox_bak.json"

:: 遍历文件并复制
for %%F in (%file_list%) do (
    if exist "%path_A%\%%F" (
        copy "%path_A%\%%F" "%path_B%" >nul
        echo 复制成功：%%F
    ) else (
        echo 文件未找到：%%F
    )
)
`
