### ISSUE TITLE
希望可以自定义app背景色

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/flutter_server_box#57]
主题色可以自定义真的太好了，但是背景颜色好像不是纯白色或者纯黑色，导致整个界面看起来不够简洁，显得节目不够高级，如果角色背景色白色或者黑色不好，那是否可以考虑可以自定义背景颜色，谢谢

**Comment by lollipopkit** [comment]
已实现全黑（AMOLED模式），但不考虑自定义，遵循Material Design

**Comment by jaychoubaby** [comment]
> 已实现全黑（AMOLED模式），但不考虑自定义，遵循Material Design

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/a21dc344-2c01-4c5f-b558-1bcff0470ba1)
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/ef7c321b-f357-4eb3-bc71-5d96d128a6e9)
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/4fed41cd-c8ca-4798-b231-cc7fd4b92089)
可是你可以发现  几乎每一个页面的背景不是完全的黑色，可能是因为自定义的颜色有了一层蒙版导致背景色不能全黑或者全白，导致看起来不是很协调，有一种旧旧的感觉，只是个人意见，当然如果你坚持你的看法我也同意，这个不会影响主要功能，只是一个视觉感受，希望你不会介意我提出的我这一个看法，再次感谢你开发的这款好用的app

**Comment by lollipopkit** [comment]
......???

026e951

![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/e6e56f25-6bc6-4232-9354-cc2b9af9a02e)
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/4c5c87cc-5723-4b6e-991f-17143bee5879)

**Comment by jaychoubaby** [comment]
> ......???
> 
> [026e951](https://github.com/lollipopkit/flutter_server_box/commit/026e951604b83f355bc445d70bfa7c461c0f8992)
> 
> ![image](https://user-images.githubusercontent.com/10864310/242531998-e6e56f25-6bc6-4232-9354-cc2b9af9a02e.png) ![image](https://user-images.githubusercontent.com/10864310/242531704-4c5c87cc-5723-4b6e-991f-17143bee5879.png)

I understand that the current version of App Store is still 338. Looking forward to an update.
