### ISSUE TITLE
如果密码里面含有特殊字符，会登录不了

### ISSUE THREAD

**Issue by cikichen** [lollipopkit/flutter_server_box#573]
当密码里面有一些特殊字符，比如&之类的，会提示参数错误，无法登录

**Comment by lollipopkit** [comment]
无法复现

https://github.com/user-attachments/assets/7a46efe5-d0f3-458c-bf48-a7e42c258fc0

**Comment by cikichen** [comment]
> 无法复现
> 
>  VID_20240914_174126.mp4

应该是serv00的问题

**Comment by cikichen** [comment]
> 无法复现
> 
>  VID_20240914_174126.mp4

还是有问题。
![QQ_1726629690159](https://github.com/user-attachments/assets/18ec38e6-0d6a-4ce5-8da0-0729a6614e58)


未知

```sh
SSHAuthAbortError(Connection closed before authentication: SSHInternalError(Invalid argument(s): responses.length (1) != message.prompts.length (0)))
