### ISSUE TITLE
关于加载页面优化

### ISSUE THREAD

**Issue by luoxiashen** [lollipopkit/flutter_server_box#575]
这个加载页面可不可以优化一下，每次看着都好别扭，老版本到是没这感觉，非要加的话希望不要占那么大的屏幕，看着有点难受![Screenshot_2024-09-14-13-54-22-837_tech.lolli.toolbox.jpg](https://github.com/user-attachments/assets/8c8616de-5708-4045-8a93-a23ad920b755)

**Comment by lollipopkit** [comment]
已修复，但未发布
