### ISSUE TITLE
我的终端进去就卡死了，能输入命令，但点执行没反应。我电脑上正常，WIN11+终端访问没问题。

### ISSUE THREAD

**Issue by dianso** [lollipopkit/flutter_server_box#59]
我的终端进去就卡死了，能输入命令，但点执行没反应。

手机小米12S

进中断后默认启用小米安全键盘，没法选择其他键盘。

输入命令点击回车按钮不管用

**Comment by lollipopkit** [comment]
把小米安全键盘关了试试？

关于输入法的问题我不太会解决，网上资源也很少，抱歉

**Comment by dianso** [comment]
这个app默认调用了安全键盘，miui中安全键盘是输入密码时候强行唤起的，此时不可以切换其他输入法。

**Comment by dianso** [comment]
百度了下，找到方法彻底关闭安全键盘了
回车键可以了

**Comment by dianso** [comment]
OK了
