### ISSUE TITLE
没办法添加ssh密钥

### ISSUE THREAD

**Issue by yuchen1204** [lollipopkit/flutter_server_box#6]
尝试粘贴密钥时无法操作

https://user-images.githubusercontent.com/92127505/211215586-4b684692-534f-49d2-a04a-96c9c9118c12.MOV

**Comment by lollipopkit** [comment]
很抱歉，我这里没有这个错误。

https://user-images.githubusercontent.com/10864310/211247132-f9be3192-fe4f-4ca7-ae20-04da5c408d2d.MP4


但是新增了[自动粘贴功能](https://github.com/lollipopkit/flutter_server_box/blob/9c8f9c3b9f76f00aa9b7efee0a107ea798d31b17/lib/view/page/private_key/edit.dart#L155)，希望能解决你的问题。

**Comment by lollipopkit** [comment]
如果自动粘贴未能解决问题，请重开issue
