### ISSUE TITLE
向上滑动存在bug

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/flutter_server_box#60]
https://github.com/lollipopkit/flutter_server_box/assets/26641387/8a4e6d04-26b8-403d-b6e5-8f243d48e813

当服务器较多时，手指向上滑动屏幕会一直停留在原地

**Comment by jaychoubaby** [comment]
我来描述一下出现的步骤：
1.打开app 进入docker管理，查看docker日志
2.返回首页
3.向上滑动，就会出现一直停留在原地的bug

**Comment by jaychoubaby** [comment]
> 最新版本还有这个问题吗？

新版本目前没有再出现这个问题了，我先关闭了，谢谢

**Comment by jaychoubaby** [comment]
这个问题依然存在，我录制了视频，可以看到每次我划动一部分之后它会弹回原始位置

https://github.com/lollipopkit/flutter_server_box/assets/26641387/0f2d5a1c-b26f-439c-a954-3b3b502f0dc9

**Comment by lollipopkit** [comment]
好的，我多添加几个服务器，尝试找到问题在哪。

能麻烦看看右上角按钮页面，有无log？

**Comment by jaychoubaby** [comment]
看起来是正常的

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/4cbcfa33-1122-4cf6-9073-0988cfa3a4c9)
