### ISSUE TITLE
修改“桌面部件链接配置”会导致整个软件数据丢失

### ISSUE THREAD

**Issue by NXY666** [lollipopkit/flutter_server_box#613]
**描述BUG**

修改“桌面部件链接配置”会导致整个软件数据丢失。

**复现步骤**

1. 前往“设置 -> Android设置 -> 桌面部件链接配置”。
2. 啥也不改，点保存。（此时日志并无任何报错）
3. 关闭软件。
4. 打开软件。

**期望结果**

数据不丢失。

**实际结果**

数据全部丢失，显示初始化界面。

**截图**

https://github.com/user-attachments/assets/073007d3-8036-4108-bfee-29d6e5acabe8

**设备**

系统：Android 14
APP版本：1.0.1104

**更多信息**

**Comment by GKK2024** [comment]
# 安卓端server box，仍旧存在"桌面部件链接配置" 点击 "保存" 重置数据box APP数据问题
## 测试APP版本：1.0.1104、1.0.1070、1.0.1051
### 设备：系统Android13 MIUI14.02 ; Andriod9 lineageos16
### 问题描述：只要保存"桌面部件链接配置"必然会出现APP数据全部被重置的情况，只有"桌面部件链接配置"配置数据不会被清除。
### 复现方法：
1、“应用”-->“Android设置”-->"桌面部件链接配置"--"保存"
2、彻底关闭box APP程序，即清理Android后台的进程。
3、再次从桌面打开box APP。
### 期望效果：数据不被重置；期待修复。
https://github.com/user-attachments/assets/7abdc0b4-a52f-4a34-9dae-07eb3b2b1881
