### ISSUE TITLE
Android widget failed to load

### ISSUE THREAD

**Issue by CanglanXYA** [lollipopkit/flutter_server_box#614]
**Describe the bug**

No server status after successful login.
The screen widget will display an ID which counts up 1 everytme I create a new widget to test

**To Reproduce**

**Desired Results**

show server status

**Actual Results**

ID:number

**Screenshots**

![ResizedImage_2024-10-27_09-40-43_3055](https://github.com/user-attachments/assets/66412645-3974-40b4-91b3-f411d31dd61a)

**Device**

**Additional context**

By the way, the app data would be erased after a "force quit" at app detail page.

**Comment by konstkarapan** [comment]
Same issue here but I'm on Xiaomi hyperos
