### ISSUE TITLE
v1.0.1104 进ssh时有很大几率app崩溃闪退概率

### ISSUE THREAD

**Issue by hibuddies** [lollipopkit/flutter_server_box#616]
rt

**Comment by teemue** [comment]
I cannot open the terminal via the SSH panel, the app crashes immediately.
However, if I fire a snippet from the front page, the terminal opens.

**Comment by hsingyin** [comment]
> I cannot open the terminal via the SSH panel, the app crashes immediately. However, if I fire a snippet from the front page, the terminal opens.

Yes I'm experiencing the same thing, my device system is Android 15

**Comment by alias38** [comment]
我也是，特别是v6 only的机器

**Comment by lollipopkit** [comment]
给了通知权限吗？

**Comment by hsingyin** [comment]
> 给了通知权限吗？

![Screenshot_2024_1102_130258.jpg](https://github.com/user-attachments/assets/9fe2a6fb-611f-40e8-9f3b-a60d501ebef4)

已经给了通知权限

**Comment by teemue** [comment]
>  
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
> ----    
> Have you given notification permission?  
>       

Yes

**Comment by FuAon** [comment]
same situation with xiaomi hyperos(android 15)

**Comment by lollipopkit** [comment]
Fixed in #658
