### ISSUE TITLE
最新版(1.0.1104)首次启动ssh连接闪退

### ISSUE THREAD

**Issue by PoemMistyMoon** [lollipopkit/flutter_server_box#623]
**最新版(1.0.1104)首次启动ssh连接闪退，进入软件后直接点击连接ssh，选择任意一个ssh连接都会闪退，是这次闪退之后立刻启动软件再进行连接，就不会闪退，也就是冷启动软件第一次必闪退，闪退后立刻重启软件就不会再闪退，而且小米的三方异常监测不会监测到这个闪退，其他软件闪退的时候可以看到闪退分析*

**设备**
小米14 安卓14 澎湃OS1
软件版本:1.0.1104

**Comment by lollipopkit** [comment]
Fixed in #658
