### ISSUE TITLE
希望增加进程展示列表

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/flutter_server_box#64]
希望增加top命令展示列表，可以快速查看占用CPU最高的服务

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/9caacb28-0ecc-4e38-bad4-e849d9f9a61e)

**Comment by jaychoubaby** [comment]
我看到了新版本的快捷查看进程按钮，我体验了它，但是我感觉体验不是很好，我经常使用top命令，但是在手机上使用top只能显示一部分，所以我们希望能够给进程列表做一个新的UI页，如果你愿意的话。

**Comment by lollipopkit** [comment]
已实现，关于进程页还有更多建议吗？

**Comment by jaychoubaby** [comment]
> 已实现，关于进程页还有更多建议吗？

已经体验了一段时间，有几个建议：
1.进程页展示的进程名称如果太长的话会占满整个屏幕，希望可以精简一下，做成统一长度
2.进程占用的cpu和mem看起来好像不是动态更新的，希望可以动态更新
3.如果优化了第一条名称太长的问题，我觉得“cpu、mem、pid、user”是可以同时在一行展示

![IMG_1977](https://github.com/lollipopkit/flutter_server_box/assets/26641387/3b2eeb49-8197-46a0-a180-0457a31f926e)

**Comment by lollipopkit** [comment]
已实现，[感谢](https://github.com/lollipopkit/flutter_server_box/blob/9ffe5583fd692a3fbc2466925a53110003b15937/lib/data/res/url.dart#L16C1-L16C1)

**Comment by lollipopkit** [comment]
如果没其他问题将关闭该issue
