### ISSUE TITLE
终端无法执行命令的bug

### ISSUE THREAD

**Issue by wzry2580** [lollipopkit/flutter_server_box#65]
**描述BUG**
<!-连接服务器之后的终端的bug无法执行命令，你按回车键，他没反应 嗯，还有就是自动更新最新版，但是github 版本号看着比他还低一点，不知道是什么原因 ，-->

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by wzry2580** [comment]
手机系统 emui 8.0.0
APP版本:21.0.270
中段无法命令命令的bug，新版本依然存在 尽量修复，不然会影响体验

**Comment by mostcute** [comment]
应该是输入法回车键没有被作为enter输入

**Comment by lollipopkit** [comment]
> 应该是输入法回车键没有被作为enter输入

感觉是的，建议使用规范的输入法

请 @wzry2580 尝试关闭各厂商的“安全输入法”后反馈

**Comment by lollipopkit** [comment]
已修复，请更新至 1.0.404 及以上。若仍然有问题，请重新开启该 issue
