### ISSUE TITLE
SSH Disconnection

### ISSUE THREAD

**Issue by thirstywaterx** [lollipopkit/flutter_server_box#654]
## Description of the Issue  
In version v1.0.1104 arm for Android of the Serverbox app, the app crashes during the process of establishing an SSH connection.

## Steps to Reproduce  
1. Open the Serverbox app.  
2. Attempt to connect to a server using the SSH feature.  
3. Observe the app crashing during the connection process.

## Expected Results  
The app should remain stable and functional throughout the SSH connection process.

## Actual Results  
The app crashes while trying to establish the SSH connection, making the feature unusable.

## Device Information  
- **OS**: HarmonyOS 4  
- **Device**: Huawei Honor 20  
- **App Version**: v1.0.1104 arm for Android

**Comment by lollipopkit** [comment]
#662
