### ISSUE TITLE
Impossible to exit full screen on Android

### ISSUE THREAD

**Issue by wpisarski** [lollipopkit/flutter_server_box#657]
**Describe the bug**

Once you enable full screen mode in settings it is impossbile to exit. Everything works and I can add new hosts, but application settings are not accessible.

**To Reproduce**

Go to settings, enable full screen mode and restart the app.

**Desired Results**

There should be some way to access application settings.

**Actual Results**

No obvious way to access settings

**Screenshots**

**Device**

Google Pixel 7a, GrapheneOS compilation number 2024120900 (Android 15)
App version 1.0.1104

**Comment by lollipopkit** [comment]
A temporary solution is flip your phone to horizontal position.
