### ISSUE TITLE
页面配色很捉急

### ISSUE THREAD

**Issue by Whichbfj28** [lollipopkit/flutter_server_box#66]
推荐一个配色网站吧。作者可以去看看。里面有很多配色方案。
https://aicolors.co/
![image](https://github.com/lollipopkit/flutter_server_box/assets/47915665/3c328141-853a-4302-b978-f37ce1c1c9a8)

**Comment by lollipopkit** [comment]
丑与否是个人看法，不属于 issue。

**Comment by jaychoubaby** [comment]
其实我也觉得配色不是很好要看，不够高级，很好的app但是配色上显得不是那么高级
