### ISSUE TITLE
搜狗输入无限大写iOS

### ISSUE THREAD

**Issue by FellBan** [lollipopkit/flutter_server_box#68]
**描述BUG**

搜狗输入法一直无限大写

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/fec4090b-8309-4877-ad20-a4524f9fff89

在 1.0.407 测试未发现问题，若仍有问题，请再次开启。
