### ISSUE TITLE
MacOS 上的拖动图标会遮挡内容

### ISSUE THREAD

**Issue by whosphp** [lollipopkit/flutter_server_box#73]
MacOS 上的拖动图标会遮挡内容

**描述BUG**

![截屏2023-07-19 11 04 34](https://github.com/lollipopkit/flutter_server_box/assets/11045186/73eb3629-7253-4e4b-9190-224777888967)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by lollipopkit** [comment]
已完成，如果有问题请重新开启该issue
