### ISSUE TITLE
在进入软件时有几率出现首页大面积白块情况

### ISSUE THREAD

**Issue by canxueil** [lollipopkit/flutter_server_box#74]
**描述BUG**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

**Comment by wangfeng35** [comment]
第一次可以进入命令行窗口 后面进去就是全灰的状态。。

**Comment by lollipopkit** [comment]
> 第一次可以进入命令行窗口 后面进去就是全灰的状态。。

仍然出现这种状况吗？如果是，请在出现全灰后，返回上一页（此时可以左侧右滑），点击首页右上角的图标，截图全部log并在此回复（如果含有隐私，可以马赛克掉）。

**Comment by JohnsonRan** [comment]
> > 第一次可以进入命令行窗口 后面进去就是全灰的状态。。
> 
> 仍然出现这种状况吗？如果是，请在出现全灰后，返回上一页（此时可以左侧右滑），点击首页右上角的图标，截图全部log并在此回复（如果含有隐私，可以马赛克掉）。

![IMG_2968](https://github.com/lollipopkit/flutter_server_box/assets/89735151/627422a8-7646-43ab-a111-cf907fb3f19a)
![IMG_2969](https://github.com/lollipopkit/flutter_server_box/assets/89735151/1fadde4c-02c8-42ba-8bae-1b3d78d0c983)

**Comment by lollipopkit** [comment]
@JohnsonRan 好的，大概知道问题在哪里了，因为苹果需要上架审核，可能需要明天才能验证是否修复。

**Comment by lollipopkit** [comment]
请升级至最新版本，若仍然存在该问题，请再次开启该 issue

**Comment by JohnsonRan** [comment]
> 请升级至最新版本，若仍然存在该问题，请再次开启该 issue

我这边最新版还是1.0.407...
