### ISSUE TITLE
server_box_monitor 使用问题

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/flutter_server_box#75]
我使用小组件并部署了server_box_monitor服务，但是它好像不支持我的服务器，报错如下：

`parse disk status failed: invalid shell output
invalid disk status: /dev/mapper/centosvolume-root`

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/5de6e953-39c1-4c03-a1c5-8c0bbd4e3d85)

我的服务器参数如下：

Linux jay 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jaychoubaby** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/aff63db1-6cce-4979-82bd-3364696223f8)

我修改了配置并且重新部署容器，通过url可以得到正确的服务器名称，但是桌面组件它似乎不会更新，会一只停留在第一次添加的时候的数据

**Comment by lollipopkit** [comment]
- cpu 计算确实有问题，https://github.com/lollipopkit/server_box_monitor/issues/4
- [配置json](https://github.com/lollipopkit/server_box_monitor/wiki/%E4%B8%BB%E9%A1%B5#%E7%9B%91%E5%90%AC%E9%85%8D%E7%BD%AE)的前面部分有个 `name`，在那里修改服务器名称
- https://github.com/lollipopkit/flutter_server_box/issues/77

**Comment by lollipopkit** [comment]
> ![image](https://user-images.githubusercontent.com/26641387/255107071-aff63db1-6cce-4979-82bd-3364696223f8.png)
> 
> 我修改了配置并且重新部署容器，通过url可以得到正确的服务器名称，但是桌面组件它似乎不会更新，会一只停留在第一次添加的时候的数据

那是iOS的限制，最多半小时“自动”刷新一次

**Comment by jaychoubaby** [comment]
我配置了serverBox的token ，但是它并不能通知到我

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/369c2442-f196-4be3-a2d4-da3f0dc9aa1c)

**Comment by jaychoubaby** [comment]
> > ![image](https://user-images.githubusercontent.com/26641387/255107071-aff63db1-6cce-4979-82bd-3364696223f8.png)
> > 我修改了配置并且重新部署容器，通过url可以得到正确的服务器名称，但是桌面组件它似乎不会更新，会一只停留在第一次添加的时候的数据
> 
> 那是iOS的限制，最多半小时“自动”刷新一次

我是重新添加了一个新的组件，显示的数据是之前添加的那一个

![IMG_2210](https://github.com/lollipopkit/flutter_server_box/assets/26641387/3298280f-b0d5-4294-8911-49bcdab901e1)

**Comment by lollipopkit** [comment]
刚发了一条测试，有收到了吗？

**Comment by jaychoubaby** [comment]
> 刚发了一条测试，有收到了吗？

收到了

**Comment by lollipopkit** [comment]
> > 刚发了一条测试，有收到了吗？
> 
> 收到了

那就是没有触发monitor的阈值，需要更改配置里的rules

**Comment by jaychoubaby** [comment]
> > > 刚发了一条测试，有收到了吗？
> > 
> > 
> > 收到了
> 
> 那就是没有触发monitor的阈值，需要更改配置里的rules

好的，我设置极端一点试试，另外我发现部署之后自动生成的config.json与wiki里面写的配置样例不一样，我是按照wiki中的样例配置的，以哪个为准呢？

**Comment by lollipopkit** [comment]
wiki里是完整的配置（包含了monitor所有的可配置项），自动生成的默认配置只是一部分。

需要根据wiki来修改默认配置。

**Comment by jaychoubaby** [comment]
> > > 刚发了一条测试，有收到了吗？
> > 
> > 
> > 收到了
> 
> 那就是没有触发monitor的阈值，需要更改配置里的rules

我已经将cpu阈值设置为30，但是依然不会收到通知，并且cpu显示错误的问题依然没有得到解决，我已经更新到了最新的app以及docker，并且打开app更新小组件的功能也没有得到实现

**Comment by lollipopkit** [comment]
是每次打开（并非app处于关闭时再打开）app都刷新小组件？

**Comment by jaychoubaby** [comment]
> 

因为每次打开app的时候，app内会主动刷新服务器的信息，为何不直接吧这个信息用到小组件上显示呢？
如果不打开app，小组件则使用docker容器服务更新。

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/8bcf3f98-e9c2-4a56-925f-8212fc9367b9)

关于CPU提醒，我的是正常的，贴上你的配置我看看？

**Comment by jaychoubaby** [comment]
> ![image](https://user-images.githubusercontent.com/10864310/255802773-8bcf3f98-e9c2-4a56-925f-8212fc9367b9.png)
> 
> 关于CPU提醒，我的是正常的，贴上你的配置我看看？

{
        "version": 2,
        "interval": "30s",
        "rate": "1/10m",
        "name": "back",
        "rules": [
                {
                        "type": "cpu",
                        "threshold": "\u003e=30%",
                        "matcher": "0"
                },
                {
                        "type": "net",
                        "threshold": "\u003e=7.7m/s",
                        "matcher": "eth0"
                }
        ],
        "pushes": [
                {
            "type": "ios",
            "iface": {
                "name": "ServerBox iOS App",
                "token": "609a82ef6d0595044c17568c77d551c7d1e341b64a562da56fbf3cce995ffbfd",
                "title": "back\n{{name}} 提示",
                "content": "{{msg}}",
                "body_regex": ".*",
                "code": 200
            }
        }
        ]
}

**Comment by lollipopkit** [comment]
试着将interval改成3s，因为cpu计算是interval内的平均使用率，时间改短会更精确

30s是旧版配置没及时更新（现wiki已更新），不好意思

建议删除上面你那条评论，免得泄漏隐私（别人有token就可以给你发垃圾信息）

**Comment by lollipopkit** [comment]
- `"title": "back\n{{name}} 提示",`
里就不需要写 `back` 了，因为消息推送时，会把 `{{name}}` 替换为你的服务器名称，也就是 `back`
- `\u003e` 是大于符号，我会尝试解决

**Comment by jaychoubaby** [comment]
> 试着将interval改成3s，因为cpu计算是interval内的平均使用率，时间改短会更精确
> 
> 30s是旧版配置没及时更新（现wiki已更新），不好意思
> 
> 建议删除上面你那条评论，免得泄漏隐私（别人有token就可以给你发垃圾信息）

我按照新的配置修改了一下，docker出现了错误日志，日志如下：

[INF] [PUSH] 5 to push
[WAR] [PUSH]  error: code: 500, resp: {"code":8,"message":{"StatusCode":400,"Reason":"BadDeviceToken","ApnsID":"0B62B9AD-7F94-725D-BC7C-3E0AB6F62E2A","Timestamp":"0001-01-01T00:00:00Z"}}

[INF] [PUSH] 5 to push
[WAR] [PUSH]  error: code: 500, resp: {"code":8,"message":{"StatusCode":400,"Reason":"BadDeviceToken","ApnsID":"55ECC4B2-1BF2-B676-1C62-6CFFEE70DF40","Timestamp":"0001-01-01T00:00:00Z"}}

**Comment by jaychoubaby** [comment]
> * `"title": "back\n{{name}} 提示",`
>   里就不需要写 `back` 了，因为消息推送时，会把 `{{name}}` 替换为你的服务器名称，也就是 `back`
> * `\u003e` 是大于符号，我会尝试解决

这是新的配置：

{
        "version": 2,
        "interval": "7s",
        "rate": "1/10m",
        "name": "back",
        "rules": [
                {
                        "type": "cpu",
                        "threshold": ">=30%",
                        "matcher": "0"
                },
                {
                        "type": "net",
                        "threshold": ">=7.7m/s",
                        "matcher": "eth0"
                }
        ],
        "pushes": [
                {
            "type": "ios",
            "iface": {
                "name": "ServerBox iOS App",
                "token": "609a82ef6d0595044c17568c77d551c7d1e341b64a562da56fbf3cce995ffbfd",
                "title": "{{name}} 提示",
                "content": "{{msg}}",
                "body_regex": ".*",
                "code": 200
            }
        }
        ]
}
