### ISSUE TITLE
新增服务器界面主机栏能否增加备选主机选项？

### ISSUE THREAD

**Issue by allonmymind** [lollipopkit/flutter_server_box#78]
考虑到有些主机没有公网v4地址，或者有些云服务器可以使用域名连接，能否增加备选主机地址输入栏，这样可以免除同一主机配置两种不同连接方式

**Comment by lollipopkit** [comment]
好主意

**Comment by allonmymind** [comment]
> 好主意
移动家宽小主机没有v4苦不堪言，哈哈
顺便，发现1bug，全屏模式下，IOS和安卓端网络视图类型会默认变为连接数。

**Comment by allonmymind** [comment]
感谢这么快就上架更新此功能，但是我发现个问题，我用nginx反代ssh端口为非22端口，备选主机里不能单独指定端口号，不知能否在每个主机后面单独指定ssh端口

**Comment by lollipopkit** [comment]
已实现，若有问题请再次开启该 issue
