### ISSUE TITLE
作者您好

### ISSUE THREAD

**Issue by QingAnLe** [lollipopkit/flutter_server_box#8]
我添加服务器之后更换了服务器的IP，但是退出软件或者重启手机之后，客户端里面的服务器IP又会变成最初的旧IP，只能重新更改成新IP才能链接，但是重启手机又会变成旧IP，劳烦更新一下。

**Comment by lollipopkit** [comment]
已修复

保存不上是因为无法连接至服务器，测试时没注意到这种情况

感谢
