### ISSUE TITLE
I can't use the enter key in the terminal

### ISSUE THREAD

**Issue by kaliwell** [lollipopkit/flutter_server_box#81]
我在软件终端中不能使用enter键,在软件其他功能可以 .  : \
Mobile phone model:  Honor 50
NTH-AN00
Magic os 7.0
Android 12
version:v1.0.397
![DEMO](https://github.com/lollipopkit/flutter_server_box/assets/78673980/deb35546-00aa-468e-b238-cca0d00106f9)
可以在这个版本中荣耀50的安全键盘中的enter键可以使用
version:v1.0.270(+2)
![demo2](https://github.com/lollipopkit/flutter_server_box/assets/78673980/b059c43e-13cc-41b7-9742-b49827b61099)

**Comment by lollipopkit** [comment]
可以尝试修改设置中的“键盘类型”，推荐 `visiblePassword`。

输入法太多，不会（指的能力上）适配

**Comment by lollipopkit** [comment]
已修复，请更新至 1.0.404 及以上。若仍然有问题，请重新开启该 issue
