### ISSUE TITLE
iOS17小组件交互

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/flutter_server_box#82]
iOS17已经支持桌面小组件交互，可否给刷新图标增加一个交互动作，这样可以在桌面手动刷新服务器状态那该甚好![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/c1897195-b8b0-41ac-a2dd-88a1df5c411e)

**Comment by lollipopkit** [comment]
我搜索遍了，貌似不能在桌面手动刷新

**Comment by jaychoubaby** [comment]
>  
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
> ----    
> I've searched all over, but it seems that I can't manually refresh on the desktop  
>       

ios17新加的功能

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/154872a0-323e-4577-86a1-905fb22793a4)

**Comment by jaychoubaby** [comment]
以下是一些资料：

https://developer.apple.com/cn/ios/

https://developer.apple.com/videos/play/wwdc2023/10103/

![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/7858b4bf-d26e-4109-ac12-a9c6eb135a28)
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/9c883735-c7d2-4d26-879e-10a2ceb9e7c0)
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/bc6a65eb-3195-47dc-b95c-1cf7f5536186)
![image](https://github.com/lollipopkit/flutter_server_box/assets/26641387/635faa98-663a-410b-9e5b-e0b60d6a59ee)

**Comment by jaychoubaby** [comment]
这个是api文档： https://developer.apple.com/documentation/widgetkit

**Comment by jaychoubaby** [comment]
Starting with iOS 17, iPadOS 17, and macOS 14, people use buttons and toggles in widgets and Live Activities to interact with your app without launching it. For example, the large widget of the Emoji Rangers: Supporting Live Activities, interactivity, and animations sample code project includes a button that people tap to give the healing capability of their hero a temporary boost.
