### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by canxueil** [lollipopkit/flutter_server_box#83]
我对一个服务器进行了删除操作，并进行了确认，但当我重新启动APP时，他又出现在了我的主页上，这很奇怪，希望尽快解决，如是我的操作问题，还请指点。

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/41b68eed-0aff-433c-a38b-4888ace1955a

我这里没有问题。

会出个功能，批量删除服务器，希望能够解决。

**Comment by lollipopkit** [comment]
请先确保app版本大于等于 `1.0.402` ，然后在设置中 `批量删除服务器` 删除对应服务器

**Comment by lollipopkit** [comment]
已在 `1.0.402` 中解决，若仍有问题，请再次开启该 issue
