### ISSUE TITLE
Unraid无法链接还有华芸nas无法查看docker是大佬们没支持吧

### ISSUE THREAD

**Issue by yl948** [lollipopkit/flutter_server_box#86]

**Comment by yl948** [comment]
![IMG_1358](https://github.com/lollipopkit/flutter_server_box/assets/70079656/77bf4dd0-68b5-415b-bddb-552d52312f6d)
![IMG_1359](https://github.com/lollipopkit/flutter_server_box/assets/70079656/d5df0792-2f79-422f-a230-5bde64420082)

**Comment by yl948** [comment]
第一个是华芸nas
第二个是unraid

**Comment by lollipopkit** [comment]
麻烦在服务器上执行，并粘贴输出。如果含有隐私，请以 xx 代替
```sh
docker version
docker ps -a
docker stats --no-stream
docker image ls
```

**Comment by yl948** [comment]
需要截图吗大佬

**Comment by yl948** [comment]
每一个命令都需要复制吗
我看就是查看docker和镜像的命令


Issues-translate-bot ***@***.***>于2023年8月4日 周五17:31写道：

**Comment by lollipopkit** [comment]
嗯，因为不知道是哪一条命令出的问题（后继会优化，好定位问题）

**Comment by yl948** [comment]
这个是爱速特nas无法查看控制docker

***@***.******@***.*** # docker version
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:21:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:27:32 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.13
  GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
***@***.******@***.*** # docker ps -a
CONTAINER ID   IMAGE                                COMMAND
 CREATED         STATUS                       PORTS

                                                      NAMES
1ff984c5c823   chisbread/qbittorrent:latest         "/init"
 8 days ago      Up 8 days                    6881/tcp, 6881/udp,
0.0.0.0:6883->6883/tcp, 0.0.0.0:6883->6883/udp, :::6883->6883/tcp,
:::6883->6883/udp, 0.0.0.0:8028->8080/tcp, :::8028->8080/tcp
qbittorrent
a8968e9b2a94   linuxserver/qbittorrent:14.3.9       "/init"
 2 weeks ago     Up 2 weeks                   0.0.0.0:8027->8027/tcp,
:::8027->8027/tcp, 8080/tcp, 0.0.0.0:52252->6881/tcp, 0.0.0.0:52252->6881/udp,
:::52252->6881/tcp, :::52252->6881/udp                   qbnastool
b27d9eb25867   syly948/nastool:3.2.4                "/init"
 3 weeks ago     Up 3 weeks                   0.0.0.0:3001->3000/tcp,
:::3001->3000/tcp
                                                            nastool
f399d0579106   yipengfei/movie-robot:beta           "/bin/sh -c 'sh /app…"
  3 weeks ago     Exited (137) 2 weeks ago

                                                        mrbot
d0cc43a692bb   lswl/vertex:latest                   "/bin/sh -c 'bash /a…"
  4 weeks ago     Up 3 weeks                   0.0.0.0:3007->3000/tcp,
:::3007->3000/tcp
                                                            vertex
25afafe0af66   chisbread/transmission:latest        "/init"
 6 weeks ago     Up 3 weeks                   0.0.0.0:9091->9091/tcp,
:::9091->9091/tcp, 0.0.0.0:51413->51413/tcp, :::51413->51413/tcp,
0.0.0.0:51413->51413/udp, :::51413->51413/udp
transmission
d3cc31d7690f   portainer/portainer-ce:latest        "/portainer"
  6 weeks ago     Up 3 weeks                   0.0.0.0:8000->8000/tcp,
:::8000->8000/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 9443/tcp
                                                             portainer
61319088931d   xhofe/alist:latest                   "/entrypoint.sh"
  2 months ago    Up 3 weeks                   0.0.0.0:5244->5244/tcp,
:::5244->5244/tcp
                                                            alist
39759802bf1d   mtphotos/mt-photos:latest            "sh /usr/src/app/ent…"
  2 months ago    Exited (137) 3 weeks ago

                                                        mt-photos
59be6cdcab53   linuxserver/qbittorrent:14.3.9       "/init"
 3 months ago    Up 3 weeks                   0.0.0.0:8025->8025/tcp,
:::8025->8025/tcp, 8080/tcp, 0.0.0.0:52253->6881/tcp, 0.0.0.0:52253->6881/udp,
:::52253->6881/tcp, :::52253->6881/udp                   vtqb
874af3842fa1   lovechen/embyserver:latest           "/init"
 3 months ago    Exited (0) 3 weeks ago

                                                      emby
d3de4c9c6aa5   linuxserver/qbittorrent:14.3.9       "/init"
 4 months ago    Up 3 weeks                   0.0.0.0:6882->6882/tcp,
:::6882->6882/tcp, 6881/tcp, 8080/tcp, 6881/udp, 0.0.0.0:8026->8026/tcp,
0.0.0.0:6882->6882/udp, :::8026->8026/tcp, :::6882->6882/udp   qbqb
f755ab6f11f7   linuxserver/duplicati:latest         "/init"
 4 months ago    Up 3 weeks                   0.0.0.0:8200->8200/tcp,
:::8200->8200/tcp
                                                            duplicati
ee3f75d00946   allanpk716/chinesesubfinder:latest   "tini entrypoint.sh"
  4 months ago    Up 3 weeks                   0.0.0.0:19035->19035/tcp,
:::19035->19035/tcp, 0.0.0.0:19037->19037/tcp, :::19037->19037/tcp
                                                           chinesesubfinder
d3b82fde0773   syly948/nastools:2.9.1               "/nas-tools/docker/e…"
  4 months ago    Up 3 weeks                   0.0.0.0:3005->3000/tcp,
:::3005->3000/tcp
                                                            nastools
c89ebe332eb1   4a40e48c1fed                         "/bin/sh -c 'bash /a…"
  5 months ago    Exited (137) 4 months ago

                                                       vertex-old
56c97c9fefa4   messense/aliyundrive-webdav          "/sbin/tini -- /usr/…"
  5 months ago    Exited (137) 3 weeks ago

                                                        aliyundrive-webdav
d4f6b72fbaf3   ngfchl/ptools:latest                 "/bin/bash /ptools/s…"
  5 months ago    Exited (137) 3 weeks ago

                                                        ptools
d770fdaa9b41   iyuucn/iyuuplus:latest               "/entrypoint.sh"
  7 months ago    Up 3 weeks                   0.0.0.0:8787->8787/tcp,
:::8787->8787/tcp
                                                            IYUU
6a2b1df9787f   babde0f9fab0                         "sh /usr/src/app/ent…"
  8 months ago    Exited (143) 2 months ago    0.0.0.0:8063->8063/tcp,
:::8063->8063/tcp
                                                            mt_photos-old
76d394efd43b   linuxserver/radarr:latest            "/init"
 11 months ago   Exited (128) 2 months ago    0.0.0.0:7878->7878/tcp,
:::7878->7878/tcp
                                                            radarr
c668afd9c8f3   linuxserver/qbittorrent:4.4.2        "/init"
 12 months ago   Up 3 weeks                   0.0.0.0:6881->6881/tcp,
0.0.0.0:6881->6881/udp, :::6881->6881/tcp, :::6881->6881/udp,
0.0.0.0:8018->8080/tcp,
:::8018->8080/tcp                                 qb
7a4360ef04af   yixinrushi/video_tools:full-0.1      "python3 main.py"
 12 months ago   Exited (137) 12 months ago

                                                      video_tools
***@***.******@***.*** # docker stats --no-stre
am
CONTAINER ID   NAME               CPU %     MEM USAGE / LIMIT     MEM %
NET I/O           BLOCK I/O         PIDS
1ff984c5c823   qbittorrent        1.05%     996.1MiB / 11.47GiB   8.48%
13.6GB / 173GB    388GB / 842MB     13
a8968e9b2a94   qbnastool          0.52%     1.165GiB / 11.47GiB   10.15%
 227GB / 17.3GB    68.3GB / 130MB    13
b27d9eb25867   nastool            0.35%     205.2MiB / 11.47GiB   1.75%
2.65GB / 856MB    15.2GB / 800MB    48
d0cc43a692bb   vertex             1.32%     228.5MiB / 11.47GiB   1.94%
32.4GB / 1.66GB   421GB / 12GB      124
25afafe0af66   transmission       3.25%     525.6MiB / 11.47GiB   4.47%
69.8GB / 3.01TB   6.79TB / 6.44GB   10
d3cc31d7690f   portainer          0.00%     17.46MiB / 11.47GiB   0.15%
256MB / 91.5MB    48.5GB / 1.83GB   9
61319088931d   alist              0.00%     15.61MiB / 11.47GiB   0.13%
196MB / 1.3MB     27.9GB / 6.87MB   10
59be6cdcab53   vtqb               0.39%     10.3MiB / 11.47GiB    0.09%
778MB / 18GB      3.15GB / 41.5MB   13
d3de4c9c6aa5   qbqb               41.14%    1.791GiB / 11.47GiB   15.61%
 1.44TB / 78.5GB   131GB / 2.06GB    24
f755ab6f11f7   duplicati          0.40%     174.2MiB / 11.47GiB   1.48%
5.63GB / 4.99GB   51.7GB / 23.7GB   80
ee3f75d00946   chinesesubfinder   0.05%     9.855MiB / 11.47GiB   0.08%
241MB / 11.2kB    13.1GB / 73.7kB   9
d3b82fde0773   nastools           0.11%     77.18MiB / 11.47GiB   0.66%
337MB / 95.7MB    35.1GB / 41kB     35
d770fdaa9b41   IYUU               0.02%     17.56MiB / 11.47GiB   0.15%
563MB / 139MB     8.05GB / 23.3MB   7
c668afd9c8f3   qb                 44.44%    718.2MiB / 11.47GiB   6.11%
29.7TB / 4.73TB   23.1TB / 37.6GB   25
***@***.******@***.*** # docker image ls
REPOSITORY                     TAG        IMAGE ID       CREATED
SIZE
nastool/nas-tools              latest     b59a68dc1a68   3 weeks ago
1.09GB
syly948/nastool                3.2.4      b59a68dc1a68   3 weeks ago
1.09GB
yipengfei/movie-robot          beta       3e703df625de   3 weeks ago
1.99GB
newptools/ptools               latest     520a011b0b20   4 weeks ago
551MB
ngfchl/ptools-client-backend   latest     e2576364f1b4   7 weeks ago
497MB
yipengfei/movie-robot          <none>     bcd194a703d8   8 weeks ago
1.98GB
xhofe/alist                    latest     783cbb0d8417   2 months ago
 56.5MB
portainer/portainer-ce         latest     3d18fe6d6805   2 months ago
 273MB
nastool/nas-tools              3.2.3      d1a689dab814   2 months ago
 1.09GB
syly948/nastool                3.2.3      d1a689dab814   2 months ago
 1.09GB
lswl/vertex                    stable     a707fabe9ef9   2 months ago
 554MB
mtphotos/mt-photos             latest     250078317c54   3 months ago
 1.26GB
lswl/vertex                    <none>     5d4877524f92   4 months ago
 553MB
jxxghp/nas-tools               latest     e25507bca168   4 months ago
 1.14GB
syly948/nastool                3.2.0      e25507bca168   4 months ago
 1.14GB
linuxserver/duplicati          latest     df73bb265a94   4 months ago
 844MB
jxxghp/nas-tools               <none>     7865a4c2e2c8   4 months ago
 1.12GB
allanpk716/chinesesubfinder    latest     6b9699afe552   5 months ago
 153MB
lswl/vertex                    latest     e19876610037   5 months ago
 553MB
lswl/vertex                    <none>     4a40e48c1fed   5 months ago
 553MB
jxxghp/nas-tools               3.0.0      41683a2237dc   5 months ago
 1.12GB
syly948/nastools               2.9.1      303ebcad2acd   5 months ago
 1.11GB
jxxghp/nas-tools               <none>     8aab40b49393   5 months ago
 1.11GB
xhofe/alist                    <none>     3ba9cfc06314   6 months ago
 54.1MB
linuxserver/duplicati          <none>     740647d8389a   6 months ago
 726MB
ngfchl/ptools                  latest     f4f157f6c0e7   6 months ago
 409MB
messense/aliyundrive-webdav    latest     44ebe5cc8fda   6 months ago
 14.2MB
lovechen/embyserver            latest     d40be6aaa4d7   7 months ago
 568MB
mtphotos/mt-photos             <none>     babde0f9fab0   8 months ago
 1.25GB
javtube/javtube-server         latest     530c8c4aca6d   9 months ago
 31.2MB
lswl/vertex-base               latest     588ef8ae069e   11 months ago
441MB
linuxserver/radarr             latest     fb7a9f54e439   11 months ago
211MB
yixinrushi/video_tools         full-0.1   32dcb5308d37   12 months ago
912MB
linuxserver/qbittorrent        4.4.2      b7cf904613ca   14 months ago
223MB
chisbread/transmission         latest     d262247e0c08   14 months ago
188MB
chisbread/qbittorrent          latest     09512e6593d0   18 months ago
212MB
linuxserver/qbittorrent        14.3.9     6328840003f0   19 months ago
391MB
portainer/portainer-ce         2.9.3      ad0ecf974589   20 months ago
252MB
iyuucn/iyuuplus                latest     6e59662bbf01   22 months ago
57.6MB










这个是unraid直接无法链接

Last login: Fri Aug  4 02:26:57 2023 from 192.168.233.2
Linux 5.19.9-Unraid.
***@***.***:~# docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 22:56:42 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:45 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
***@***.***:~# docker ps -a
CONTAINER ID   IMAGE                                   COMMAND
     CREATED         STATUS                       PORTS

                              NAMES
0e4b4e22ebb0   voglerr/free-games-claimer:latest
"docker-entrypoint.s…"   3 hours ago     Exited (1) 3 hours ago

                                                  fgc
3efb4cdb5d3f   johngong/qbittorrent:latest             "/init"
     7 days ago      Up 7 days                    0.0.0.0:6881->6881/tcp,
:::6881->6881/tcp, 0.0.0.0:8989->8989/tcp, 0.0.0.0:6881->6881/udp,
:::8989->8989/tcp, :::6881->6881/udp     qeebt
e40a1bdfe2fc   nyanmisaka/jellyfin:latest
 "./jellyfin/jellyfin…"   11 days ago     Exited (143) 2 days ago

                                                   jellyfin
81d525dedf40   chisbread/qbittorrent                   "/init"
     4 weeks ago     Exited (0) 3 weeks ago

                              qbittorrent
a6561d0a58ca   crazymax/diun:latest                    "diun serve"
    4 weeks ago     Up 32 hours

                             diun2
f6afffe1f839   tickstep/aliyunpan-sync:v0.2.7          "/bin/sh -c
./app.sh"    7 weeks ago     Exited (137) 4 weeks ago

                                      aliyunpan-sync
8231c662621e   yipengfei/movie-robot:beta              "/bin/sh -c 'sh
/app…"   2 months ago    Exited (137) 2 months ago

                                   Mr
1fd57f4f0240   xingsu1021/pthelper:latest
 "/usr/local/bin/star…"   3 months ago    Up 4 weeks
0.0.0.0:58000->80/tcp, :::58000->80/tcp
                                                        pthelper
2ec659c9aefb   linuxserver/plex                        "/init"
     5 months ago    Exited (0) 5 months ago

                               plex
71ff91e227b5   linuxserver/qbittorrent:14.3.9          "/init"
     5 months ago    Up 4 weeks

                              qb
3b7c7ed24d46   fallenbagel/jellyseerr:latest           "/sbin/tini -- yarn
…"   5 months ago    Exited (1) 5 months ago

                               jellyseerr
ceaf2b261cea   aeert/dsback:latest                     "/bin/sh -c 'java
-D…"   5 months ago    Exited (1) 5 months ago

                                 dsback
71e50eae1fe0   tautulli/tautulli:latest                "./start.sh python
T…"   6 months ago    Exited (0) 3 weeks ago

                                tautulli
437062f9c973   likai521/nas-aurora:v0.1.0              "/bin/sh -c 'sh
/opt…"   6 months ago    Exited (137) 6 months ago

                                   nas-aurora
e85c047965ea   javtube/javtube-server:latest           "/javtube-server"
     6 months ago    Up 4 weeks                   0.0.0.0:58080->8080/tcp,
:::58080->8080/tcp
                                javtube
2e68362be36b   ghcr.io/taxel/plextraktsync:latest      "/init"
     7 months ago    Exited (1) 47 minutes ago

                               PlexTraktSync
535151b8901d   cloudnas/clouddrive:amd64               "/start.sh"
     7 months ago    Up 4 weeks

                              AliyunDrive
ba57493149c6   ghcr.io/benphelps/homepage:latest
"docker-entrypoint.s…"   7 months ago    Exited (0) 7 months ago

                                                   homepage
cdee8973a039   jlesage/nginx-proxy-manager             "/init"
     7 months ago    Up 4 weeks                   0.0.0.0:38443->4443/tcp,
:::38443->4443/tcp, 0.0.0.0:3880->8080/tcp, :::3880->8080/tcp,
0.0.0.0:7818->8181/tcp,
:::7818->8181/tcp   npm
6e79438d2650   jwstar/arbot:latest                     "python3 -u bot.py"
     7 months ago    Exited (1) 4 weeks ago

                              arbot
2914ef32271f   chisbread/qbittorrent                   "/init"
     8 months ago    Exited (0) 5 months ago

                               qbrs
a41d1f471e6f   lovechen/embyserver                     "/init"
     8 months ago    Exited (0) 4 months ago

                               embyserver
8a5454fe7acc   jellyfin/jellyfin-vue:unstable-static
"/docker-entrypoint.…"   8 months ago    Exited (0) 4 months ago

                                                   Jellyfin-vue-static
dee12e9b3cfd   ghcr.io/dusk-labs/dim:dev               "./dim"
     8 months ago    Exited (137) 8 months ago

                               Dim
c38a65ac312b   jlesage/mkvtoolnix                      "/init"
     8 months ago    Exited (0) 8 months ago

                               mkvtoolnix
e700990d60f7   mongo
"docker-entrypoint.s…"   8 months ago    Exited (132) 8 months ago

                                                   MongoDB
8494f047d9fe   ghcr.io/petio-team/petio                "/sbin/tini -- node
…"   8 months ago    Exited (143) 8 months ago

                               petio
8663bec3566c   p3terx/aria2-pro                        "/init"
     8 months ago    Up 4 weeks                   0.0.0.0:6800->6800/tcp,
:::6800->6800/tcp, 0.0.0.0:6888->6888/tcp, :::6888->6888/tcp,
0.0.0.0:6888->6888/udp,
:::6888->6888/udp     aria2-pro
051b2e5108a5   xhofe/alist:latest                      "./alist server
--no…"   8 months ago    Up 4 weeks                   0.0.0.0:5244->5244/tcp,
:::5244->5244/tcp
                                AList
c7c6d240e77e   yanyaobbb/mrhelper                      "/bin/sh -c 'cd
/app…"   8 months ago    Up 4 weeks                   80/tcp,
0.0.0.0:8787->8787/tcp,
:::8787->8787/tcp
                        mrhelper
5fc2ff2feac8   kodcloud/kodbox                         "/entrypoint.sh
/usr…"   9 months ago    Up 4 weeks                   443/tcp, 9000/tcp,
0.0.0.0:8050->80/tcp, :::8050->80/tcp
                                     kodbox
f23cc30d0135   neosmemo/memos                          "./memos --mode
prod…"   9 months ago    Exited (2) 9 months ago

                                   memos
8cf7c86312cb   lscr.io/linuxserver/nginx               "/init"
     10 months ago   Exited (0) 10 months ago

                              nginx
0618c1fef067   flaresolverr/flaresolverr               "/usr/bin/dumb-init
…"   10 months ago   Up 4 weeks                   0.0.0.0:8191->8191/tcp,
:::8191->8191/tcp
                                flaresolverr
99209951efeb   linuxserver/radarr                      "/init"
     10 months ago   Exited (0) 10 months ago

                              radarr
acb559cf8ed3   linuxserver/sonarr                      "/init"
     10 months ago   Exited (0) 10 months ago

                              sonarr
abd0d2ec4b6e   lscr.io/linuxserver/freshrss            "/init"
     10 months ago   Exited (0) 7 months ago

                               freshrss
868af146a52c   diygod/rsshub                           "dumb-init -- npm
ru…"   10 months ago   Up 4 weeks                   0.0.0.0:1200->1200/tcp,
:::1200->1200/tcp
                                RSSHub
2d3b02f27150   oscar1011/easy_xarr:main                "/init python3
Main.…"   10 months ago   Exited (1) 10 months ago

                                    easy_xarr
0ab11664c8c0   cr.hotio.dev/hotio/jackett              "/init"
     11 months ago   Exited (0) 10 months ago

                              jackett
47f94ef34afa   lscr.io/linuxserver/mariadb             "/init"
     11 months ago   Up 4 weeks                   0.0.0.0:3306->3306/tcp,
:::3306->3306/tcp
                                MariaDB
528a0335585e   xiaoyi510/xarr-notify                   "/bin/sh -c
./XArr-N…"   11 months ago   Up 4 weeks
0.0.0.0:8085->8085/tcp,
:::8085->8085/tcp
                                xarr-notify
7a2a80d5cb93   cr.hotio.dev/hotio/prowlarr:testing     "/init"
     11 months ago   Exited (0) 11 months ago

                              prowlarr
d44b3c231752   likun7981/hlink                         "/bin/sh -c 'hlink
s…"   11 months ago   Exited (137) 11 months ago

                                hlink
c3051ae3ba82   portainer/portainer-ce                  "/portainer"
    13 months ago   Exited (2) 13 months ago

                              Portainer-CE
6d1e13f61d9d   homeassistant/home-assistant            "/init"
     13 months ago   Exited (0) 13 months ago

                              Home-Assistant-Core
f1d193d24d1d   321661/snap2html
 "container-entrypoin…"   13 months ago   Exited (0) 11 months ago

                                                    snap2html
61c2585e32fa   adminer                                 "entrypoint.sh
docke…"   13 months ago   Up 4 weeks                   0.0.0.0:8411->8080/tcp,
:::8411->8080/tcp
                                adminer
***@***.***:~# docker stats --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET
I/O           BLOCK I/O   PIDS
3efb4cdb5d3f   qeebt          0.04%     18.57MiB / 7.604GiB   0.24%
1.43GB / 148MB    0B / 0B     20
a6561d0a58ca   diun2          0.05%     24.56MiB / 7.604GiB   0.32%
468MB / 132MB     0B / 0B     11
1fd57f4f0240   pthelper       8.04%     604.7MiB / 7.604GiB   7.77%
33.3MB / 2.05MB   0B / 0B     7
71ff91e227b5   qb             0.12%     520.4MiB / 7.604GiB   6.68%
4.88GB / 41.2GB   0B / 0B     13
e85c047965ea   javtube        0.00%     77.35MiB / 7.604GiB   0.99%
36MB / 579kB      0B / 0B     7
535151b8901d   AliyunDrive    0.34%     294.1MiB / 7.604GiB   3.78%     0B
/ 0B           0B / 0B     52
cdee8973a039   npm            0.41%     126.9MiB / 7.604GiB   1.63%
116GB / 58.1GB    0B / 0B     26
8663bec3566c   aria2-pro      0.01%     4.762MiB / 7.604GiB   0.06%
25.2MB / 160kB    0B / 0B     6
051b2e5108a5   AList          0.00%     25.06MiB / 7.604GiB   0.32%
17.7GB / 267MB    0B / 0B     16
c7c6d240e77e   mrhelper       0.25%     85.95MiB / 7.604GiB   1.10%
82.2MB / 108MB    0B / 0B     16
5fc2ff2feac8   kodbox         0.03%     120.6MiB / 7.604GiB   1.55%
24.7MB / 47.2kB   0B / 0B     17
0618c1fef067   flaresolverr   0.00%     17.79MiB / 7.604GiB   0.23%
25.8MB / 193kB    0B / 0B     12
868af146a52c   RSSHub         0.00%     65.55MiB / 7.604GiB   0.84%
27MB / 162kB      0B / 0B     24
47f94ef34afa   MariaDB        0.02%     74.23MiB / 7.604GiB   0.95%
24.7MB / 46.8kB   0B / 0B     13
528a0335585e   xarr-notify    0.01%     16.1MiB / 7.604GiB    0.21%
155MB / 81.4MB    0B / 0B     9
61c2585e32fa   adminer        0.00%     5.934MiB / 7.604GiB   0.08%
24.7MB / 46.9kB   0B / 0B     1
***@***.***:~# docker image ls
REPOSITORY                     TAG               IMAGE ID       CREATED
    SIZE
voglerr/free-games-claimer     latest            54df38f543e2   2 weeks ago
    972MB
johngong/qbittorrent           latest            847b130f0a6e   6 weeks ago
    140MB
crazymax/diun                  latest            5a71bc6fad66   7 weeks ago
    56.1MB
yipengfei/movie-robot          beta              7bc9738f7396   3 months
ago    2GB
nyanmisaka/jellyfin            latest            73f442a5e05c   3 months
ago    1.09GB
tickstep/aliyunpan-sync        v0.2.7            6370717fc574   4 months
ago    27MB
xingsu1021/pthelper            latest            19c67fe3958b   5 months
ago    2.11GB
linuxserver/plex               latest            db4e9c936319   5 months
ago    383MB
tickstep/aliyunpan-sync        v0.2.5            a082a302423b   7 months
ago    25.6MB
ghcr.io/taxel/plextraktsync    latest            c61a0f1fffdd   7 months
ago    87.1MB
tautulli/tautulli              latest            a6d03a7c8367   7 months
ago    201MB
python                         3                 75cc8d87cc34   7 months
ago    932MB
ghcr.io/benphelps/homepage     latest            812c7c1cc095   7 months
ago    195MB
likai521/nas-aurora            v0.1.0            ca03dbd32f9f   7 months
ago    3.45GB
jwstar/arbot                   latest            743ae8987d7e   7 months
ago    587MB
yipengfei/movie-robot          1.8.8             1f9677eb640b   8 months
ago    1.66GB
cloudnas/clouddrive            amd64             863a140383de   8 months
ago    293MB
cloudnas/clouddrive            latest            863a140383de   8 months
ago    293MB
aeert/dsback                   latest            0cb99445673f   8 months
ago    236MB
lovechen/embyserver            latest            aea65a567728   8 months
ago    568MB
xhofe/alist                    latest            3ce2152396a5   8 months
ago    45.1MB
yanyaobbb/mrhelper             latest            74599a6659a2   8 months
ago    1.09GB
mongo                          latest            2dd27bb6d3e6   8 months
ago    695MB
jlesage/mkvtoolnix             latest            ca7c577782b1   8 months
ago    365MB
yipengfei/movie-robot          latest            9443a14a78d6   9 months
ago    1.92GB
aeert/dsback                   1.0.0             b695a68df0aa   9 months
ago    230MB
kodcloud/kodbox                latest            cf235dc4814e   9 months
ago    472MB
fallenbagel/jellyseerr         latest            35c487516c47   9 months
ago    720MB
tickstep/aliyunpan-sync        v0.2.3            66f7416c1223   9 months
ago    25.5MB
neosmemo/memos                 latest            54ed5f86de8e   9 months
ago    23.7MB
ghcr.io/dusk-labs/dim          dev               7182a3fa42b2   10 months
ago   470MB
xhofe/alist                    main              dd283994eb45   10 months
ago   46MB
xhofe/alist                    v3.0.3            fe9d8228f0d9   10 months
ago   46MB
lscr.io/linuxserver/nginx      latest            b4dcd618cabb   10 months
ago   162MB
diygod/rsshub                  latest            dc8c0305dd64   10 months
ago   262MB
linuxserver/sonarr             latest            1fd0e31dbdae   11 months
ago   333MB
p3terx/aria2-pro               latest            997da399fc5d   11 months
ago   29.1MB
linuxserver/radarr             latest            afd333b5ff0d   11 months
ago   211MB
tickstep/aliyunpan-webdav      v0.2.1            f02bb4cb7710   11 months
ago   25.4MB
tickstep/aliyunpan-sync        v0.2.1            5afddced513e   11 months
ago   25.4MB
oscar1011/easy_xarr            main              a8b629ab224b   11 months
ago   395MB
cr.hotio.dev/hotio/jackett     latest            928e263cf847   11 months
ago   298MB
xhofe/alist                    v2                6b46a7527485   11 months
ago   40.1MB
cr.hotio.dev/hotio/prowlarr    testing           d5512ffe62bd   11 months
ago   223MB
lscr.io/linuxserver/freshrss   latest            c28a1601afc4   12 months
ago   116MB
likun7981/hlink                latest            70a2453cc9a5   12 months
ago   179MB
xiaoyi510/xarr-notify          latest            10e077b18363   12 months
ago   50.4MB
flaresolverr/flaresolverr      latest            091b16d04fc3   12 months
ago   417MB
lswl/vertex                    nextui            20c2d22c6137   12 months
ago   594MB
javtube/javtube-server         latest            7c12cf603107   12 months
ago   30.3MB
oscar1011/easy_xarr            notify_only       d3cac809d929   12 months
ago   395MB
wiw1.1                         latest            688a412d5196   13 months
ago   283MB
portainer/portainer-ce         latest            e8e975c3a7f0   13 months
ago   278MB
homeassistant/home-assistant   latest            2673e5e6bbfe   13 months
ago   1.23GB
lscr.io/linuxserver/mariadb    latest            453c62d1dc75   13 months
ago   293MB
adminer                        latest            6261a306e265   14 months
ago   90.6MB
jlesage/nginx-proxy-manager    latest            8b2f4cf2c43f   14 months
ago   192MB
linuxserver/qbittorrent        4.4.2             b7cf904613ca   14 months
ago   223MB
linuxserver/qbittorrent        latest            e3ce01e9d9f9   15 months
ago   252MB
flaresolverr/flaresolverr      v2.2.4            0f0f79e9b000   15 months
ago   416MB
chisbread/qbittorrent          latest            09512e6593d0   18 months
ago   212MB
linuxserver/qbittorrent        14.3.9            6328840003f0   19 months
ago   391MB
jellyfin/jellyfin-vue          unstable-static   37328d7844f4   19 months
ago   39.7MB
romancin/tinymediamanager      latest            42880c846cf2   21 months
ago   261MB
321661/snap2html               latest            7f80fd446b70   22 months
ago   710MB
ghcr.io/petio-team/petio       latest            41b9f0a5618f   23 months
ago   94.1MB
***@***.***:~#



lollipopkit ***@***.***>于2023年8月4日 周五17:34写道：

**Comment by yl948** [comment]
大佬给你发了你查收一下

lollipopkit ***@***.***>于2023年8月4日 周五17:34写道：

**Comment by lollipopkit** [comment]
请更新至[416](https://res.lolli.tech/serverbox/apks/416.apk)版本，然后截图报错。

**Comment by yl948** [comment]
我看appstore没显示更新

lollipopkit ***@***.***>于2023年8月5日 周六12:55写道：

**Comment by lollipopkit** [comment]
。。。你一说才知道还没审核，昨晚就申请了，大概只有等明天

**Comment by yl948** [comment]
好的大佬等明天再看看

Issues-translate-bot ***@***.***>于2023年8月5日 周六13:12写道：

**Comment by lollipopkit** [comment]
在 449 版本可以查看了吗？

**Comment by yl948** [comment]
昨天看没更新刚刚更新了一下目前Unraid可以了，突然外网都打不开docker了我回家的时候试一下，估计没啥问题了，大佬牛逼
Issues-translate-bot ***@***.***>于2023年8月8日 周二18:35写道：

**Comment by lollipopkit** [comment]
我菜，感谢支持，先关闭issue，如果有问题，再开新的

**Comment by yl948** [comment]
不知道咋了都可以显示就是打开docker一直转圈圈所以的都是，不知道是不是我网络问题
Issues-translate-bot ***@***.***>于2023年8月8日 周二18:35写道：

**Comment by yl948** [comment]
大佬说笑呢，你咋可能菜，牛逼就完事了

lollipopkit ***@***.***>于2023年8月8日 周二18:44写道：

**Comment by yl948** [comment]
大佬你自己试一下看看，我试了所有的功能都挺快就是docker一直转圈圈🤣

不知名的遥 ***@***.***>于2023年8月8日 周二18:46写道：

**Comment by lollipopkit** [comment]
https://github.com/lollipopkit/flutter_server_box/assets/10864310/d4fca106-53a6-4cd6-a2bc-d50cadaefaed

我的没问题，你能提供log（点首页右上角的按钮，然后截图）吗？

**Comment by yl948** [comment]
lollipopkit ***@***.***>于2023年8月8日 周二18:52写道：

**Comment by yl948** [comment]
大佬有没有电报之类的群

lollipopkit ***@***.***>于2023年8月8日 周二18:52写道：

**Comment by lollipopkit** [comment]
没有群。
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/82bf6966-a870-401f-a7f8-aa1af8c4105c)

发图了吗，我怎么看不到，要不用网页？不用邮箱

**Comment by yl948** [comment]
![IMG_1521](https://github.com/lollipopkit/flutter_server_box/assets/70079656/12b2118a-185e-4ce7-ae6d-0188c33966b2)
大佬你看一下

**Comment by lollipopkit** [comment]
这打开“过”docker页面吗？如果没有，需要先打开，再截图

**Comment by lollipopkit** [comment]
进这个页面，过几秒钟，就可以回log截图，如果没log，我在想想办法

**Comment by yl948** [comment]
好像链接上也没有日志，刚刚试了一下就华硕的这个nas一直转圈圈

lollipopkit ***@***.***>于2023年8月8日 周二19:24写道：
