### ISSUE TITLE
Large blank gray block in server list

### ISSUE THREAD

**Issue by karuboniru** [lollipopkit/flutter_server_box#88]
**Describe the bug**
After a certain server has been set up, the application can not show the status of the specific one but an blank block instead.

**To Reproduce**
1. Setup servers
2. Open app
3. Wait status to update

**Desired Results**
All servers should show up normall

**Actual Results**
 - Upon starting the application
![图片](https://github.com/lollipopkit/flutter_server_box/assets/3437889/4d8c8aaf-693f-47bd-a7a8-ef1980573863)
 -  Wait a few seconds, right after the status gets updated of first server 
![图片](https://github.com/lollipopkit/flutter_server_box/assets/3437889/70d09569-3ae5-43ee-8c97-d80102897f56)
 - Remove first server that appears to be working here
![图片](https://github.com/lollipopkit/flutter_server_box/assets/3437889/33482d89-f590-40ad-8ed0-5672dd80cb90)
 - Open details page before the UI breaks 
![图片](https://github.com/lollipopkit/flutter_server_box/assets/3437889/e6671054-43de-4b3a-a272-9f4e2adfa3bb)

**Screenshots**
See above

**Device**
OS: Android 13 (MIUI 14) on Xiaomi 11 (venus)
App: 1.0.407

**Additional context**
The server causing the problem is running Fedora IoT, which is a quite uncommon variant.

**Comment by lollipopkit** [comment]
Can you paste the screenshot of log screen (click top right btn on the start page) after the bug occurs?

**Comment by lollipopkit** [comment]
Please [download](https://res.lolli.tech/serverbox/apks/412.apk) it to test whether it is solved.

**Comment by karuboniru** [comment]
Yes, this time it works (at least partially). Seems that the Disk information in overview page is weird... But the major bug has gone.
![图片](https://github.com/lollipopkit/flutter_server_box/assets/3437889/04a7f29b-8cd1-45be-9fcc-c3410a20d9bf)

**Comment by lollipopkit** [comment]
Can you give me your detail disk info? It helps me to correct the display logic of overview page.
