### ISSUE TITLE
安卓味太浓了，最主要的是连个私钥导入功能都没有

### ISSUE THREAD

**Issue by wxdjs** [lollipopkit/flutter_server_box#9]
如题

**Comment by lollipopkit** [comment]
密钥导入功能是个好建议，可能会在近期加入

“安卓味”是因为我喜欢material design，如果喜欢cupertino风格，fork一份自己改(⁠•⁠‿⁠•⁠)（没别的意思）

**Comment by wxdjs** [comment]
添加key导入功能非常实用，希望早点加入，👍一个
