### ISSUE TITLE
左右滑动切换页面时有点小问题

### ISSUE THREAD

**Issue by LittleState** [lollipopkit/flutter_server_box#90]
**描述BUG**
使用滑动切换页面，到最右侧页面时还能继续翻页。

**截图**
![Screenshot_20230805-011407_ServerBox.png](https://github.com/lollipopkit/flutter_server_box/assets/25955194/209f4851-5c0a-415a-b3ba-c4e2d25a6356)

**设备**
- 系统： Android12
- App版本： 1.0.413

**Comment by lollipopkit** [comment]
感谢你的反馈，已在416版本中解决。
