### ISSUE TITLE
无法连接v6 地址

### ISSUE THREAD

**Issue by HappyQuQu** [lollipopkit/flutter_server_box#91]
**描述BUG**

安卓版不支持v6 域名的连接 显示
SSHErr<SSHErrType.connect>: alterUrl is null
ios版无此问题 配置是从ios版上恢复过来的
**复现步骤**

配置好连接后就会出现

**期望结果**

支持v6连接

**实际结果**

**截图**

![Screenshot_2023-08-05-09-55-55-118_tech.lolli.toolbox.jpg](https://github.com/lollipopkit/flutter_server_box/assets/4098823/750582f0-fd24-4869-9bcd-3f6892c8ba3c)

![IMG_20230805_095823.jpg](https://github.com/lollipopkit/flutter_server_box/assets/4098823/5877b4d6-c5c2-401a-8ddb-b8d340a8fd5a)

**设备**

![Screenshot_2023-08-05-09-58-58-283_com.android.settings.jpg](https://github.com/lollipopkit/flutter_server_box/assets/4098823/d403600f-3dfd-4db2-8b82-b612204598c0)

**更多信息**

**Comment by lollipopkit** [comment]
v6是支持的，根本原因应该是其他的。

请使用[测试版](https://res.lolli.tech/serverbox/apks/414.apk)，反馈其报错。

**Comment by HappyQuQu** [comment]
> v6是支持的，根本原因应该是其他的。
> 
> 请使用[测试版](https://res.lolli.tech/serverbox/apks/414.apk)，反馈其报错。

好了 可以正常连接了

**Comment by lollipopkit** [comment]
感谢你的反馈，现在将关闭 issue，若仍有问题，请开启新的 issue
