### ISSUE TITLE
所有设备无法访问docker标签

### ISSUE THREAD

**Issue by Yuuki-Rin** [lollipopkit/flutter_server_box#92]
**描述BUG**

所有设备无法访问docker标签

**期望结果**

能正常实现该功能

**实际结果**

**截图**

![Screenshot_2023-08-05-10-14-51-659_tech lolli toolbox-edit](https://github.com/lollipopkit/flutter_server_box/assets/63774025/d6b6755e-9c43-4a08-91ab-0fc6e8a4aeed)

**设备**

**更多信息**

docker报错：RangeError (length): Invalid value: Valid value range is lempty: 0

**Comment by Yuuki-Rin** [comment]
> **描述错误**
> 
> 所有设备无法访问 docker标签
> 
> **期望结果**
> 
> 能正常实现该功能
> 
> **实际结果**
> 
> **截图**
> 
> ![Screenshot_2023-08-05-10-14-51-659_tech 萝莉工具箱-编辑](https://user-images.githubusercontent.com/63774025/258557835-d6b6755e-9c43-4a08-91ab-0fc6e8a4aeed.jpg)
> 
> **设备**
> 
> **更多信息**
> 
> docker报错：范围错误（长度）：无效值：有效值范围为lempty：0

系统包括Ubuntu22.04 群晖7.2

**Comment by lollipopkit** [comment]
麻烦更新至416版本，发送截图，帮助我定位问题。

**Comment by Yuuki-Rin** [comment]
> 麻烦更新至416版本，发送截图，帮助我定位问题。

![Screenshot_2023-08-05-15-03-02-139_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/c00cd34e-7816-4c26-9f4a-b3d60d2ffa4f)
![Screenshot_2023-08-05-15-02-36-816_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/0be128f0-a53e-4128-a0c3-3375f9b69170)
![Screenshot_2023-08-05-15-02-42-516_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/f0c694c4-de2f-4f9d-b6d0-4e457933ab16)
![Screenshot_2023-08-05-15-02-28-317_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/11a777ab-bee4-4b70-be90-8a9abffc667a)

**Comment by lollipopkit** [comment]
不好意思，我的问题。刚刚log不够详细，麻烦升级至422，再发截图。

**Comment by Yuuki-Rin** [comment]
> 不好意思，我的问题。刚刚log不够详细，麻烦升级至422，再发截图。

![Screenshot_2023-08-05-17-20-45-470_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/d9bd9328-2303-4b8d-927e-3292b18d937f)
![Screenshot_2023-08-05-17-20-51-305_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/c7fa077b-c1bb-4ed5-a398-de0f5e960bfe)
![Screenshot_2023-08-05-17-20-58-329_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/6356ae11-e014-417a-8e9a-2732b06320a0)

**Comment by Yuuki-Rin** [comment]
> 不好意思，我的问题。刚刚log不够详细，麻烦升级至422，再发截图。
![Screenshot_2023-08-05-17-23-02-186_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/2d10832b-447c-4f3c-98f1-0c1eceb42ebf)
)
![Screenshot_2023-08-05-17-22-42-780_tech lolli toolbox](https://github.com/lollipopkit/flutter_server_box/assets/63774025/fff3ea9a-4297-47d6-8555-d1f2f7eb00d4)

**Comment by lollipopkit** [comment]
麻烦执行 `docker ps -a`，粘贴输出

**Comment by Yuuki-Rin** [comment]
> 

root@bup:~# docker ps -a
CONTAINER ID   IMAGE                         COMMAND                  CREATED       STATUS       PORTS                                                           NAMES
4cce4a32b075   mwxmmy/biliupforjava:latest   "/bin/sh -c 'java $J…"   3 weeks ago   Up 3 weeks   0.0.0.0:49141->80/tcp, :::49141->80/tcp                         bup
17f825660e97   6053537/portainer-ce          "/portainer"             4 weeks ago   Up 4 weeks   8000/tcp, 9443/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp   portainer
93d68819ca55   bililive/recorder             "dotnet /app/Bililiv…"   4 weeks ago   Up 4 weeks   0.0.0.0:49140->2356/tcp, :::49140->2356/tcp                     brec

**Comment by lollipopkit** [comment]
加QQ聊方便吗？`2036293523`
