### ISSUE TITLE
服务器右上角的三个点很难按到。

### ISSUE THREAD

**Issue by Whichbfj28** [lollipopkit/flutter_server_box#94]
没有人觉得上面这3个点很难按到吗？。ssh、sftp、docker 都是服务器上最常用的功能。偏偏缩小到那么一个按钮上。
ping跟代码片段是不需要经常编辑查看的。却放到下面3个大按钮上。
![image](https://github.com/lollipopkit/flutter_server_box/assets/47915665/6ecdc72c-5454-4884-a86c-481eba2ec969)

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/flutter_server_box/assets/10864310/ac7d3f6e-f3cc-4fb6-84fa-3cefa91ffcd0)
