### ISSUE TITLE
兼容docker安装账户与ssh登录账户不同的情况

### ISSUE THREAD

**Issue by Yuuki-Rin** [lollipopkit/flutter_server_box#95]
**描述BUG**

兼容docker安装账户与ssh登录账户不同的情况

**期望结果**

可正常获取docker的状态

**截图**

![20230805210546](https://github.com/lollipopkit/flutter_server_box/assets/63774025/ec1a4b2d-8942-4b64-9a8b-4421f05e6849)

**更多信息**

**Comment by lollipopkit** [comment]
已在 `449` 版本中实现
